### ISSUE TITLE
SLES 15 SP4 Validation 2.8

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1004]
Group 1 = 2.8/1.27/24
Group 2 = 2.8/1.26/24
Group 3 = 2.8/1.25/24
Group 4 = 2.8/1.27/23
Group 5 = 2.8/1.26/23
Group 6 = 2.8/1.25/23

|  OS | Groups |  Private AMI  | Public AMI  | User | 
|---|---|---|---|---|
| SLE 15 SP4    | G1 | ami-07a85f4472da11a6f|   | ec2-user |
| SLE 15 SP4    | G2 |  |   | ec2-user |
| SLE 15 SP4    | G3 |  ami-07a85f4472da11a6f |   | ec2-user |
| SLE 15 SP4    | G4 |  |   | ec2-user |
| SLE 15 SP4    | G5 |  |   | ec2-user |
| SLE 15 SP4    | G6 |  |   | ec2-user |

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest relevant k8s available
- Deploy local clusters using relevant k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

---

- [ ] Downstream cluster checks

| OS and version  | Downstream Cluster Type  |  G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| SLE 15 SP4 | RKE1 Custom  | Vivek  :white_check_mark: | Rishabh ✅ | Vivek ✅
| SLE 15 SP4 | RKE1 Node Driver  | ||
| SLE 15 SP4  | RKE2 Custom  |  Vivek  :white_check_mark:| Rishabh ✅| Vivek ✅ 
| SLE 15 SP4  | RKE2 Node Driver   | Vivek  :white_check_mark: | Rishabh ✅| Vivek ✅
| SLE 15 SP4  | k3s Custom   | Vivek  :white_check_mark: | Rishabh ✅| Vivek ✅
| SLE 15 SP4  | k3s Node Driver  | Vivek  :white_check_mark: | Rishabh ✅| Vivek ✅

**Although Public AMI should be used for Node Driver cluster, a Public AMI is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [ ] Rancher local cluster checks

| OS and version  | Downstream Cluster Type    | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| SLE 15 SP4 |RKE1 Imported   | Vivek :white_check_mark:  |Rishabh ✅ | Vivek ✅ | 
| SLE 15 SP4 | RKE2 Imported   | Vivek :white_check_mark:  |Rishabh ✅  | Vivek ✅ |
| SLE 15 SP4 | K3s Imported   | Vivek :white_check_mark:  |Rishabh ✅  | Vivek ✅ |

---

**Prerequisites:**
Docker 24.0.5 is installed on the OS.

**Comment by mitulshah-suse** [comment]
Closing the issue since there is no further testing planned for this.
