### ISSUE TITLE
openSUSE 15.5 Validation

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1005]
Group 1 = 2.8/1.27/24
Group 2 = 2.8/1.26/24
Group 3 = 2.8/1.25/24
Group 4 = 2.7/1.26/24
Group 5 = 2.7/1.25/24
Group 6 = 2.6/1.26/24
Group 7 = 2.6/1.25/24

|  OS | Group | Private AMI  | Public AMI  | User | 
|---|---|---|---|---|
| openSUSE 15.5 | G1 ||ami-0f0f07e28a7679ecb|ec2-user
| openSUSE 15.5 | G2 |
| openSUSE 15.5 | G3 |
| openSUSE 15.5 | G4 |
| openSUSE 15.5 | G5 |
| openSUSE 15.5 | G6 |
| openSUSE 15.5 | G7 |

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using relevant k8s version available
- Deploy local clusters using relevant k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

---

- [ ] Downstream cluster checks

| OS and version  | Downstream Cluster Type   | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| openSUSE 15.5 | RKE1 Custom  |Rishabh ✅ |Rishabh ✅ |Rishabh ✅ |
| openSUSE 15.5 | RKE1 Node Driver  || ||
| openSUSE 15.5 | RKE2 Custom  |Rishabh ✅ |Rishabh ✅ |Rishabh ✅ |||
| openSUSE 15.5  | RKE2 Node Driver  |Rishabh ✅  |Rishabh ✅  |Rishabh ✅ |||
| openSUSE 15.5  | k3s Custom  |Rishabh ✅ |Rishabh ✅ |Rishabh ✅ ||
| openSUSE 15.5 | k3s Node Driver  |Rishabh ✅ |Rishabh ✅|Rishabh ✅ ||

**Although Public AMI should be used for Node Driver cluster, a Public AMI is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [ ] Rancher local cluster checks

| OS and version  | Downstream Cluster Type  | Status  | Assignee  | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|---|---|
| openSUSE 15.5| RKE1 Imported   |pass | |Rishabh ✅|Rishabh ✅|Rishabh ✅
| openSUSE 15.5| RKE2 Imported   |pass |  |Rishabh ✅|Rishabh ✅|Rishabh ✅
| openSUSE 15.5| K3s Imported   |pass |  |Rishabh ✅|Rishabh ✅|Rishabh ✅

---
**Prerequisites:**
- Docker 24.0.5 is already installed in the ami

**Comment by mitulshah-suse** [comment]
Closing the issue since there is no further testing planned for this.
