### ISSUE TITLE
Ubuntu 22.04 OS Validation 2.8

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1007]
Group 1 = 2.8/1.27/24
Group 2 = 2.8/1.26/24
Group 3 = 2.8/1.25/24
Group 4 = 2.8/1.27/23
Group 5 = 2.8/1.26/23
Group 6 = 2.8/1.25/23

ami : ami-0e83be366243f524a

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest relevant k8s available
- Deploy local clusters using relevant k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

---

- [x] Downstream cluster checks

| OS and version  | Downstream Cluster Type  | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| Ubuntu | RKE1 Custom  |Rishabh ✅ |Rishabh ✅ |Vivek ✅|Vivek ✅ |Vivek ✅ |Vivek ✅
| Ubuntu| RKE1 Node Driver  |Rishabh ✅ |Rishabh ✅ |Vivek ✅|Vivek ✅|Vivek ✅|Vivek ✅|
| Ubuntu  | RKE2 Custom  |Rishabh ✅ |Rishabh ✅ |Vivek ✅|Vivek ✅|Vivek ✅|Vivek ✅|
| Ubuntu | RKE2 Node Driver  |Rishabh ✅  |Rishabh ✅  |Vivek ✅|Vivek ✅|Vivek ✅|Vivek ✅|
| Ubuntu  | k3s Custom  |Rishabh ✅ |Rishabh ✅ |Vivek ✅|Vivek ✅|Vivek ✅|Vivek ✅||
| Ubuntu  | k3s Node Driver  |Rishabh ✅ |Rishabh ✅|Vivek ✅|Vivek ✅|Vivek ✅|Vivek ✅||

**Although Public AMI should be used for Node Driver cluster, a Public AMI is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [x] Rancher local cluster checks

| OS and version  | Downstream Cluster Type  | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| Ubuntu| RKE1 Imported   |Rishabh ✅ |Rishabh ✅ |Vivek ✅|Vivek ✅|Vivek ✅|Vivek ✅|
|Ubuntu| RKE2 Imported   |Rishabh ✅ |Rishabh ✅  |Vivek ✅|Vivek ✅|Vivek ✅|Vivek ✅|
| Ubuntu| K3s Imported   |Rishabh ✅|Rishabh ✅  |Vivek ✅|Vivek ✅|Vivek ✅|Vivek ✅|

---
**Prerequisites**

**Comment by vivek-shilimkar** [comment]
Since all the validations for Ubuntu 22.04 for 2.8 are done. Closing the issue.
