### ISSUE TITLE
Add a test which deploys and prints workloads' images for Istio/Monitoring v1 charts

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#101]
This is for helping with the support matrix during release testing

- Create rancher server/use existing rancher server
- Create clusters/use existing clusters
- Deploy latest version of monitoring or a given version of monitoring/istio v1 chart (in case a release has multiple versions)
- Print/console out the workload pods' docker images - all in monitoring or istio related namespaces

**Comment by anupama2501** [comment]
Closing as the v1 monitoring/istio charts are deprecated.
