### ISSUE TITLE
Better reporting for provisioning time out failures

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#1011]
When a timeout happens during a provisioning test, test state/condition of the cluster should also be reported instead of just the generic time out error.

**Comment by rancher-max** [comment]
https://github.com/rancher/rancher/pull/46186
https://github.com/rancher/rancher/pull/46171
https://github.com/rancher/rancher/pull/46173

**Comment by rancher-max** [comment]
Will need a PR into 2.10 as well.
