### ISSUE TITLE
Investigate failing tests in Jenkins UI automation pipeline

### ISSUE THREAD

**Issue by izaac** [rancher/qa-tasks#1012]
There are a few tests that fail consistently in the Jenkins UI automation pipeline.

 -   Check for differences between GH Actions and Jenkins implementations
 -   Run the tests and retrieve the HTML results that include screenshots.
 -   Try to reproduce locally.

**Comment by izaac** [comment]
Root cause: #61192

**Comment by yonasberhe23** [comment]
Closing in favor of https://github.com/rancher/qa-tasks/issues/1075. That ticket has more details than this one.
