### ISSUE TITLE
Rocky Linux 9.2 OS Validation 2.8

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/qa-tasks#1017]
Group 1 = 2.8/1.27/24
Group 2 = 2.8/1.26/24
Group 3 = 2.8/1.25/24
Group 4 = 2.8/1.27/23
Group 5 = 2.8/1.26/23
Group 6 = 2.8/1.25/23

ami : ami-03d39810179b00672

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest relevant k8s available
- Deploy local clusters using relevant k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

- [ ] Downstream cluster checks

| OS and version  | Downstream Cluster Type  | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| Rocky Linux | RKE1 Custom  |Rishabh ✅ |Rishabh ✅ |Rishabh ✅
| Rocky Linux| RKE1 Node Driver  |Rishabh ✅ |Rishabh ✅ |Rishabh ✅|
| Rocky Linux  | RKE2 Custom  |Rishabh ✅ |Rishabh ✅ |Rishabh ✅||
| Rocky Linux | RKE2 Node Driver  |Rishabh ✅  |Rishabh ✅  |Rishabh ✅||
| Rocky Linux  | k3s Custom  |Rishabh ✅ |Rishabh ✅ |Rishabh ✅|
| Rocky Linux  | k3s Node Driver  |Rishabh ✅ |Rishabh ✅|Rishabh ✅|

**Although Public AMI should be used for Node Driver cluster, a Public AMI is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [ ] Rancher local cluster checks

| OS and version  | Downstream Cluster Type  | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| Rocky Linux| RKE1 Imported   |✅ |Rishabh ✅ | Vivek ✅
|Rocky Linux| RKE2 Imported   |✅ | Rishabh ✅ | Vivek ✅
| Rocky Linux| K3s Imported   |✅ | Rishabh ✅ | Vivek ✅

---
**Prerequisites**

**Comment by mitulshah-suse** [comment]
Closing the issue since there is no further testing planned for this.
