### ISSUE TITLE
Oracle Linux 9.2 OS Validations 2.8

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/qa-tasks#1028]
Group 1 = 2.8/1.27/24
Group 2 = 2.8/1.26/24
Group 3 = 2.8/1.25/24
Group 4 = 2.8/1.27/23
Group 5 = 2.8/1.26/23
Group 6 = 2.8/1.25/23

|  OS | Groups |  Private AMI  | Public AMI  | User | 
|---|---|---|---|---|
| Oracle Linux 9.2  | G1 | ami-07dc9ebe105fb556d|  ami-00aa264e184ff5703 | ec2-user |
| Oracle Linux 9.2  | G2 |  |   | ec2-user |
| Oracle Linux 9.2  | G3 |  |   | ec2-user |
| Oracle Linux 9.2  | G4 |  |   | ec2-user |
| Oracle Linux 9.2  | G5 |  |   | ec2-user |
| Oracle Linux 9.2  | G6 |  |   | ec2-user |
| Oracle Linux 9.2  | G7 |  |   | ec2-user |

ami : ami-07dc9ebe105fb556d (Created a private AMI with pre-requisite from Public AMI ami-00aa264e184ff5703)

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest relevant k8s available
- Deploy local clusters using relevant k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

- [ ] Downstream cluster checks

| OS and version  | Downstream Cluster Type  | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| Oracle Linux 9.2 | RKE1 Custom  | Vivek  :white_check_mark: | Rishabh  :white_check_mark:| Rishabh  :white_check_mark: 
| Oracle Linux 9.2 | RKE1 Node Driver  | Vivek  :white_check_mark: | Rishabh  :white_check_mark: | Rishabh  :white_check_mark:
| Oracle Linux 9.2 | RKE2 Custom  | Vivek  :white_check_mark: | Rishabh  :white_check_mark: | Rishabh  :white_check_mark:
| Oracle Linux 9.2 | RKE2 Node Driver  |  Vivek  :white_check_mark: | Rishabh  :white_check_mark: | Rishabh  :white_check_mark:
| Oracle Linux 9.2 | k3s Custom  |Vivek  :white_check_mark: | Rishabh  :white_check_mark: | Rishabh  :white_check_mark:
| Oracle Linux 9.2 | k3s Node Driver  | Vivek  :white_check_mark: | Rishabh  :white_check_mark: | Rishabh  :white_check_mark:

**Although Public AMI should be used for Node Driver cluster, a Public AMI is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [ ] Rancher local cluster checks

| OS and version  | Downstream Cluster Type  | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| Oracle Linux 9.2 | RKE1 Imported   | Vivek  :white_check_mark: |Rishabh ✅|Rishabh ✅
|Oracle Linux 9.2| RKE2 Imported   | Vivek  :white_check_mark: |Rishabh ✅|Rishabh ✅
| Oracle Linux 9.2| K3s Imported   | Vivek  :white_check_mark: |Rishabh ✅|Rishabh ✅

---
**Prerequisites**
1. Firewalld disabled
2. nm-cloud-setup.service and nm-cloud-setup.timer stopped and disabled.

**Comment by mitulshah-suse** [comment]
Closing the issue since there is no further testing planned for this.
