### ISSUE TITLE
Init Node Cannot be Removed

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1039]
https://github.com/rancher/rancher/issues/42709

**Comment by daviswill2** [comment]
This is an issue from the 2.8.0 release that should be automated.

**Comment by Josh-Diamond** [comment]
Initial PR:
https://github.com/rancher/rancher/pull/44155

**Comment by Josh-Diamond** [comment]
shepherd PR:
https://github.com/rancher/shepherd/pull/64

**Comment by markusewalker** [comment]
Merged.
