### ISSUE TITLE
Update tfp-automation Jenkinsfile to support REPO, BRANCH and TIMEOUT

### ISSUE THREAD

**Issue by markusewalker** [rancher/qa-tasks#1056]
### Issue Description
The `tfp-automation` Jenkins job currently only supports the parameters for configuration and test case. If you wish to test changes using this Jenkinsfile, or showcasing your code changes are working as expected, there isn't a great way to do this.

As such, we need to update the job to support `REPO`, `BRANCH` and `TIMEOUT`. Once done, we need to update the Jenkins job itself to reflect these new parameters.

**Comment by Josh-Diamond** [comment]
this has been tested and verified in our Jenkins env 🚀  closing out the issue now
