### ISSUE TITLE
SLES 15 SP4 Validation RM 2.7 / 2.6

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1062]
Group 7 = 2.7/1.26/24
Group 8 = 2.7/1.25/24
Group 9 = 2.7/1.26/23
Group 10 = 2.7/1.25/23
Group 11 = 2.6/1.26/24
Group 12 = 2.6/1.25/24

|  OS | Groups |  Private AMI  | Public AMI  | User | 
|---|---|---|---|---|
| SLE 15 SP4    | G7 |ami-07a85f4472da11a6f	 |   | ec2-user |
| SLE 15 SP4    | G8 |  |   | ec2-user |
| SLE 15 SP4    | G9 |  |   | ec2-user |
| SLE 15 SP4    | G10 |  |   | ec2-user |
| SLE 15 SP4    | G11 |  |   | ec2-user |
| SLE 15 SP4    | G12 |  |   | ec2-user |

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest relevant k8s available
- Deploy local clusters using relevant k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

---

- [ ] Downstream cluster checks

| OS and version  | Downstream Cluster Type  |  G7 | G8 | G9 | G10 | G11 | G12 |
|---|---|---|---|---|---|---|---|
| SLE 15 SP4 | RKE1 Custom  | :white_check_mark:  | | |
| SLE 15 SP4 | RKE1 Node Driver  | |
| SLE 15 SP4  | RKE2 Custom  | :white_check_mark:   | |  
| SLE 15 SP4  | RKE2 Node Driver   | :white_check_mark:   | | 
| SLE 15 SP4  | k3s Custom   | :white_check_mark:   | | 
| SLE 15 SP4  | k3s Node Driver  | :white_check_mark:   | | 

**Although Public AMI should be used for Node Driver cluster, a Public AMI is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [ ] Rancher local cluster checks

| OS and version  | Downstream Cluster Type    |  G7 | G8 | G9 | G10 | G11 | G12 |
|---|---|---|---|---|---|---|---|
| SLE 15 SP4 |RKE1 Imported   |  :white_check_mark:  | | | 
| SLE 15 SP4 | RKE2 Imported   | :white_check_mark:  | |  |
| SLE 15 SP4 | K3s Imported   |  :white_check_mark:  || |

---

**Prerequisites:**
Docker 24.0.5 is installed on the OS.

**Comment by mitulshah-suse** [comment]
Closing the issue since there is no further testing planned for this.
