### ISSUE TITLE
CentOS 7.9 OS Validation 2.7 / 2.6

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1064]
Group 7 = 2.7/1.26/24
Group 8 = 2.7/1.25/24
Group 9 = 2.7/1.26/23
Group 10 = 2.7/1.25/23
Group 11 = 2.6/1.26/24
Group 12 = 2.6/1.25/24

|  OS | Groups |  Private AMI  | Public AMI  | User | 
|---|---|---|---|---|
| CentOS    | G7 | ami-06815b24f17f7cab7 |    | centos |
| CentOS    | G8 | ami-06815b24f17f7cab7 |  |  centos |
| CentOS    | G9 |  |   |  |
| CentOS   | G10 |  |   | |
| CentOS    | G11 |  |   |  |
| CentOS   | G12 |  |   |  |

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest relevant k8s available
- Deploy local clusters using relevant k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

---

- [ ] Downstream cluster checks

| OS and version  | Downstream Cluster Type  |  G7 | G8 | G9 | G10 | G11 | G12 |
|---|---|---|---|---|---|---|---|
| CentOS | RKE1 Custom  | :white_check_mark:  | :white_check_mark:  | |
| CentOS| RKE1 Node Driver  |:white_check_mark:  | :white_check_mark: |
| CentOS  | RKE2 Custom  |  :white_check_mark:  | :white_check_mark: |
| CentOS  | RKE2 Node Driver   |  :white_check_mark:  | :white_check_mark: |
| CentOS  | k3s Custom   |  :white_check_mark:  | :white_check_mark: |
| CentOS  | k3s Node Driver  |  :white_check_mark:  | :white_check_mark: |

**Although Public AMI should be used for Node Driver cluster, a Public AMI is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [ ] Rancher local cluster checks

| OS and version  | Downstream Cluster Type    |  G7 | G8 | G9 | G10 | G11 | G12 |
|---|---|---|---|---|---|---|---|
| CentOS |RKE1 Imported   |  :white_check_mark: |:white_check_mark: | | 
|CentOS | RKE2 Imported   |:white_check_mark:  |:white_check_mark: |  |
| CentOS| K3s Imported   |:white_check_mark:   |:white_check_mark:| |

---

Prerequisites
On couple of Community AMIs the OpenSSL is not installed. Which results in failure in provisioning RKE2 and K3S clusters. Hence, private AMI was created with OpenSSL installed and tested node driver cluster provisioning with that Private AMI ami-06815b24f17f7cab7.

**Comment by mitulshah-suse** [comment]
Closing the issue since there is no further testing planned for this.
