### ISSUE TITLE
Investigate UI test failures on -head image version of Rancher

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/qa-tasks#1075]
Investigate 7 failures on v2.8-head:

- namespace-picker.spec.ts
- pages/project-namespace.spec.ts
- pages/charts/istio.spec.ts
- pages/charts/prometheus.spec.ts
- pages/explorer/workloads/pods.spec.ts
- pages/explorer/workloads/workloads.spec.ts
- navigation/side-nav/product-side-nav.spec.ts

**Comment by yonasberhe23** [comment]
* namespace-picker.spec.ts - flaky - a config issue requires a code fix (need to update preference in setup step and then run test)
* pages/project-namespace.spec.ts - flaky - Page not loading in time for cypress to find ‘create namespace’ button
* pages/charts/istio.spec.ts   - flaky - need to wait for istio install request to come back with success response (also failing in Github actions)
* pages/charts/prometheus.spec.ts  - issue related to PSP (pod security)
* pages/explorer/workloads/pods.spec.ts - issue related to PSP (pod security)
* pages/explorer/workloads/workloads.spec.ts - issue related to PSP (pod security)
* navigation/side-nav/product-side-nav.spec.ts  - flaky (fails sometimes)
* user-menu related failures (also failing in Github actions)
  * preferences
  * account and api-keys
  * logout

**Comment by izaac** [comment]
Added separate issue for workloads/pods errors: https://github.com/rancher/qa-tasks/issues/1079

pages/explorer/workloads/pods.spec.ts - issue related to PSP (pod security)
pages/explorer/workloads/workloads.spec.ts - issue related to PSP (pod security)

Medium effort.

**Comment by izaac** [comment]
Added a separate issue for the Prometheus ui tests errors: https://github.com/rancher/qa-tasks/issues/1079

pages/charts/prometheus.spec.ts - issue related to PSP (pod security)

This could require high effort.

**Comment by izaac** [comment]
Added a separate issue to fix the flakiness of the istio chart install. With possible solution.
https://github.com/rancher/qa-tasks/issues/1082
pages/charts/istio.spec.ts

Test in:
https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/charts/istio.spec.ts

Low effort.

**Comment by izaac** [comment]
I created a separate issue for this: https://github.com/rancher/qa-tasks/issues/1083

The errors on the project-namespace tests are sporadic but they could be improved for consistent execution by making sure the projectsNamespaces page is visible.

pages/project-namespace.spec.ts
https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/explorer/project-namespace.spec.ts

Low effort.

**Comment by izaac** [comment]
Most of the references issues here were fixed. I'll add another issue for other areas. This is one of the fixes done.

https://github.com/rancher/dashboard/pull/10529
