### ISSUE TITLE
Automate airgap HA setup

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#11]
* Create an airgapped HA setup

Same format as our existing airgap job, but the cluster nodes should be airgapped and the correct options passed to the Helm install command.

**Comment by slickwarren** [comment]
What we need for this ticket:

* deploy bastion node -- already in AG script
* deploy at least 3 private nodes in same subnet as bastion -- already in AG script
* prepare bastion as private registry -- already in AG script
* install helm, kubectl, and rke onto bastion node --partially in HA script
* pull rancher from helm repo --probably in HA script
* rke up with private registry settings + private IP of each node --partially in HA script
* set kubeconfig to output yaml from rke --probably in HA script
* add certs (certmanager if using rancher certs)  -- already in AG script
* create helm template, should look something like 
```
helm template rancher ./rancher-<version>.tgz --output-dir .     --namespace cattle-system     --set hostname=<Hostname>     --set rancherImage=<Private_Registry>/rancher/rancher     --set ingress.tls.source=<rancher-or-secret>    --set certmanager.version=<cert-manager-version-if-rancher-certs-else-remove>    --set systemDefaultRegistry=<Private_Registry>     --set useBundledSystemChart=true     --set rancherImageTag=<version>
```
* deploy rancher -- partially in AG/HA script
* edit `kubectl edit ingress rancher -n cattle-system` to include both public and private LBs -- TODO
* add secret if not using rancher certs  -- already in AG script

cc @izaac and @brandond , please add/modify these steps as needed. We could also use k3s

**Comment by slickwarren** [comment]
https://github.com/rancher/rancher/pull/34619
