### ISSUE TITLE
Go test framework for v1 APIs

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#110]
Create a Go framework for end-to-end and functional tests of the new v1 (dashboard) APIs

Start with basic RKE2 provisioning cases for admin and standard users for Digital Ocean and Custom clusters.

**Comment by igomez06** [comment]
https://github.com/rancher/rancher/pull/33901

**Comment by igomez06** [comment]
New PR: https://github.com/rancher/rancher/pull/34666
