### ISSUE TITLE
Oracle Linux 9.1 OS Validations 2.7/2.6

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/qa-tasks#1109]
Group 7 = 2.7/1.26/24
Group 8 = 2.7/1.25/24
Group 9 = 2.7/1.26/23
Group 10 = 2.7/1.25/23
Group 11 = 2.6/1.26/24
Group 12 = 2.6/1.25/24

|  OS | Groups |  Private AMI  | Public AMI  | User | 
|---|---|---|---|---|
| Oracle Linux 9.1  | G7 | ami-00aefd01b58d9bc96 | ami-0f1f169fb8ec7ede5  | ec2-user |
| Oracle Linux 9.1  | G8 |  |   | cloud-user |
| Oracle Linux 9.1  | G9 |  |   | cloud-user |
| Oracle Linux 9.1  | G10 |  |   | cloud-user |
| Oracle Linux 9.1  | G11 |  |   | cloud-user |
| Oracle Linux 9.1  | G12 |  |   | cloud-user |

ami : ami-0636302284effe929 

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest relevant k8s available
- Deploy local clusters using relevant k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

- [ ] Downstream cluster checks

| OS and version  | Downstream Cluster Type  | G7 | G8 | G9 | G10 | G11 | G12 |
|---|---|---|---|---|---|---|---|
| Oracle Linux 9.1 | RKE1 Custom  | :white_check_mark: | |
| Oracle Linux 9.1 | RKE1 Node Driver  |:white_check_mark:  | |
| Oracle Linux 9.1 | RKE2 Custom  | :white_check_mark:   | |
| Oracle Linux 9.1 | RKE2 Node Driver  | :white_check_mark:  | |
| Oracle Linux 9.1 | k3s Custom  |:white_check_mark:  | |
| Oracle Linux 9.1 | k3s Node Driver  |  :white_check_mark:  | |

**Although Public AMI should be used for Node Driver cluster, a Public AMI is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [ ] Rancher local cluster checks

| OS and version  | Downstream Cluster Type  |  G7 | G8 | G9 | G10 | G11 | G12 |
|---|---|---|---|---|---|---|---|
| Oracle Linux 9.1 | RKE1 Imported   | :white_check_mark:  | |
|Oracle Linux 9.1 | RKE2 Imported   |:white_check_mark:  | |
| Oracle Linux 9.1 | K3s Imported   | :white_check_mark: | |

---
**Prerequisites**
1. Firewalld disabled
2. nm-cloud-setup.service and nm-cloud-setup.timer stopped and disabled.

**Comment by mitulshah-suse** [comment]
Closing the issue since there is no further testing planned for this
