### ISSUE TITLE
Fix Snapshot Restore Flaky Tests

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#1111]
Snapshot restore, and upgrade strategy static (table) tests fail inconsistently on these points;

- Deployment checks
- After restore checks (version and other cluster change changes)
- Conflict errors due to not having a cleanup in the test teardowns for deployments
- Multiple watch and wait due to timeouts

Additionally, we need to consider redesigning:
- Static tests require configuration input, and as these are static tests, they shouldn't need user inputs
- While running the whole suite, the dynamic input test will also run, we need a logic to skip these if the input isn't given like the current provisioning tests.

We need to consider redesigning, enhancing, and possibly overwriting these tests. Especially the static tests where we run them on release tests - pushed the sign-off date at least a full day.

**Comment by markusewalker** [comment]
I have a local fix for separate task https://github.com/rancher/qa-tasks/issues/989. I'll just add the fixes needed here in that PR that I will open.

**Comment by markusewalker** [comment]
**rancher/rancher**
v2.9 PR: https://github.com/rancher/rancher/pull/44338
v2.8 PR: https://github.com/rancher/rancher/pull/44385
v2.7 PR: https://github.com/rancher/rancher/pull/44386

**rancher/shepherd**
v2.9 PR: https://github.com/rancher/shepherd/pull/59
v2.8 PR: https://github.com/rancher/shepherd/pull/60
v2.7 PR: https://github.com/rancher/shepherd/pull/61
