### ISSUE TITLE
Enhance Documentation about Scaling Tests

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#1112]
While running the release tests, we need the most updated and well-explained test runs to shorten the release sign-off times. A few points to consider:

- For Hosted Cluster scaling; 
  - What kind of setup do we need for these tests? Node pools etc.
  - Do we have to enable auto-scaling for them?
  - If we enable or disable auto-scaling, what kind of configuration is needed depending on the auto-scaling? I talked offline with the hostbusters, AFAIK it's a thing for AKS, does it matter for other hosted clusters?
- For RKE1/RKE2/K3s;
    - 3 ETCD, 2 CP, and 2 Worker Roles have failed while running the static test - especially with custom scaling tests. Do we need updated documentation about their cluster setup examples?
    - Do we need separate pools for different roles or do they have to be in the same pool?
    - Does the given setup example work for custom scaling too? Is there any difference to consider or note?

Additional: Not limited to scaling, we have JSON and YAML examples mixed. And JSON examples usually don't work because of the syntax. So we can't use JSON <-> YAML convert because of that.

**Comment by markusewalker** [comment]
Some of these points are already explained in the README, other points can be made more clear. This is a small change so it will be added into a separate PR with other work.

**Comment by markusewalker** [comment]
**rancher/rancher**
v2.9 PR: https://github.com/rancher/rancher/pull/44338

**rancher/shepherd**
v2.9 PR: https://github.com/rancher/shepherd/pull/59

**Comment by markusewalker** [comment]
Talking offline with the team, we're going to have another README refactoring PR that will address this along with the other provisioning READMEs, rather than piece mealing.

**Comment by markusewalker** [comment]
This should be addressed. Closing.
