### ISSUE TITLE
Post release Checks on a RKE1 cluster provisioning is Failing

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/qa-tasks#1118]
When I run post release checks for v2.8.1 -- I am seeing 3 failures on RKE1 cluster provisioning. The issues are related to RKE1 cluster only, remaining two clusters (RKE2 and K3s) are passing the validations. 

**Failed tests from the Report:**

1. github.com/rancher/rancher/tests/v2/validation/provisioning/rke1.TestCustomClusterRKE1ProvisioningTestSuite/TestProvisioningRKE1CustomCluster/1_Node_all_roles_Standard_User_Node_Provider:_ec2_Kubernetes_version:_v1.27.8-rancher2-1_cni:_calico (from github.com_rancher_rancher_tests_v2_validation_provisioning_rke1)

2. github.com/rancher/rancher/tests/v2/validation/provisioning/rke1.TestCustomClusterRKE1ProvisioningTestSuite/TestProvisioningRKE1CustomCluster (from github.com_rancher_rancher_tests_v2_validation_provisioning_rke1)

3. github.com/rancher/rancher/tests/v2/validation/provisioning/rke1.TestCustomClusterRKE1ProvisioningTestSuite (from github.com_rancher_rancher_tests_v2_validation_provisioning_rke1)

==============
**MORE DETAILS ON THE ERRORS:**

1. github.com/rancher/rancher/tests/v2/validation/provisioning/rke1.TestCustomClusterRKE1ProvisioningTestSuite/TestProvisioningRKE1CustomCluster/1_Node_all_roles_Standard_User_Node_Provider:_ec2_Kubernetes_version:_v1.27.8-rancher2-1_cni:_calico (from github.com_rancher_rancher_tests_v2_validation_provisioning_rke1)

```
Stacktrace
=== RUN   TestCustomClusterRKE1ProvisioningTestSuite/TestProvisioningRKE1CustomCluster/1_Node_all_roles_Standard_User_Node_Provider:_ec2_Kubernetes_version:_v1.27.8-rancher2-1_cni:_calico
time=2024-01-22T18:30:32Z level=info msg=Execute Registration Command for node i-09c25c5b9881f0faf
time=2024-01-22T18:30:32Z level=info msg=Linux pool detected, using bash...
time=2024-01-22T18:30:32Z level=info msg=Command: sudo docker run -d --privileged --restart=unless-stopped --net=host -v /etc/kubernetes:/etc/kubernetes -v /var/run:/var/run  rancher/rancher-agent:v2.8.1 --server https://dasha281.qa.rancher.space --token 54lb79lpsdz5bhq7f5p6ph96xkhpxpk6m95nm2d5fgbh25rgp6rs5z  --controlplane --etcd --worker
time=2024-01-22T18:31:32Z level=info msg=72ee70eeff1597a5788154d9eb9a671cb340dac60213049f2642cbcebe5f70a7

time=2024-01-22T18:35:39Z level=info msg=Cluster status is active!
time=2024-01-22T18:35:39Z level=info msg=serviceAccountTokenSecret in this cluster is: cluster-serviceaccounttoken-rbbtv
time=2024-01-22T18:35:40Z level=info msg=All nodes in the cluster are in an active state!
    permutations.go:172: 
        	Error Trace:	/root/go/src/github.com/rancher/rancher/tests/v2/validation/provisioning/permutations/permutations.go:172
        	            				/root/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
        	Error:      	Should NOT be empty, but was []
        	Test:       	TestCustomClusterRKE1ProvisioningTestSuite/TestProvisioningRKE1CustomCluster/1_Node_all_roles_Standard_User_Node_Provider:_ec2_Kubernetes_version:_v1.27.8-rancher2-1_cni:_calico
time=2024-01-22T18:36:06Z level=error msg=failed to cleanup resource. Backoff error: timed out waiting for the condition. Cleanup error: Bad response statusCode [403]. Status [403 Forbidden]. Body: [message=clusters.management.cattle.io "c-lvs79" is forbidden: User "u-ftp52" cannot get resource "clusters" in API group "management.cattle.io" at the cluster scope: RBAC: [clusterrole.rbac.authorization.k8s.io "c-lvs79-clustermember" not found, clusterrole.rbac.authorization.k8s.io "c-lvs79-clusterowner" not found], baseType=error, code=Forbidden] from [https://dasha281.qa.rancher.space/v3/clusters/c-lvs79]
        --- FAIL: TestCustomClusterRKE1ProvisioningTestSuite/TestProvisioningRKE1CustomCluster/1_Node_all_roles_Standard_User_Node_Provider:_ec2_Kubernetes_version:_v1.27.8-rancher2-1_cni:_calico (471.71s)
```

2. github.com/rancher/rancher/tests/v2/validation/provisioning/rke1.TestCustomClusterRKE1ProvisioningTestSuite/TestProvisioningRKE1CustomCluster (from github.com_rancher_rancher_tests_v2_validation_provisioning_rke1)

Stacktrace
```
=== RUN   TestCustomClusterRKE1ProvisioningTestSuite/TestProvisioningRKE1CustomCluster
    --- FAIL: TestCustomClusterRKE1ProvisioningTestSuite/TestProvisioningRKE1CustomCluster (483.51s)

```

3. github.com/rancher/rancher/tests/v2/validation/provisioning/rke1.TestCustomClusterRKE1ProvisioningTestSuite (from github.com_rancher_rancher_tests_v2_validation_provisioning_rke1)

Stacktrace
```
=== RUN   TestCustomClusterRKE1ProvisioningTestSuite
time="2024-01-22T18:28:06Z" level=info msg="default rke1 kubernetes version is: v1.27.8-rancher2-1"
--- FAIL: TestCustomClusterRKE1ProvisioningTestSuite (486.81s)
```

**Comment by markusewalker** [comment]
This is happening because of a failed check in the function `CheckETCDVersion`. We previously had fixed this back in December, but seems to be still giving issues. I will look into this.

**Comment by markusewalker** [comment]
**rancher/rancher PRs**
2.9 PR: https://github.com/rancher/rancher/pull/44292
2.8 PR: https://github.com/rancher/rancher/pull/44293
2.7 PR: https://github.com/rancher/rancher/pull/44295

**rancher/shepherd PRs**
2.9 PR: https://github.com/rancher/shepherd/pull/52
2.8 PR: https://github.com/rancher/shepherd/pull/53
2.7 PR: https://github.com/rancher/shepherd/pull/54

**Comment by markusewalker** [comment]
Merged.
