### ISSUE TITLE
OS Validation for k8s 1.27 and 2.7

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1139]
1.27 k8s
Rancher version : 2.7.11-head, RKE version : v1.4.15-rc3

OS to test | Docker Version | Custom Cluster | Node Driver | Standalone | Notes
-- | -- | -- | -- | -- | --
Ubuntu 22.04 | 24.0 | **PASS** |**PASS** | **PASS** |  
Oracle Linux 9.2 | 24.0 |**PASS** |**PASS** | **PASS** |
Oracle Linux 9.1 | 24.0 |**PASS** |**PASS** | **PASS** |
Oracle Linux 9.0  | 24.0 | |  | | Fails with issue - https://github.com/rancher/rancher/issues/43678
Oracle Linux 8.8 | 24.0 |**PASS** |**PASS** | **PASS** | 
Oracle Linux 8.7  | 24.0 |**PASS** |**PASS** | **PASS** |
CentOS 7.9 | 24.0 | **PASS** |**PASS** |  **PASS** |
RHEL 9.2 | 24.0 | PASS | PASS |  PASS |  
RHEL 9.1 | 24.0 | PASS | PASS |  PASS |  
RHEL 9.0 | 24.0 | PASS | PASS |  PASS |  
RHEL 8.8 | 24.0 | PASS | PASS |  PASS |  
RHEL 8.7 | 24.0 | PASS | PASS |  PASS |  
RHEL 7.9 | 24.0 | PASS | PASS |  PASS |  
Rocky 9.2 | 24.0 | PASS | PASS |  PASS |  
Rocky 9.1 | 24.0 | PASS | PASS |  PASS |  
Rocky 9.0 | 24.0 | PASS | PASS |  PASS |  
Rocky 8.8 | 24.0 | PASS | PASS |  PASS |  
Rocky 8.7 | 24.0 | PASS | PASS |  PASS |  
SLES:15SP4 | 24.0 | **PASS** | **PASS** | **PASS** |   Comes with docker pre-installed
SLES:15SP5 | 24.0 | **PASS**  | **PASS** | **PASS** |  Comes with docker pre-installed
OpenSUSE:15.4 | 24.0 | **PASS**  | **PASS** | **PASS** |  Comes with docker pre-installed
OpenSUSE:15.5 | 24.0 | **PASS**   | **PASS** | **PASS** |  Comes with docker pre-installed

**Comment by vivek-shilimkar** [comment]
Since, all the validations are done. closing the ticket.
