### ISSUE TITLE
 Implement Slack reporter using go Slack API

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#1148]
Slack has a go API module that we can leverage 
https://github.com/slack-go/slack

- Slack Client
- Slack Reporting functions

**Comment by NickVolynkin** [comment]
JFYI: once you complete the Qase reporting step, there's a ready integration with Slack. So, you might save some time if it does what you want. See https://help.qase.io/en/articles/6417209-slack

**Comment by igomez06** [comment]
> JFYI: once you complete the Qase reporting step, there's a ready integration with Slack. So, you might save some time if it does what you want. See https://help.qase.io/en/articles/6417209-slack

Thank you!. The Qase reporting is already done, and working. I'll take a look thank you!

**Comment by igomez06** [comment]
@NickVolynkin after looking at this, would we be able to report test failures to a specific `@ `in a channel in Slack?

**Comment by igomez06** [comment]
@NickVolynkin how would the Qase reporting look on slack using the ready integration tool?

**Comment by NickVolynkin** [comment]
Oh, wow, I skipped this question. I'll return with some examples.

**Comment by NickVolynkin** [comment]
Here's a simplest example:

<img width="467" alt="Screenshot 2024-04-03 at 18 23 59" src="https://github.com/rancher/qa-tasks/assets/8015154/34969059-e59e-4c95-86ef-639cf416fa62">

**Comment by NickVolynkin** [comment]
@igomez06 

> report test failures to a specific @

Do you want it to mention particular people in the channel, like the PR author?

**Comment by igomez06** [comment]
> @igomez06
> 
> > report test failures to a specific @
> 
> Do you want it to mention particular people in the channel, like the PR author?

yes essentially the slack group who are response for the failure analysis of the specific failures. We would tag our test case with the group/team responsible, if that makes sense.

**Comment by igomez06** [comment]
Request Webhook slack app for Jenkins.
