### ISSUE TITLE
Improve Parser to divide automation tests in Qase by Test Suite Name

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#1150]
Currently all the automation tests are one suite in the Rancher Qase repository. Update parser to separate tests by test suite so it is easier to navigate.

**Comment by NickVolynkin** [comment]
Once you report test results to your Qase repository, it will create test cases for them and assign them IDs. You can take these IDs and use them to annotate your tests, like this: `@qase.id(42)` ([docs](https://github.com/qase-tms/qase-python/tree/master/qase-pytest)). After that, you can organize the cases in the Qase repository as you want, and the tests will be reported seamlessly.

That is, if you annotate tests with IDs, you won't have to reorganize them in the code repo or rewrite your parser. Hope you'll find it useful.

**Comment by igomez06** [comment]
PRs:

- https://github.com/rancher/rancher/pull/44771
- https://github.com/rancher/rancher/pull/44772
- https://github.com/rancher/rancher/pull/44773

**Comment by igomez06** [comment]
Done
