### ISSUE TITLE
Fix Flaky Python Tests Additional CLI

### ISSUE THREAD

**Issue by floatingman** [rancher/qa-tasks#1154]
The following tests fail due to this issue. https://github.com/rancher/rancher/issues/36332#issuecomment-1106948162

tests.v3_api.test_cli.test_cli_app_install
tests.v3_api.test_cli.test_cli_app_upgrade
tests.v3_api.test_cli.test_cli_app_rollback
tests.v3_api.test_cli.test_cli_app_delete
tests.v3_api.test_cli.test_cli_app_install_local_dir

**Comment by markusewalker** [comment]
Closing this issue as this has has been converted to the Go framework.
