### ISSUE TITLE
Add Utility to pull global role bindings using Wrangler

### ISSUE THREAD

**Issue by floatingman** [rancher/qa-tasks#1168]
As part of the overall goal to import Wrangler #725 functions into the Go Automation framework, I need to import the ability to query global role bindings using Wrangler.

Currently, this is accomplished by using the dynamic client.

**Comment by floatingman** [comment]
https://github.com/rancher/qa-tasks/issues/725

**Comment by igomez06** [comment]
Update global roles test to use new wrangler client. Confirm with Anupama during review.

**Comment by floatingman** [comment]
https://github.com/rancher/rancher/pull/45131

**Comment by floatingman** [comment]
https://github.com/rancher/rancher/pull/45886
