### ISSUE TITLE
Update readme for provisioning tests 

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#1170]
Current readme for provisioning tests is split into multiple sections for provisioningInput, nodeTemplateConfigs, customCluster and advanced option. 
Instead if we can have a sample config all of that is required to provision either a custom cluster or node drivers that is required while spinning clusters can help cross teams understand the config better.

For example in https://github.com/rancher/rancher/blob/release/v2.9/tests/v2/validation/provisioning/rke1/README.md#custom-cluster
we have the following dependencies but the config provided below this note does not have nodeDrivers or nodeProviders option:
```
Dependencies:

- Ensure you have nodeDrivers set in provisioningInput
- make sure that all roles are entered at least once in nodePools.nodeRoles
- ensure nodeProviders is set
- use AMIs that already have Docker installed and the service is enabled on boot

```
But we have another note in the Provisioning Input that states nodeProviders is only needed for custom cluster tests; the framework only supports custom clusters through aws/ec2 instances which has the nodeProviders .

**Comment by markusewalker** [comment]
Merged.
