### ISSUE TITLE
Implement Github action that runs go linter for shepherd

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#1192]
Have a GH action that runs a Golang linter for the repo, like the one that exists in rancher/rancher.

**Comment by caliskanugur** [comment]
Potentially an unblocker for a backporting bot/logic too - which we got feedback about from the Shepherd contributors

**Comment by caliskanugur** [comment]
Closing in favor of: https://github.com/rancher/qa-tasks/issues/1230
