### ISSUE TITLE
Discuss Sanity checks needed for Shepherd Repo

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#1231]

**Comment by caliskanugur** [comment]
**Actions Items:**

- Add a way to restrict merges (if possible) without verifying changes workflow passes
- Go format checks, check goimports vs gofmt and if it’s something supported out of the box, for me
- Announcing the rebase after the workflow is merged
- Set another meeting: https://github.com/rancher/qa-tasks/issues/1247

**Comment by caliskanugur** [comment]
1st and 3rd one completed offline.

2nd one:

- Example: https://github.com/rancher/shepherd/actions/runs/8529939334/job/23366756674?pr=76
- Further info: https://pkg.go.dev/golang.org/x/tools/cmd/goimports
