### ISSUE TITLE
Validate vSphere8 for 2.8.3

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1233]
Issue description:
Support matrix does not include support for VMware vSphere 8
 
 
Actual behavior:
Support is listed and provided for VMware vSphere 8
 
Expected behavior:
Customer expects us to support VMware vSphere 8 and for it to be listed on Matrix

**Comment by slickwarren** [comment]
update - everything has been tested - no behavior exclusive to vsphere 8 has been found that is not working on rancher. There are a few open issues found (that affect both 7 and 8) that are being reviewed / addressed by dev team.

**Comment by rishabhmsra** [comment]
Validated SLES-15SP5 on vSphere 8 environment using below steps:
- Created rancher v2.8.3-rc6 server.
- Provisioned RKE1, RKE2 and K3s node driver cluster using sles-15sp5.
- Ran network checks on all clusters. All checks passed successfully.
