### ISSUE TITLE
Automate RKE2 ETCD Snapshot Restore

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#124]

**Comment by sowmyav27** [comment]
Being tracked here

- Snapshot + restore using etcd - https://github.com/rancher/qa-tasks/issues/405
- Snapshot + restore using etcd + k8s version - https://github.com/rancher/qa-tasks/issues/406
- Snapshot + restore using etcd + k8s + cluster config option - https://github.com/rancher/qa-tasks/issues/407
- S3 enabled snapshot + restore - https://github.com/rancher/qa-tasks/issues/408
