### ISSUE TITLE
[Improvement] Enable More Robust Input/Configuration - Golang Automation Framework

### ISSUE THREAD

**Issue by git-ival** [rancher/qa-tasks#128]
Should be able to feed values in via Flags, config files, or environment variables as detailed here: https://dev.to/ilyakaznacheev/a-clean-way-to-pass-configs-in-a-go-application-1g64

prospective tools:
- https://github.com/BurntSushi/toml
	- gopkg.in/yaml.v2
- https://dev.to/ilyakaznacheev/a-clean-way-to-pass-configs-in-a-go-application-1g64
	- https://github.com/ilyakaznacheev/cleanenv
- https://github.com/peterbourgon/ff

**Comment by bmdepesa** [comment]
Completed.
