### ISSUE TITLE
Fix 2.9 python tests -- removal of v1 test_monitoring broke other python tests

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#1281]
https://github.com/rancher/rancher/pull/44229
in this PR there were some removals of tests but importing this file was not fixed in various files. 
i.e. test_istio, test_cluster_templates

This appears to affect other tests as well that don't have any imports i.e. test_deploy_rancher_server.

**Comment by anupama2501** [comment]
Closing as the fix has been merged.
