### ISSUE TITLE
Fix Norman Schema Changes in Shepherd for Rancher 2.9

### ISSUE THREAD

**Issue by floatingman** [rancher/qa-tasks#1282]
The schema for management.cattle.io has changed from 2.8. It is going to be necessary to update the schema and regenerate the Norman clients

Extensive testing is going to be needed to be sure nothing is broken after updating the clients.

**Comment by igomez06** [comment]
This is done I believe, will need to double check the PR that came for 1.29 or 1.30 kubernetes support into shepherd
