### ISSUE TITLE
[UI] Investigate error: Cannot read properties of undefined (reading 'TenantFeatures')

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/qa-tasks#1289]
Investigate error: Cannot read properties of undefined (reading 'TenantFeatures') which causes test failures/flakiness. It occurs in many of our e2e tests that are navigating away from Dashboard (e.g. Support Links > 'Can click on Docs link' test) 

![6cc623fa919743d832306a13d5accd2a.png](https://zube.io/files/rancher/ccb18dd430a85f35d08864a8c7f58c66-6cc623fa919743d832306a13d5accd2a.png)

**Comment by yonasberhe23** [comment]
QA Notes:

repro steps
1. navigate to https://ranchermanager.docs.rancher.com/v2.8
2. open console
3. notice error > otBannerSdk.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'TenantFeatures')
_____
1. navigate to https://ranchermanager.docs.rancher.com/v2.8/getting-started/overview
2. open console
3. notice error > otBannerSdk.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'TenantFeatures')

**Comment by yonasberhe23** [comment]
I'm assuming that this is a docs issue since the console error is being thrown on `ranchermanager.docs` pages. should I create an issue for this in the [rancher-docs repo](https://github.com/rancher/rancher-docs)? @gaktive

**Comment by gaktive** [comment]
@yonasberhe23 if that error is coming from the docs site, then yes, file a docs ticket.

**Comment by yonasberhe23** [comment]
issue reported https://github.com/rancher/rancher-docs/issues/1249

**Comment by yonasberhe23** [comment]
Closing this. will use bug ticket for tracking https://github.com/rancher/rancher-docs/issues/1249
