### ISSUE TITLE
[UI] Update 'Writing Tests' docs

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/qa-tasks#1293]
Update docs to include best practices discussed during the last retro meeting regarding how to utilize POs

Here are a couple of examples of what we shouldn’t do/how to fix it:

1. [Charts > monitoring-istio.spec](https://github.com/rancher/dashboard/blame/e09df1da0e6fdef6c46556b186020bf2c3059484/cypress/e2e/tests/pages/charts/monitoring-istio.spec.ts#L73). In this example we are creating an instance of labeled select class directly in the test but this should be in a PO file instead like this:

create a PrometheusTab class and in there create a storageClass  fn which returns labeled select with a given selector
```
import LabeledSelectPo from '@/cypress/e2e/po/components/labeled-select.po';

storageClass(): LabeledSelectPo {
    return new LabeledSelectPo('[data-testid="select-chart-prometheus-storage-class"]');
  }
```

and then use storageClass() in the spec file
```
import { PrometheusTab } from '@/cypress/e2e/po/pages/explorer/charts/tabs/prometheus-tab.po';

const prometheus = new PrometheusTab();

prometheus.storageClass().toggle();
prometheus.storageClass().clickOptionWithLabel('local-path');
```

 2. [Charts > opa-gatekeeps.spec](https://github.com/rancher/dashboard/blob/e09df1da0e6fdef6c46556b186020bf2c3059484/cypress/e2e/tests/pages/charts/opa-gatekeeper.spec.ts#L63). In this example we are using cy.get() command and passing in the selector, this should also be in a PO file

Current dev docs: https://rancher.github.io/dashboard/testing/e2e-test#writing-tests

**Comment by yonasberhe23** [comment]
pr raised https://github.com/rancher/dashboard/pull/10901

**Comment by izaac** [comment]
qa task https://github.com/rancher/qa-tasks/issues/1293

**Comment by izaac** [comment]
Moving to done. PR is docs and is now merged.
