### ISSUE TITLE
Find a solution for running all of the automated patch validation checks at once

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#1340]
Either "one click" or running in parallel simpler or something. We need a design document for this with the different solutions considered and one selected.

**Comment by aganesh-suse** [comment]
First round of batch test was added successfully.
Pending: to separate out the arm install and upgrade test into separate jenkins jobs, and then add those to be triggered by batch test as well.

**Comment by aganesh-suse** [comment]
Done. We have batch jobs for installs/upgrades separately. including arm as well.
