### ISSUE TITLE
Add hardened cluster provisioning / testing to release testing

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#1354]
prerequisites:
- [x] https://github.com/rancher/qa-tasks/issues/632
- [x] https://github.com/rancher/qa-tasks/issues/1336
- [x] https://github.com/rancher/qa-tasks/issues/1333

TODO: 
- [ ] ensure the tests above have a static test for hardening rke1/rke2/k3s so that this runs during release testing

**Comment by markusewalker** [comment]
Rancher PRs
2.9: https://github.com/rancher/rancher/pull/45578

Shepherd PRs
2.9: https://github.com/rancher/shepherd/pull/198
2.8: https://github.com/rancher/shepherd/pull/203
2.7: https://github.com/rancher/shepherd/pull/204

**Comment by markusewalker** [comment]
Merged.
