### ISSUE TITLE
Look into sanity job failures - K3s + RKE1 azure

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#1373]
jenkins jobs are failing for 1.28.9 azure for k3s (stacked) and rke1 (dedicated)

**Comment by slickwarren** [comment]
for rke1 azure, the ssh_username was different between automation vs. manual. However updating that didn't change the result of automation. 

good news is, manually provisioning azure rke1 is working

also, sshing into the node, the default user doesn't have access to docker in either manual vs. automated use case. but sudo su works, and this behavior doesn't seem to make a difference for the manual use case. so something is up with the automation config.

**Comment by slickwarren** [comment]
this is something to do with the config when used via automation. Manually provisioning with default settings is working fine.

**Comment by markusewalker** [comment]
Our weekly sanity runs is showing Azure working across cluster types. Closing issue.
