### ISSUE TITLE
[scale-framework] Add ability to run rke1 clusters

### ISSUE THREAD

**Issue by dramich** [rancher/qa-tasks#138]
Current framework only scales clusters through imported k3s clusters, this needs to be expanded to be able to create/provision rke1 clusters from scratch.

**Comment by git-ival** [comment]
Added modules for RKE1:
* [control-plane](https://github.com/rancher/rancher2-scaling/pull/41)
* [downstreams](https://github.com/rancher/rancher2-scaling/pull/40)
