### ISSUE TITLE
[UI] VAI - Pagination test cases

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/qa-tasks#1380]
- [x] Cluster Events Table | Validate the pagination is hidden | Navigate to cluster events table | Pagination hidden
- [x] Cluster Events Table | Validate the table includes pagination at the bottom

- [x] Custom resource definition | Pagination hidden
- [x] Custom resource definition | Pagination visible

- [x] Pods | Pagination hidden
- [x] Pods | Pagination visible

- [x] ~~Fleet bundles | Pagination hidden~~ Fleet workspaces | Pagination hidden
- [x] ~~Fleet bundles | Pagination visible~~ Fleet workspaces | Pagination visible

- [x] User API Keys | Pagination hidden 
- [x] User API Keys | Pagination visible

- [x] Users | Pagination hidden 
- [x] Users | Pagination visible

- [x] Role Templates | Pagination hidden
- [x] Role Templates | Pagination visible

Test steps for happy path scenarios (example table has 122 rows of data): 
1. Add deterministic data to validate pagination
2. Navigate to the table 
3. Check: Pagination is visible `<< < 1 - 100 of {122} {type} > >>` 
4. Check: Navigate back elements are disabled
5. Check: navigate to next page `<< < 101 - 122 of {122} {type} > >>` 
6. Check: Navigate forward elements are disabled
7. Check data is sorted correctly (Add one deterministic data for the last page)
8. Check search filter works correctly
9. Select all on the page and check the resource count at top of table

**Comment by richard-cox** [comment]
Just checking in, these tests validate page controls for the existing pagination process. Are there any plans to cover other pagination features like sorting and filtering, and then all the same again with the vai backed pagination on?

**Comment by yonasberhe23** [comment]
That is the plan for 2.10, we are currently only concerned with Vai OFF and making sure there aren't regressions in 2.9 and then will account for Vai ON after the 2.9 release.
I am doing a basic check for sorting here but we were missing filtering so I've added that to the list. thanks for calling that out.
