### ISSUE TITLE
Various CLI checks are failing

### ISSUE THREAD

**Issue by davidnuzik** [rancher/qa-tasks#141]
Various CLI checks fail (test_cli.py) 

![image](https://user-images.githubusercontent.com/45179589/136277332-59d7384e-493a-48ce-b1d6-2c8191cee32e.png)

To reproduce, run the cli checks on a v2.5.10 cluster - I tested with v2.5.10-rc2; these tests will always fail.
Looking at the code it looks like we need to make some small changes to fix this.

**Comment by sowmyav27** [comment]
closing - https://github.com/rancher/rancher/issues/36332#issuecomment-1106948162
