### ISSUE TITLE
[Spike] v2prov and Fleet Relation

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#1418]
- Figure out the v2Prov and Fleet's relationship by including both parties
- Create a test case agreed upon

This is the spike portion, later automation needs to be followed.

**Comment by slickwarren** [comment]
fleet test plan areas:
fleet via rancher -- tested via k3d for fresh install cases in fleet-e2e repo
is k3d enough to validate v2Prov -> hostbusters devs say yes


other areas of investigation:
fleet in airgap  - tested indirectly during rancher testing (for local cluster only, no actual fleet tests are done but we see fleet working properly with downstream clusters)
fleet on windows ? 
~fleet + harvester? Longhorn?
Neuvector
stackstate~ -- these will likely be revisited as we approach different/new teams in the future, not necessary to do right now
upgrade checks (upgrade of rancher, downstream clusters, etc.)

rancher HA
terraform? 


-- update 2 -- 
created confluence doc to start tracking / help deciding where tests should live

**Comment by slickwarren** [comment]
areas for PIT team to contribute for v2prov, all of the following would need both fleet-agent and gitRepo tests:
* airgap -- fleet-agent only (see excluded areas for more details)
* v2Prov upgrades (should k8s upgrade, fleet version upgrade test is covered in their repo)
* fresh installs -- possibly straightforward to add a check on fleet-agent for downstream clusters. This is implicitly checked in fleet-e2e repo by checking that local cluster in fleet-local ns is in `active` state on continuous delivery page
* windows -- can add explicit check for this re: fresh installs for downstream clusters. Can add gitRepo test for it when adding for k8s upgrades
* etcdSnapshots (downstream cluster rollbacks) would look similar logic added to support windows
* proxy - would be worth adding to proxy test suite for both local cluster + downstream cluster use cases 

more advanced but less common areas would include (we can consider these to be `P2` use cases):
* ACE
* PNI


unknown support areas:
* running on hardened clusters / SElinux -- could run this as part of v2Prov checks but, if it doesn't work out-of-box we would need to work with the fleet team to figure out what type of repos can work with hardened clusters (just for gitRepo case, fleet-agent works on hardened clusters)
* Terraform (pretty sure rancher doesn't have fleet included in provider2 but also couldn't find  a dedicated tf fleet-provider)
* varying types of signed certs (should work with any valid cert on the local cluster i.e. self signed, letsencrypt, etc. )
* certificate rotation (best guess; fleet is not affected by this in a way that wouldn't affect all resources on the cluster)

excluded areas:
* cluster type -- this isn't worth adding IMO - fleet isn't dependent on any resources for the cluster, and would be redundant to write test for rke1/rke2/k3s/etc.   Fleet team tests using k3d, which is sufficient
* airgap -- likely only checking that downstream/local cluster fleet-agent is operating as expected. ~Adding a private helm repo in AG setup is not straightforward~ 
  * with some testing done with the UI team, this may actually be more possible than I thought
* rancher CLI
* checking that credentials are secure -- this seems outside of PIT team responsibilities, but we can check this if need be. It would be a manual test afaik
* checking that the chart itself is correctly formatted / published (outside PIT team scope)

**Comment by slickwarren** [comment]
created issues in https://github.com/rancher/qa-tasks/issues/1514
closing this spike
