### ISSUE TITLE
Better error handling of v3 API test framework

### ISSUE THREAD

**Issue by izaac** [rancher/qa-tasks#142]
Some parameters in our automated jobs either silently fail without properly doing its task.
Or other parameters fail without helpful information of the root cause.

**Comment by davidnuzik** [comment]
Some jobs will succeed but have actually failed as well. For example, consider https://jenkins.int.rancher.io/job/rancher_qa/view/rancher_ha/job/rancher-v3_ha_upgrade/36/
In the console output we can see the helm upgrade command returned a non-zero exit code.
