### ISSUE TITLE
Convert test_network_policy to go

### ISSUE THREAD

**Issue by floatingman** [rancher/qa-tasks#1427]
The following test in Rancher needs to be converted from Python to Go

https://github.com/rancher/rancher/blob/818c5d381f350b8033a65648d5a33637f24c9ed8/tests/validation/tests/v3_api/test_network_policy.py

**Comment by floatingman** [comment]
Main - https://github.com/rancher/rancher/pull/46740
Backports
- v2.9 https://github.com/rancher/rancher/pull/47577
- v2.8 https://github.com/rancher/rancher/pull/47578
- v2.7 https://github.com/rancher/rancher/pull/47579

**Comment by rancher-max** [comment]
This was completed, so closing this issue.
