### ISSUE TITLE
[Spike] Harvester usage

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#1436]
Investigate how we can start using Harvester for cluster provisioning to assist with cross-team testing

**Comment by slickwarren** [comment]
https://github.com/rancher/qa-tasks/issues/468

https://github.com/harvester/tests/blob/main/harvester_e2e_tests/integrations/test_9_rancher_integration.py

https://harvester.github.io/tests/manual/harvester-rancher/

**Comment by slickwarren** [comment]
spent some time Friday looking more at documentation, installing harvester on baremetal

will spend more time today looking at harvester's api

**Comment by slickwarren** [comment]
based on the meeting, here are the points for new work:

* release testing
  * across rancher versions, before rancher releases


* implementing new test cases
* terraform crossover with rancher/harvester-providers
* airgap


action items:
* getting access / to jenkins -- Harvester team to start on this effort
* qase test plan needs some modification -- khushboo to work on this and get back to PIT 
* harvester in Go - CW working on client for this

**Comment by slickwarren** [comment]
currently:
* waiting for RAFT team design approval for harvester client
* waiting for tests for us to help / add from Harvester team
* waiting for harvester team / EIO on machines to use in Lab ENV

**Comment by slickwarren** [comment]
https://github.com/rancher/qa-tasks/issues/1618
