### ISSUE TITLE
[Spike] Exploratory research around what Harvester is capable of

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#1459]
Areas mentioned:

- Networking
  - DNS
  - Load balancing
  - Registry
- Terraform modules 
- All the things we DON'T know

**Comment by git-ival** [comment]
Will need to workaround limitations with the harvester terraform provider not having a way to pull the harvester kubeconfig before the apply phase: https://github.com/harvester/harvester/issues/1797

Will need to silo bullseye traffic, VMS, etc. into a bullseye-specific namespace. https://docs.harvesterhci.io/v1.4/networking/harvester-network

Will need to configure a separate DHCP server or jumpbox/tunnel solution to enable secure access to the VMs.

It seems that there should be a registry already configured for the Harvester env, based on internal docs.
