### ISSUE TITLE
[Spike] Research Update Test Containers to Have Latest Dependencies

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#1470]

**Comment by igomez06** [comment]
- Create a GHA workflow that will build the docker image
- Triggered either on code changes or on PR merges
  - We have a similar work flow 
  -  There is way to trigger the GHA when a specific file is changed: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
