### ISSUE TITLE
Run Flaky test on Local  : TestSteveDownstream 

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/qa-tasks#1485]
Run this test on both v2.9.1-rc? and v2.8.6-rc? before our public release.

This test is failing on GHA.
https://github.com/rancher/rancher/issues/42674

Currently this test is skipped and make sure the test is working as expected.

**Comment by igomez06** [comment]
This bug needs to be addressed for the test to pass:
https://github.com/rancher/rancher/issues/46391

**Comment by dasarinaidu** [comment]
Ran these tests on v2.8 and v2.9; all the tests are green and closing this card.
