### ISSUE TITLE
[Spike] Investigate how to label tests with team owner for failure reporting

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#1491]
Investigate how to label tests with team owner for failure reporting in Slack. 

Tests should be annotated somehow - in code or in Qase and these should be mapped to Slack groups for notifications.

re: #1151

**Comment by caliskanugur** [comment]
Known parts:

- Qase [reporter](https://github.com/rancher/rancher/blob/main/tests/v2/validation/pipeline/qase/reporter/main.go#L284-L289) object has a comment section where right now it only includes the stacktrace. We can turn this section into map wrapped by string to have stacktrace & owner sections.
- Slack reporter has a struct where we can add additional field for the owners, currently setup happens after the Qase reporter  reads the [test2json results](https://github.com/rancher/rancher/blob/main/tests/v2/validation/pipeline/qase/reporter/main.go#L93-L96), and parses it to create Qase test case map -- which is also used for Slack reporter

**First Option** - Embedding it somewhere in the tests (suite struct, global variable calling etc.) to read the logs later after the call happens:

Basically `logrus.Print(owner.team2)` and read/parse this log from:

`{"Time":"2024-09-11T10:12:57.705748-04:00","Action":"output","Package":"golang/pkg/testsum","Test":"TestIntMinBasic","Output":"time=\"2024-09-11T10:12:57-04:00\" level=info msg=\"Hello Team2\"\n"}`


Potential questions:

- How does it make sure the test suites/cases are including this new owner section in the comments? What kind of regexp or parsing is needed, as it'd be more reading regexp. 

**Second Option** - Custom runner to wrap gotestsum:

Flow could look like this:

 - Wrap `gotestsum` with a small custom runner CLI app, maybe somewhat similar to [gotestdox](https://github.com/bitfield/gotestdox/blob/main/gotestdox.go#L77-L98)
   - After the test run is completed, read the file's new line for owner (or field)
   - Before the test run command starts, read the file's new line for owner (or field), attach it to the output - probably custom with embedded go test output struct addition

Potential questions:

- How does it know go tests' two different option - local dir mode vs package list vs specific file

**Comment by bmdepesa** [comment]
Option 3 - 

See: https://gist.github.com/bmdepesa/4ecf0691fb5097bbf2493ed5ffbd0e87#file-gistfile1-txt-L53

- In the Qase test results parsing: 
  - Before parsing - 
    - map the comments to the test names for all tests in our path
  - During parsing to update Qase 
    - find the matching Slack team owner name for the current test/suite
  - During the test update 
    - update the `SlackTeamOwner` field on the existing or newly added test
  - During Slack reporting
    - Grab the team name from the Qase `SlackTeamOwner` field and include on that the output for each failing test if exists

We will need to do some simple regex filtering on the comment and tests.. for this case we only want to map comments on functions that start with `Test`; and we only want comments that begin with `@slack-team`
