### ISSUE TITLE
Define process for documenting ECM automation by team

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#1494]
Define a process for documenting the automation tools / artifacts / processes for each team in ECM to facilitate cross-team usage. 

Where should this information live? 
How can we make the best use of it? 
How do we expect to interact with different teams?

**Comment by igomez06** [comment]
https://docs.google.com/document/d/1BrmP8n3t3d6JCS0YKWVHYPGlObhbWiK8OpP8NVQ9bMs/
