### ISSUE TITLE
Rancher RHEL / OL / Rocky 8.10 OS Support 2.8.7

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#1511]
**On 2.8-head Rancher**

OS | Private AMI | Public AMI | User
-- | -- | -- | --
RHEL 8.10 | 
OL 8.10 |   |
Rocky 8.10 |   |

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest 1.30 available
- Deploy local clusters using 1.30 k8s version
- - Deploy local clusters using 1.29 k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```
 

- [ ] Downstream cluster checks 

OS and version | Downstream Cluster Type | Status | Assignee
-- | -- | -- | --
RHEL 8.10 | RKE1 Custom |PASS| Rishabh
RHEL 8.10| RKE1 Node Driver |PASS |Rishabh
RHEL 8.10 | RKE2 Custom |PASS |Rishabh
RHEL 8.10 | RKE2 Node Driver | PASS | Rishabh
RHEL 8.10 | k3s Custom |PASS|Rishabh
RHEL 8.10 | k3s Node Driver | PASS | Rishabh
OL 8.10 | RKE1 Custom | PASS |Rishabh
OL 8.10| RKE1 Node Driver |PASS|Rishabh
OL 8.10 | RKE2 Custom |PASS |Rishabh
OL 8.10 | RKE2 Node Driver | PASS | Rishabh
OL 8.10 | k3s Custom |PASS |Rishabh
OL 8.10 | k3s Node Driver | PASS | Rishabh
Rocky 8.10 | RKE1 Custom | PASS |Rishabh
Rocky 8.10| RKE1 Node Driver |PASS |Rishabh
Rocky 8.10 | RKE2 Custom | PASS |Rishabh
Rocky 8.10 | RKE2 Node Driver | PASS | Rishabh
Rocky 8.10 | k3s Custom | PASS |Rishabh
Rocky 8.10 | k3s Node Driver | PASS | Rishabh

- [ ] Rancher local cluster checks

- [ ] Chart validation -

**Comment by rishabhmsra** [comment]
Completed the checks on rancher v2.8.7, hence closing this issue.
