### ISSUE TITLE
Auth: Add p0 validations for Github

### ISSUE THREAD

**Issue by izaac** [rancher/qa-tasks#1536]
Add P0 tests, login, logout, and access restriction.

**Comment by yonasberhe23** [comment]
code is in place (needs clean up) but putting this on hold until [Jenkins failures investigation](https://github.com/rancher/qa-tasks/issues/1551) is done for Vue3 test effort

**Comment by yonasberhe23** [comment]
This is un-automatable:

1. Github requires the Rancher user to authenticate via GitHub login page when going through the authentication flow and it seems that GitHub blocks cookies when a bot/automation is detected which blocks user from logging in (even with valid credentials) and therefore blocks the auth process. I've tried to work around this by enabling GitHub auth provider in Rancher by using purely Rancher API requests but was still prompted to login to Github.
2. GitHub deprecated their API for OAuth apps for security reasons https://docs.github.com/en/enterprise-server@3.15/rest/oauth-authorizations/oauth-authorizations?apiVersion=2022-11-28. Bc of this, we are only able to automate the OAuth app creation flow via GitHub’s web app and going this route will cause us to write flaky tests; if GitHub decides to change their web elements for login and OAuth creation flow then we would need to update the selectors we use in our tests. Cypress recommends not automating third party sites for this reason. https://docs.cypress.io/app/core-concepts/best-practices#Potential-Challenges-Authenticating-with-Social-Platforms
3. We can’t use a pre-configured/existing OAuth app bc the homepage/callback url would not match the Rancher base url bc it dynamically changes per test run except for in the case of using `local` setup where the rancher base url stays the same.
