### ISSUE TITLE
Fix cis automation for OS that does not create the group as the username while creating the user account

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/qa-tasks#157]
CIS scans on hardened cluster fails while using SLES as SLES does not create the group when the user is created. -U flag needs to be passed ensure group is created.
```
useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U
```
Expected:
```
# stat -c %U:%G /var/lib/rancher/rke2/server/db/etcd
etcd:etcd
```
Actual:
CIS scan fail as the etcd dir does not belong to etcd group
```
# stat -c %U:%G /var/lib/rancher/rke2/server/db/etcd
etcd:users
```

**Comment by rancher-max** [comment]
Resolved by https://github.com/rancher/rancher/pull/35934
