### ISSUE TITLE
Add Missing Proxy Test Build Flags

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#1603]
https://github.com/rancher/rancher/blob/main/tests/v2/validation/provisioning/proxy/k3s_proxy_custom_cluster_test.go#L1, currently proxy tests are missing labels, we need to add them so they don't run by default

**Comment by markusewalker** [comment]
Main: https://github.com/rancher/rancher/pull/47808
2.9: https://github.com/rancher/rancher/pull/47811
2.8: https://github.com/rancher/rancher/pull/47812

**Comment by markusewalker** [comment]
Merged.
