### ISSUE TITLE
Add base64 kubeconfig to cluster creation jobs

### ISSUE THREAD

**Issue by davidnuzik** [rancher/qa-tasks#161]
For example, https://jenkins.int.rancher.io/job/rancher_qa/view/rke2/job/rancher_v3_create_rke2_cluster/ job does not spit out base64 encoded kubeconfig so we have to manually fix it when copy and paste from console output. However, the HA Deploy job does do this.

Can we copy this logic over to cluster creation jobs such as the rke2 one?

**Comment by rancher-max** [comment]
https://github.com/rancher/rancher/pull/36556
