### ISSUE TITLE
Automate Restricted admin p0/p1 usecases

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#164]
User is Restricted Admin
- [x] User should NOT be able to list the local cluster
- [x] User should be able to list clusters that the user is not owner of or has created.
- [x] User should be able to deploy a new downstream cluster
- [x] User should be able to list Global settings
- [x] User should NOT be able to EDIT global settings

**Comment by samjustus** [comment]
sure-4720

**Comment by anupama2501** [comment]
Closing the ticket as the PR has been merged.
