### ISSUE TITLE
Automate Basic RKE2 provisioning tests for all cluster providers

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#165]
- [x] AWS
- [x] DO
- [x] azure
- [x] Harvester
- [x] Linode

<Details of test cases to be included in the ticket>

**Comment by slickwarren** [comment]
AWS and DO were done by Izrael, and I finished harvester [in this PR.](https://github.com/rancher/rancher/pull/36100) 
TODO: azure, linode

**Comment by slickwarren** [comment]
azure and linode were added by Izrael
