### ISSUE TITLE
Automate Subset of UI Regression cases using Cypress framework

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#166]
<Details of the test cases to be listed in this ticket>

**Comment by davidnuzik** [comment]
Noting here for the record: We agreed (quite recently after issue creation) to see if we can find someone or a group to take this up instead. I had initially showed interest in learning Cypress and building out automation -- I have shifted my focus and prefer to focus on golang.

However, I am happy to still take some part in assisting - for example, I still intend to deliver a UI Test plan which can be used to build out automation.
