### ISSUE TITLE
Automate pre/post upgrade tests with Go framework

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#167]
Automate deploying and validating these resources with the Go framework for pre/post upgrade checks. 
- [ ] Workloads
- [ ] Ingress
- [ ] Services
- [ ] Namespace

This is for doing test_upgrade but using the new v1 API calls to deploy resources

**Comment by bmdepesa** [comment]
https://github.com/rancher/rancher/pull/38461
