### ISSUE TITLE
[RBAC] Project Member P0 tests

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#168]
### Project member - @anupama2501 
- [ ] Project member can list the downstream cluster
- [ ] Project member should NOT be able to assign members to the cluster
- [ ] Project member should be able to list Projects the user is member of
- [ ] Project member should be able to list namespaces in this project and is able to create namespaces
- [ ] Project member should NOT be able to assign users as project members to the project
- [ ] Project member should NOT be able to create new Projects in the cluster

---
For reference: v3_api tests are [here](https://github.com/rancher/rancher/blob/release/v2.6/tests/validation/tests/v3_api/test_rbac.py)

**Comment by samjustus** [comment]
Target equivalent bullet in each section to start

**Comment by anupama2501** [comment]
Closing the ticket as the PRs have been merged and validated.
