### ISSUE TITLE
Change logic of schedulable nodes for k3s and rke2 cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#176]
Currently master node is included in list of nodes as master is also schedulable for k3s and rke2 cluster
But when it is a cluster deployed from Rancher, this is not applicable. It will be equivalent to an RKE1 cluster in that case. 
This logic is applicable only for imported cluster

**Comment by slickwarren** [comment]
I found that this is also an issue for other rke2 cluster types. I've addressed this in a PR. basically, now we only check if there are noSchedule or noExecute taints on the node(s) https://github.com/rancher/rancher/pull/36452
