### ISSUE TITLE
Include release tests for Airgap/proxy

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#177]
Include release tests for Airgap/proxy
- Private - git repo, registry, helm repo, logging endpoints
- Proxy for - git repo, registry, helm repo, logging endpoints

Explore automation for these scenarios.

**Comment by bmdepesa** [comment]
Closed in favor of https://github.com/rancher/qa-tasks/issues/478 and https://github.com/rancher/qa-tasks/issues/51
