### ISSUE TITLE
Complete rke2 local cluster provisioning in rancher2-scaling

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#186]
- [x] Utilize [rancherfed rke2 terraform module](https://github.com/rancherfederal/rke2-aws-tf) for now
- [x] Add FQDN setup via Route53
- [x] Add additional node dedicated to running rancher-monitoring (use taints)

**Comment by git-ival** [comment]
PR needs review: https://github.com/rancher/rancher2-scaling/pull/42
