### ISSUE TITLE
2.6.5 General Scaling Runs - Medium

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#197]
Local Config:
* K8s: 
  * Distribution - K3s, RKE2, and RKE1
  * Version - v1.22.4
* Rancher:
    * Chart Version - 2.6.5-rc2
    * Image Version - v2.6.5-rc2
    * Desired loglevel - info
    * CATTLE_PROMETHEUS_METRICS - false

Downstream Config:
* K8s:
    * Distribution - K3s
    * Version - v1.22.8+k3s1

Test Scenario:
  1. Setup Rancher control-plane cluster using rancher2-scaling repo
  2. Scale to the currently [documented cluster limit
](https://rancher.com/docs/rancher/v2.6/en/installation/requirements/#hardware-requirements) using the rancher2-scaling k3s 'clusters' module
    i. Scale in batches of 50 clusters
   ii. Output Rancher pod logs and record current Rancher resource usage here

**Comment by git-ival** [comment]
Completed 3 Medium scaling runs, 1 against each k8s distribution (RKE1, K3s, and RKE2). Results have been logged internally.
