### ISSUE TITLE
Identify flaky tests

### ISSUE THREAD

**Issue by izaac** [rancher/qa-tasks#217]
Review current on-tag / additional test runs to find tests with known failures.

Identify these in confluence
Create issues to track the fixes for these tests

**Comment by izaac** [comment]
Related to: https://github.com/rancher/qa-tasks/issues/219

**Comment by sowmyav27** [comment]
@vivek-shilimkar is there anything else pending from the initial activity of fixing these flaky tests

**Comment by vivek-shilimkar** [comment]
Ticket mentioned here is completed. All the tests here are fixed. https://github.com/rancher/qa-tasks/issues/217#issuecomment-1034256293

Details of the on-tag job were shared on the confluence.
