### ISSUE TITLE
Review existing failing tests from v3_needs Jenkins

### ISSUE THREAD

**Issue by izaac** [rancher/qa-tasks#219]
Nodeport test cases
cluster ip
hostport test cases
test_bkp

**Comment by vivek-shilimkar** [comment]
PR for the fix of service_discovery related error is up.

https://github.com/rancher/rancher/pull/35973

**Comment by vivek-shilimkar** [comment]
test_bkp related errors are fixed with above PR.

**Comment by rishabhmsra** [comment]
Nodeport and clusterIp related tests are fixed : https://github.com/rancher/rancher/pull/35732
