### ISSUE TITLE
v2.6.4 Release Task - QA Sign off for KDM and RKE

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#222]
Start on Thursday before Release - 03/24
Due by - Same day - 03/24

---

**Provide sign off for KDM**

- [x] Verify everything in KDM checklist/Test Plan has been completed
- [x] Provide sign off in _team-rancher-release-bits_ channel. Tag Release Captain

**Provide Sign off for RKE release**

- [x] RKE checks in KDM should be completed
- [x] No issues on Zube for RKE for the release should be open
- [x] If 1 and 2, QA should provide sign off to the Release Captain in _team-rancher-release-bits_ channel

**Comment by Auston-Ivison-Suse** [comment]
Closing comment as all checks have been complete.
