### ISSUE TITLE
v2.6.4 Release Task - QA Sign off Rancher Final RC 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#224]
Start and Due Date - Friday prior to release - 03/25/2022

---
### Release Captain Tasks

- [ ] Provide sign off for Rancher Final RC if 
```
- All issues in all repos should be validated and closed - Rancher/Dashboard/Rancher security/Rancher Embargo
- https://github.com/rancher/qa-tasks/issues/223 is closed
- https://github.com/rancher/qa-tasks/issues/222 is closed
- RKE version is released
```
- [ ] Validate Final Rancher RC has been Tagged
```
- Drone build for Rancher final RC should pass
- verify by doing a docker pull rancher/rancher:<version>
- Post in _team-rancher-qa_ that the final RC has been tagged
```
- [ ] Confirm rancher-images.txt is ready for release
```
Verify the images in rancher-images.txt file are unRCed in final Rancher RC's file
```
- [ ] Validating Automation test suite on Final Rancher RC
- [ ] Verify Harvester Tag has been released

**Comment by MKlimuszka** [comment]
@sowmyav27, due to the (always expected) issues with drone, can this ticket be started a day earlier? or on the other hand, if things get delayed, how vital is it to be done by that Friday as opposed to by Monday.
