### ISSUE TITLE
Validate v1/v2 charts on RKE2 downstream cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#233]
### As part of RKE2 GA - Validate v1/v2 charts on RKE2 downstream cluster (linux only)

---

### v1 charts

- [x] GDNS

---

### v2 charts

- [x] Logging
- [x] Monitoring
- [x] Alerting drivers
- [x] CIS - Permissive Scan on a default non-hardened cluster
- [x] vSphere charts
- [x] Backup Restore on RKE2 local cluster and downstream RKE2 clusters
- [x] Longhorn
- [x] Istio

---

Note: We can validate this as part of 1.23 RKE2 downstream testing.

Details about the setup
- Rancher server version - 2.6.4-rc (latest) or 2.6-head latest
- Downstream cluster k8s version - 1.23RKE2 latest available in Rancher
- 3 etcd, 2 cp and 3 worker nodes

**Comment by ronhorton** [comment]
~~currently blocked by https://github.com/rancher/rancher/issues/36826~~

solution was to included 2.6.4-rc6 as the chart version as well as the image version in the jenkins job. unblocked.
