### ISSUE TITLE
Validate 8.4 RHEL on 2.6.x

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#239]
Due date: 02/18/2022

---
Pre Requisites:
- Rancher on 2.6.3
- Default k8s version -  1.21
- AMI - RHEL 8.4 AMI

----

### Team 2
**Downstream cluster – Tim/Auston (RKE1)**

- [x] Deploy downstream Custom clusters Using private RHEL 8.4 AMI with SELinux Enabled (OS and docker level) RPM enabled – Auston
- [ ] Deploy Node driver clusters using public RHEL 8.4 AMI – Tim 
   * Failed issue rancher/rancher#36526
- [x] Deploy Node driver using private RHEL 8.4 AMI with SELinux Enabled (OS and docker level) RPM enabled – Tim
- [x] Run v3_needs cluster on the downstream clusters

---

**Local HA cluster  – Tim**

- [x] Deploy local RKE1 cluster Using private RHEL 8.4 AMI with SELinux Enabled (OS and docker level) RPM enabled
- [x] Deploy downstream cluster
- [x] Run v3_needs cluster on the downstream clusters

---

### Team 3
**v1/v2 charts (RKE1)**

- [x] Deploy local RKE1 cluster Using private RHEL 8.4 AMI with SELinux Enabled (OS and docker level) RPM enabled
- [x] Deploy downstream Custom clusters Using private RHEL 8.4 AMI with SELinux Enabled (OS and docker level) RPM enabled
- [x] Deploy v1/v2 charts. Validate P0 usecase

**Comment by slickwarren** [comment]
istio issue -> https://github.com/rancher/rancher/issues/36668
