### ISSUE TITLE
Epic - Cleanup of resources after automation runs 

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#25]
All tests should clean up after themselves within a Rancher server
All cloud infrastructure resources should clean up

**Comment by davidnuzik** [comment]
+1 but seems like works today? What doesn't seem to work is that if tests fail then cleanup may not run? E.g. https://jenkins.int.rancher.io/view/all/job/rancher_qa/view/rancher_ha/job/rancher-v3_ha_deploy/1422/console I expected with the test(s) to fail for it to still clean up and delete the ec2 instances, tg, lb for me.

**Comment by bmdepesa** [comment]
Handled in framework
