### ISSUE TITLE
v2.6.4 Release checks - Performance of Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#250]
Start after Feature complete date: 02/18/2022
Due by: 03/02/2022

---

### To validate
- Rancher meets minimum performance requirements for the new milestone version
```
- Scales to published counts on a Medium (large?) setup
- SLOs are met
- Cluster provisioning of RKE1/RKE2 at fresh install and at scale occurs within the maximum time range
```

**Comment by git-ival** [comment]
Did a K3s scaling run (local K3s + downstreams K3s) using 2.6.4-rc8. Installed latest rancher-monitoring (100.1.1+up19.0.3) with `CATTLE_PROMETHEUS_METRICS` env var enabled. The added metrics and resource usage associated with them may have effected the overall results.

Downstream Clusters reached: 265
Downstream Clusters expected: 300
Performing another run today with RKE1 downstreams and `CATTLE_PROMETHEUS_METRICS` env var disabled.

**Comment by floatingman** [comment]
Ran a RKE1 scale test with a local RKE1 cluster and downstream K3s clusters using 2.6.4-rc8. Installed latest rancher-monitoring (100.1.1+up19.0.3) with `CATTLE_PROMETHEUS_METRICS` env var not set, but it still was installed for some reason.

Downstream Clusters expected:300
Downstream Clusters reached: 231

**Comment by git-ival** [comment]
Completed scale testing RKE1 and K3s release checks using 2.6.4-rc8. Investigating issue with installing latest dev-v2.6 rancher-monitoring version on RKE2 HA.

**Comment by git-ival** [comment]
RKE2 scale testing covered by the results from the metrics/monitoring comparison. Specific comment here: https://github.com/rancher/rancher/issues/35737#issuecomment-1075699932
