### ISSUE TITLE
RKE2 Local Cluster Provisioning - Enable installing common components via server manifests

### ISSUE THREAD

**Issue by git-ival** [rancher/qa-tasks#251]
Helm charts can be placed in a server manifests directory in order to automatically deploy them, we should enable this installation method for the following components:
- [] certmanager
- [] rancher
- [] rancher-monitoring

This will remove the requirement for an s3 bucket which is currently used for storing the RKE2 server token and cluster kubeconfig yaml files.

**Comment by bmdepesa** [comment]
Completed (k3s/rke2 support only)
