### ISSUE TITLE
Provisioning RKE2 clusters and other actions on the clusters using TF

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#255]
Install rancher server v2.6-head (latest)
Note down 
- RKE2 k8s version used to deploy clusters
- TF version
- Rancher commit id

---

Using terraform scripts:

- [x] ✅ Deploy an RKE2 cluster
- [x] Scale up a worker node pool in cluster
- [x] Delete node pool and verify nodes are deleted on the backend
- [x] Add worker node pools
- [x] Delete cluster and verify nodes are deleted in the backend.

**Comment by Josh-Diamond** [comment]
- RKE2 k8s version used to deploy clusters: `v1.22.7+rke2r2`
- TF version: `v1.1.8`
- Rancher commit id: `v2.6-eb0351756f22d26c6c10f7f0c35f9e62e2283d2b-head`

Results - 5/5 ✅
