### ISSUE TITLE
Validate 8.4 RHEL on 2.6.x #239- [Team 2]

### ISSUE THREAD

**Issue by Sahota1225** [rancher/qa-tasks#263]
Team 2

Downstream cluster – Tim/Auston (RKE1)

  Deploy downstream Custom clusters Using private RHEL 8.4 AMI with SELinux Enabled (OS and docker level) RPM enabled – Auston
  Deploy Node driver clusters using public RHEL 8.4 AMI – Tim
Failed issue https://github.com/rancher/rancher/issues/36526
  Deploy Node driver using private RHEL 8.4 AMI with SELinux Enabled (OS and docker level) RPM enabled – Tim
  Run v3_needs cluster on the downstream clusters

**Comment by timhaneunsoo** [comment]
https://github.com/rancher/rancher/issues/36526 has been moved to 2.6.5 so the issue will be addressed in future release. Closing this task for 2.6.4
