### ISSUE TITLE
Validate rke2 scenarios

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#264]
Following test cases to be validated on an RKE2 cluster
@rishabhmsra @vivek-infracloud please pick the following usecases
- [x] Edit config and add additional worker node pools
- [x] Edit config and remove worker node pools
- [x] Edit config and increase worker node count
- [x] Edit config and decrease worker nodepool count
- [x] Increase the worker node pool count by clicking on `+`
- [x] Delete node driver cluster
- [x] Delete custom cluster

@anupama2501 Please pick the following usecases
- [x] Backup and restore with migration P1 test scenario
- [x] Backup and restore without migration P1 test scenario
- [ ] Backup restore with rollback - Failed https://github.com/rancher/rancher/issues/37553
- [x] Backup and restore - rollback with migration 
- [x] Drain before delete

**Comment by anupama2501** [comment]
Verified backup/restore checks for RKE2 clusters. More details in internal confluence doc. `Backup restore with rollback` will be verified in the linked issue above.

**Comment by rishabhmsra** [comment]
Validated all the RKE2 checks on rancher `v2.6.5-rc6` by provisioning a `v1.22.9+rke2r1` node driver cluster(1-cp, 1-etcd, 1-worker). All checks passed successfully.
