### ISSUE TITLE
absa patch release tasks

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#265]
2.5.12 absa  - Anu
- [x] Validation tests on the patch version 2.5.12-patch1-head
- [x] Rollback on same cluster from 2.5.122 >> 2.5.12-debug1 >> 2.5.12-patch1-head >> 2.5.12 by changing the rancher-deployment and adding an additional env variable `CATTLE_AGENT_IMAGE` set to `rancher/rancher-agent:v2.5.12`

**Comment by anupama2501** [comment]
Verified on 2.5.12 >> 2.5.12-debug1 >> 2.5.12-patch1-head

1. Created a rancher HA with 2 clusters created as a standard user
2. Ran the pre upgrade checks on the 2 clusters
3. From local cluster, edit the rancher deployment and add the env variables `CATTLE_PROMETHEUS_METRICS`=`true` and `CATTLE_AGENT_IMAGE`=`rancher/rancher-agent:v2.5.12`
4. Install monitoring in the local cluster 
5. Created a service monitor by following this doc https://github.com/rancher/rancher/wiki/How-to-setup-prometheus-dashboard-for-controllers with a bearer token created as secret in the cattle-system with key=token and value=bearer token
7. Login to the grafana UI from apps & market place >> monitoring >> grafana
8. Verify the graphs displayed
9. Upgrade rancher to 2.5.12-debug1 - run post upgrade checks
11. Edit the service monitor as mentioned in the doc linked in step5
12. Verify the graphs from grafana dashboard
13. Upgrade to 2.5.12-patch1-head - run post upgrade checks 
14. Roll back to 2.5.12 - run pre upgrade checks
15. Edit the service monitor and verified the graphs from grafana dashboard.
Pre upgrade graph:
<img width="500" alt="2512grafana" src="https://user-images.githubusercontent.com/38144301/157379596-ab01a28b-7d18-4af6-8311-2284c4c2f5ce.png">



Post upgrade graph:
<img width="500" alt="postupgarde" src="https://user-images.githubusercontent.com/38144301/157379431-1de7baac-a23d-49eb-86b6-a81de868e5ff.png">

**Comment by snasovich** [comment]
Reopened by mistake somehow.
