### ISSUE TITLE
Feature charts validation on 1.23 k8s cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#268]
Validate the following charts on a 1.23 k8s cluster on `2.6.4-rc7` HA cluster, using RKE1 `v1.3.8-rc6` version for the local HA cluster. (k8s version of local cluster also 1.23 k8s. HA so that we can test backup restore chart)

### v1 charts

| Chart | Assignee | Status | Comments|
| --- | --- | --- | --- |
GDNS | Anu | FAIL|existing issue: https://github.com/rancher/rancher/issues/35909 |
Longhorn | Khushboo |PASS | | 

### v2 charts
| Chart | Assignee | version | Status | Comments|
| --- | --- | --- | --- |  --- |
Istio | Anu | 100.0.2+up1.10.4 | Done | --- |
Monitoring   | Ron  | 100.1.1+up19.0.3 | PASS |
Alerting Drivers  | Ron | 100.0.2 | PASS |
CIS  | Anu | 2.0.2 | Done | rke-profile-permissive 1.6 scans |
Backup Restore | Anu | 2.1.1+up2.1.1-rc4 | PASS | |
Longhorn | Khushboo | 100.1.2+up1.2.3 | PASS | |
Logging| Ron | 100.1.0+up3.17.1 |  Done | PASS | |
EKS  | Caleb | eks-operator:v1.1.3-rc3 | PASS | |
Fleet | Izaac | v0.3.9-rc5 | DONE | PASS |

**Comment by ronhorton** [comment]
'PASS'
charts verified on 1.23 k8s cluster
