### ISSUE TITLE
[Maintenance, python] update rancherv3_additional_tests_long snapshot & restore and cert rotation tests (currently failing in automation but passing manually)

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#269]
all of the tests for snapshot & restore are failing, as well as cert rotation tests in this suite. We should look into why they fail in automation, as they are passing when manually validating these cases.

**Comment by sowmyav27** [comment]
these tests have been fixed, except for test_bkp_restore_s3_recover_validate, because [this is an issue](https://github.com/rancher/rancher/issues/38505)
