### ISSUE TITLE
Update OnTag Jenkins jobs 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#275]
Update OnTag Jenkins jobs to reflect latest - k3s/rke/EKS versions

- [x] k3s - `v1.23.6+k3s1` in `rancher-v3_ontag_import_k3s_certification` Jenkins job
- [x] RKE version - `v1.3.11` in `rancher-v3_ontag_import_certification` and `rancher-v3_ha_deploy` Jenkins jobs
- [x] EKS k8s version - `1.22` in `rancher-v3_ontag_eks_certification` and `rancher-v3_ha_deploy` Jenkins jobs
- [x] Rancher Chart version `v2.6.5` in `rancher-v3_ha_deploy` Jenkins job
- [x] RANCHER_AKS_K8S_VERSION - `1.22.6` in `rancher-v3_ha_deploy` Jenkins job
- [x] RANCHER_GKE_K8S_VERSION - `v1.22.8-gke.200`  in `rancher-v3_ha_deploy` Jenkins job
- [x] Latest Windows 2019 AMI in `rancher-v3_create_windows_cluster` and `rancher-v3_ontag_windows_certification`

Add descriptions for:
- [x] k3s - `v1.23.6+k3s1` -->  in `rancher-v3_ha_deploy` Jenkins job
- [x] RKE2 - `v1.23.6+rke2r2` -->  in `rancher-v3_ha_deploy` Jenkins job
- [x] RKE_VERSION --> Have only rke_versions for 2.5.13, 2.6.4 and 2.6.5 called out

**Comment by markusewalker** [comment]
PR: https://github.com/rancherlabs/jenkins-job-builder/pull/146

**Comment by markusewalker** [comment]
Installed.
