### ISSUE TITLE
QA Cloud custodian

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#28]
Cleanup cloud resources after they have been around for longer than 48 hours

This should work across all major providers: Azure, DO, Linode, Google, etc..

Target Groups
Load Balancers
Databases
EKS stacks
Route53 records
Keypairs 

We should check for tags to see if the instance(s)/resources needs to be kept

**Comment by slickwarren** [comment]
I've written a proposal for this in our internal documentation, and have preliminary code for:
* general naming convention, following either (or both) a 48 hour deletion (when following the naming convention) or immediate (when no match to the convention is found) deletion policy
* aws:
  * keypairs
  * Load Balancers
  * Databases

**Comment by slickwarren** [comment]
related / blocking issue: https://github.com/rancher/qa-tasks/issues/687
