### ISSUE TITLE
Create authentication environment - Ping + Active Directory

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#280]
Create an authentication environment for Ping + AD testing. 

Seems there may have been some issues creating this previously - https://github.com/rancher/rancher/issues/31519#issuecomment-817041462

**Comment by sowmyav27** [comment]
@anupama2501 Can you confirm if we have AD setup deployed?

**Comment by anupama2501** [comment]
@sowmyav27/ @bmdepesa Ping SAML does not support configuring an LDAP datastore only Shibboleth currently has the option to have the ldap datastore configuration that can be enabled. The original description is not applicable for ping auth providers.

@sowmyav27 We do have AD setup and ping setup deployed separately.
