### ISSUE TITLE
Validate Open SUSE Leap 15.3

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#292]
### Rancher local RKE1 and Downstream RKE1 clusters validation -- Josh
- [x] Deploy HA Rancher with local cluster's node using Open SUSE Leap 15.3 AMI 
- [x] Deploy 2 downstream clusters using this AMI and run validation tests (3 etcd, 2 cp and 3 worker nodes) 
- - [x] Node driver cluster 
- - [x]  Custom cluster

---

### Feature charts validation
- [x]  v1 charts
- - [x] GDNS
- - [x] Monitoring v1
- - [x] Logging v1
- - [x] Longhorn
- [x]  v2 charts
- - [x] Monitoring v2
- - [x] Alerting Drivers
- - [x] Logging v2
- - [x] CIS
- - [x] Istio
- - [x] Fleet
- - [x] EKS v2 cluster
- - [x] Longhorn

**Comment by Josh-Diamond** [comment]
Rancher local RKE1 and Downstream RKE1 clusters validation - PASSED 
using `AWS Node driver w/ RKE1` + `Custom RKE1` downstream clusters and with `openSUSE AMI` for local cluster
