### ISSUE TITLE
v2.6.5 Release Task - Team 3 - QA Release Sign Off on System charts and Feature Charts

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#295]
Due date - 05/06/2022

---

### Provide Sign off on System charts and Feature Charts

- [x] All issues related to feature charts should be closed
- [x] "New charts for the release" GH issue should be validated and closed
- [x] there will be one Epic issue like [this](https://github.com/rancher/rancher/issues/35100) tracking all new versions for all charts. QA have to verify the right versions are available in Rancher.
- [x] Validate versions of charts QA validated (In release testing confluence page) is the same as that listed in the “New Charts” issue
- [x] Validate versions of charts QA validated (In release testing confluence page) is the same as that listed in the latest images.txt file. (Or if chart versions are listed under Airgap checks in Release testing page. How to find latest rancher.txt file - https://github.com/rancher/rancher/releases/tag/v2.6.5-rcX, latest RC → Assets section → Download [rancher-images.txt](https://github.com/rancher/rancher/releases/download/v2.6.4-rc13/rancher-images.txt) file)

**Comment by izaac** [comment]
Charts epic for v2.6.5 - https://github.com/rancher/rancher/issues/37376

**Comment by izaac** [comment]
All items completed. After final validations of Rancher `v2.6.5-rc12`
