### ISSUE TITLE
v2.6.5 Release - Performance of Rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#297]
Start date: 04/15/2022
Due by: 04/29/2022

---

### To validate
- Rancher meets minimum performance requirements for the new milestone version
```
- Scales to published counts on a Medium (large?) setup
- SLOs are met
- Cluster provisioning of RKE1/RKE2/K3s at fresh install and at scale occurs within the maximum time range
```

**Comment by git-ival** [comment]
Completed General 2.6.5 scaling runs as well as cluster provisioning timing runs, results logged internally. New SLOs have not been explicitly defined, once those have been well-defined we will add those to the Performance testing effort.
