### ISSUE TITLE
v2.6.5 Support Matrix checks - Validate installing Rancher, Downstream clusters listed in the support matrix 2.6.4

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#312]
Start date - Post Bug complete date - 04/20/2022
Due by - 05/06/2022

---

On latest 2.6-head or latest 2.6.5 -rc
---
### Deploy Rancher on these(Hosted clusters) clusters (Using HA jenkins) --> These hosted should be the latest available in for AKS/EKS/GKE
- Deploy a downstream cluster with the following cluster types (Can be downstream node driver RKE1 cluster with default k8s version)
- Run v3_need cluster on the downstream cluster

Local Cluster Type | Cluster k8s version | Downstream cluster Type | Downstream cluster version | Status | Assignee
-- | -- | -- | --| -- | --
AKS | v1.23.5 | RKE2 | v1.23.6+rke2r2 | PASS | Anu
GKE | v1.22.8-gke.200 | GKEv2 | v1.22.8-gke.200 | Done | Ugur
EKS | v1.21.9-eks-14c7a48 | EKSv2 | v1.21.9-eks-14c7a48| Done | Sowmya

**Comment by anupama2501** [comment]
- Deployed rancher AKS hosted on k8s version `v1.23.5` and `v1.22.6`
- Downstream clusters RKE2 `v1.23.6+rke2r2` and RKE1 `v1.23.6` respectively
- Verified v3_needs_cluster checks look good.
