### ISSUE TITLE
v2.6.5 - Release testing - Run Automation suite against 2.6.5-rc

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#313]
Start date - Post Bug complete date - 04/20/2022
Due by - 04/27/2022
---
Run Automation suite against 2.6.5-rc (3 weeks before release)

Jenkins | Assignee | Status
-- | -- | --
rancher-v3_additional_tests | Anupama |  Done
rancher-v3_additional_tests_cli | Caleb | Done
rancher-v3_additional_tests_long | Anupama | Done
rancher-v3_auth_enabled_rancher | Anupama | Done
rancher-v3_cluster_auth_grb_istio_monitoring | Anupama | Done

**Comment by sowmyav27** [comment]
rancher-v3_additional_tests_cli - Done. Checks passed manually,

**Comment by anupama2501** [comment]
Verified 

rancher-v3_additional_tests_long - checks passed manually
rancher-v3_auth_enabled_rancher - checks passed manually
