### ISSUE TITLE
v2.6.5 Release - Team 2 - Validate cluster provisioning use cases using Terraform

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#314]
- Start By: 04/20/2022
- Due by - 04/26/2022

---
Validate cluster provisioning usecases using Terraform

### node driver provisioning 

**RKE1** 

- [x] Cluster provisioning
- [x] Adding node pools
- [x] Deleting node pools
- [x] deleting the cluster

**RKE2** 

- [x] Cluster provisioning
- [x] Adding node pools
- [x] Deleting node pools

### Other usecases
- [x] Delete RKE1 and RKE2 cluster
- [x] Deploy a hosted cluster - AKS (since this is the newest)

**Comment by Josh-Diamond** [comment]
Validated on Rancher `v2.6-eb0351756f22d26c6c10f7f0c35f9e62e2283d2b-head`, using Terraform `v1.1.8`
RKE1 - with k8s versions [`v1.23.6-rancher1-1`, `v1.22.9-rancher1-1`, `v1.21.12-rancher1-1`]
RKE2 - with k8s versions [`v1.22.7+rke2r2`, `v1.23.6+rke2r1`, `v1.22.9+rke2r1`, `v1.21.12+rke2r1`]
k3s - with k8s versions [`v1.23.6+k3s1`, `v1.22.9+k3s1`, `v1.21.12+k3s1`]
AKS - with k8s version [`v1.22.6`]
