### ISSUE TITLE
[scale-framework] Split control-plane module's top-level outputs into module-specific files

### ISSUE THREAD

**Issue by git-ival** [rancher/qa-tasks#315]
Should split the control-plane's `outputs.tf` file into multiple `<module>-outputs.tf` files to ease code maintenance and review.
Minimum suggested split: 
* k3s-outputs.tf
* rke1-outputs.tf
* rke2-outputs.tf
* common-outputs.tf

**Comment by floatingman** [comment]
Closed with pull requests merged.
https://github.com/rancher/rancher2-scaling/pull/54
