### ISSUE TITLE
v2.6.4 Release - Support matrix - Add hosted k8s versions 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#317]
### Hosted Kubernetes Downstream Clusters
These versions must be filled in the Support matrix document in the internal confluence document under Section `Hosted Kubernetes Downstream Clusters (AKS/EKS/GKE)` and `Imported Kubernetes Downstream Clusters`

versions listed [here](https://github.com/rancher/qa-tasks/issues/232)

---

### Hosted Kubernetes Cluster to install Rancher Manager 

These versions must be filled in the Support matrix document in the internal confluence document under Section `Hosted Kubernetes Cluster (AKS/EKS/GKE) to install Rancher Manager on`

versions listed [here](https://github.com/rancher/rancher/issues/36277)

**Comment by brudnak** [comment]
Support matrix updated with values found in the above issues.
