### ISSUE TITLE
Update AWS_AMI for rancher_airgap tests in Jenkins

### ISSUE THREAD

**Issue by thehejik** [rancher/qa-tasks#332]
Would be possible to update **default** `AWS_AMI` and its **description** for `rancher_airgap` tests in [Jenkins](https://jenkins.int.rancher.io/job/rancher_qa/view/rancher_airgap/ ) to use newer docker-20.10?

By this PR https://github.com/rancher/rancher/pull/37232 we'd like to introduce new argument `--platform` for `save-rancher-images.sh` script which will be able download container images for different platform than the platform where the script is executed.

It simply pass the `--platform` arg and its value to docker like `docker pull --platform=linux/s390x rancher/rancher:v2.6.4` problem is that `--platform` is marked as `experimental feature` in current AWS_AMI `ami-066f14e43aebc7472` and doesn't work with preinstalled docker 19.x by default.

I've tried `ami-09dc705c0e3efbdc3	ubuntu-20.04-docker-20.10.7	125601231307/ubuntu-20.04-docker-20.10.7` and the new feature is working ok with that AMI.

![rancher_airgap-aws_ami](https://user-images.githubusercontent.com/12828077/163121816-60cf8102-8b44-4d6b-bd4c-455a81f8837c.png)

**Comment by sowmyav27** [comment]
Will be done as part of this issue https://github.com/rancher/qa-tasks/issues/564
