### ISSUE TITLE
Precommit hooks in git for linting validation tests 

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#34]

**Comment by izaac** [comment]
Probably use this Python framework https://pre-commit.com

- Create the pre-commit configuration at the rancher/rancher repo root directory level
- Create configurations for Python libraries black and flake8 at the rancher/rancher repo root directory level
- Update requirements_v3.txt to include these for pip install.
- Document in the Onboarding QA how to use it.
- Request the pre-commit output pasted as part of the Automation PR descriptions (just an idea)
