### ISSUE TITLE
Validate different OS for RKE2 clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#347]
**Node Driver clusters**
- Deploy node driver RKE2 clusters using nodes from AWS - 3 etcd, 2 control plane and 3 worker nodes using nodes launched with the AMIs (Public AMIs. Note down the AMI in the ticket when executing)
- When the cluster is up and Active, verify System Project page the workloads are active
- Run the v3_needs_cluster jenkins and verify all the tests pass. 
- Run these tests in Jenkins v3_needs_cluster job :  -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
- [ ] Latest RHEL 8.5 SElinux enabled (Private AMI since RPM will be enabled) --> _Will not work, known issue_
- [x] Ubuntu 20.04
- [ ] Latest OL 8.4 
- [x] Latest SLES 15SP3 
- [x] Rocky Linux 8.4 -

**Comment by vivek-shilimkar** [comment]
Blocked by this issue.

https://github.com/rancher/rancher/issues/37460

**Comment by markusewalker** [comment]
**AMIs**
SLES 15SP3 - `ami-0f7cb53c916a75006` (Community AMI)
OL 8.5 -  `ami-00ea24d1cdc779a79`
OL 8.4 - `ami-057ea002166d4b314`

- SLES 15SP3 was successful in setting up RKE2 cluster, importing into Rancher and running the automated Jenkins job was successful. There were 3 failures, but all are expected failures.
- When attempting to setup RKE2 cluster with automated Jenkins jobs, both OL AMIs fail consistently as it is unable to join the worker node. When looking at manually setting up instead, I was able to properly spin up a single node cluster and import into Rancher successfully.
     - Needs further investigating to see if the Jenkins job is successful like SLES 15SP3.

**Comment by vivek-shilimkar** [comment]
RKE2 v1.23.6+rke2r1 cluster creation with 2cp, 3etcd, 3worker nodes was successful on following OSes.

Ubuntu - ami-0fb653ca2d3203ac1
sles-15sp3 - ami-0f7cb53c916a75006
RockyLinux 8.4 - ami-0382eea882ee397b8

However, ingress checks failed on all of the above OSes.

Cluster creation failed on Oracle Linux 8.4 - ami-0eb9c7bb30e82c851
Log shows following error.

Error applying plan -- check rancher-system-agent.service logs on node for more information

**Comment by sowmyav27** [comment]
SLE Micro - https://github.com/rancher/rancher/issues/37539
OL Linux 8.4/8.3 - https://github.com/rancher/rancher/issues/37537

**Comment by sowmyav27** [comment]
Ingress checks will be validated separately. Closing this issue.
