### ISSUE TITLE
Validate RKE2 clusters with long cluster name

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#348]
- [x] Deploy RKE2 node driver 1 node cluster with max number of characters in cluster name
- [x] Deploy RKE2 custom driver 1 node  cluster with max number of characters in cluster name

**Comment by Josh-Diamond** [comment]
Blocked - [37535](https://github.com/rancher/rancher/issues/37535)

**Comment by Josh-Diamond** [comment]
Cluster name's max character limit for both RKE2 Node driver clusters and RKE2 Custom clusters is `63`.  Closing issue; inconsistency mentioned above will be pushed back and addressed in milestone 2.6.6
