### ISSUE TITLE
Validate RKE2 clusters on different network providers

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#349]
- Create RKE2 clusters on each of the following network providers (3 etcd, 2 cp and 3 worker nodes)
- Verify clusters come up Active
- Verify all workloads in system Project page, come up Active
- Run Network checks v3_needs_cluster jenkins job on the downstream clusters and verify all tests pass
- [ ] multus, Cilium
- [ ] multus, Calico

**Comment by rishabhmsra** [comment]
Blocked on https://github.com/rancher/rancher/issues/37460

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6.5-rc6. 

- Provisioned `v1.22.9+rke2r1` RKE2 clusters and it came up active on both network providers.
- Ran the network checks, but all the ingress checks are failing. An issue is logged for it : https://github.com/rancher/rancher/issues/37561

**Comment by sowmyav27** [comment]
Since hostport and ingress have separate issues logged. Closing this one
