### ISSUE TITLE
Validate `External cloud provider` on RKE2 harvester downstream cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#350]
- Create a downstream cluster with 3 worker, 1 etcd, 1 cp Harvester node driver cluster RKE2
- In the cloud provider config → select `external` (Add information if any other config is provided during cluster provisioning)
- Verify the nodes come up active 
- Create a volume with the respective cloud provider option - Storage clas or PV
- Associate to a workload storage options
- Write data by executing into the workload deployment pod

**Comment by slickwarren** [comment]
blocked on https://github.com/harvester/harvester/issues/2213

**Comment by slickwarren** [comment]
all tests have passed on v2.6.5-rc6 with harvester v1.0.2-rc1
* v1.22.9
  * single node cluster
  * dedicated node-per-role cluster
* v1.23.6
  * single node cluster
  * dedicated node-per-role cluster
