### ISSUE TITLE
Implement external validation in framework to ensure hosted clusters are cleaned up

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#353]
There is a delayed effect when deleting hosted clusters on rancher, in terms of the clusters being cleaned up in their respective external provider ie) azure(aks), amazon (eks). The automation framework does not account for this.

**Comment by bmdepesa** [comment]
Can we link any relevant PRs?

**Comment by sowmyav27** [comment]
Hosted clusters is being taken care by another team. Closing this issue.
