### ISSUE TITLE
Validate node rehydration for RKE2 local and downstream clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#357]
Validate node rehydration for RKE2 local and downstream clusters

**Comment by slickwarren** [comment]
downstream issues - https://github.com/rancher/rancher/issues/38926#issuecomment-1292763825

local testing - tbd

**Comment by slickwarren** [comment]
spent some time figuring out the best option to automate local cluster rehydration. Max has some [related TF + GO automation here](https://github.com/rancher/rke2/tree/master/tests/terraform), but long term we may want to go with something all in one, like corral.

**Comment by slickwarren** [comment]
this is simpler than initially thought:
*  a new VM is registered with a cluster 
* existing node is removed
