### ISSUE TITLE
[scale-framework] Support provisioning Cluster v1 RKE2 clusters

### ISSUE THREAD

**Issue by git-ival** [rancher/qa-tasks#358]
[Cluster v1
](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster)
[Cluster v2](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster_v2)

Both cluster versions must be supported within the same module.
Support multi-`node_pool` with single and multi-roles.
Uses locals to perform logic for the `count` on the relevant resources.

**Comment by bmdepesa** [comment]
RKE2 v1 provisioning is not a valid usecase
