### ISSUE TITLE
connect to a VPN with jenkins (for use with harvester, vsphere)

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#374]
we have many gapped environments that our internal team uses for harvester and vsphere testing. 
We should configure tests to use a VPN configuration .

**Comment by bmdepesa** [comment]
After discussion we think the best approach is to install the vpn client into the automation docker container
* https://github.com/rancher/rancher/blob/release/v2.6/tests/v2/validation/Dockerfile.validation
* https://github.com/rancher/rancher/blob/release/v2.6/tests/validation/Dockerfile.v3api

We would need a script at some point to write the vpn configuration files and then connect to the Fremont DC. This would be the step that needs the most investigation. 

From this point, we can run the automation pointing to the Fremont DC with no impact on user experience except for configuring the tests appropriately.

**Comment by bmdepesa** [comment]
https://github.com/rancher/rancher/pull/37953 has been merged

@slickwarren can you update this card if nothing else remains?
