### ISSUE TITLE
Automate Cluster Owner and Member RBAC v1 API calls

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#380]
### Cluster owner

- [x]  Standard user cannot list downstream cluster
- [x] Cluster owner can list the downstream cluster
<s> - Cluster owner should be able to assign members to the cluster </s> --> v3 endpoint
- [x] Cluster owner should be able to list projects the user does not own
- [x] Cluster owner should be able to list namespaces the user does not own
- [x] Cluster owner should be able to create namespaces in Projects the user does not own
- [x] Cluster owner should be able to create Projects in the cluster

---

### Cluster Member

- [x] Cluster member owner can list the downstream cluster --> v1 call
- [x] Cluster member should NOT be able to assign members to the cluster --> v3 call
- [x] Cluster member should NOT be able to list projects the user does not own --> v1 call
- [x] Cluster member should NOT be able to list namespaces the user does not own --> v1 call
- [x] Cluster member should NOT be able to create namespaces in Projects the user does not own --> v1 call
- [x] Cluster member should be able to create Projects in the cluster --> v1 call

**Comment by sowmyav27** [comment]
PR: https://github.com/rancher/rancher/pull/39630

**Comment by anupama2501** [comment]
Closing as the required PRs are merged
