### ISSUE TITLE
Create new private AMI for Windows 2019

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#383]
On latest 2019 Windows AMI
- Install docker
- Install SSH

**Comment by markusewalker** [comment]
Created new Windows Server 2019 private AMI with docker and ssh built-in. Verified I could RDP and SSH into an AMI based off of this template that I created.

Additionally, I went ahead and modified the AMI to specifications needed for internal use. As part of issue https://github.com/rancher/qa-tasks/issues/275, I will update the latest AMI with this new one that I created.
