### ISSUE TITLE
v2.5.14 Release - Final RC checks - QA signs off Rancher Release - Post Release checks 

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#385]
Due Date: 23rd May 2022 
---

These checks that the QA Release Captain must do before providing sign off to tag Rancher Final RC

 
- [ ] Provide sign off for Rancher Final RC
- [ ] All issues in all repos should be validated and closed - Rancher/Dashboard/Rancher security/Rancher Embargo

**`To request a final RC`**
- [ ] Verify the images in rancher-images.txt file are unRCed in final Rancher RC's file
- [ ] Download the rancher-images.txt file
- [ ] verify all images except these images
- [ ] rancher/rancher-agent:v2.5.14-rc
- [ ] rancher/rancher-runtime:v2.5.14-rc
- [ ] rancher/rancher:v2.5.14-rc
- [ ] If above steps are completed - QA must provide a sign off to Release Captain to tag a Rancher final RC in team-rancher-release-bits channel

**` Final RC Checks `**
- [ ] Validate Final Rancher RC has been Tagged
- [ ] Drone build for Rancher final RC should pass in [here](https://drone-pr.rancher.io/rancher/rancher)
- [ ] verify by doing a docker pull rancher/rancher:<version>
- [ ] Announce in QA channel that the final RC has been tagged
- [ ] onTag Automation on Rancher Final RC must be complete
- [ ] Final versions must be validated on Final Rancher RC

**` Sign off on Rancher release`**
- [ ] Provide Sign off if the above tasks have been completed for rancher release

**`Post Release checks`**
- [ ] Deploy 1 downstream RKE1 node driver cluster on the released version of rancher using default k8s version - 1 etcd + 1 control plane + 1 worker node

**Comment by sowmyav27** [comment]
Was done
