### ISSUE TITLE
Automate Terraform Release Testing usecases

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#386]
Automate Terraform Release Testing usecases

---

### Node driver provisioning
**RKE1**

- [x]  Cluster provisioning
- [x]  Adding node pools
- [x]  Deleting node pools
- [x]  deleting the cluster

---
**RKE2**

- [x]  Cluster provisioning
- [x]  Adding node pools
- [x]  Deleting node pools

---
**Other usecases**

- [x]  Delete RKE1 and RKE2 cluster
- [x]  Deploy a hosted cluster - AKS (since this is the newest)

**Comment by Josh-Diamond** [comment]
progress on this may be viewed [here](https://github.com/Josh-Diamond/rancher-terratest)

**Comment by Josh-Diamond** [comment]
Ticket #386 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6-64e1bd4c572d9d2b197f8732c8cb5bfa90e51e42-head`:
1. AKS
    - Using TF + Terratest, provision a downstream AKS cluster, [k8s `v1.22.6`] 
    - Once provisioned test actual cluster specs against expected cluster specs; 
    - Add 3 node pools, each with 1 node and test actual cluster specs against expected cluster specs; 
    - Delete the 3 node pools added and "restore" cluster back to originally provisioned specs.
    - Verified: [AKS Test](https://github.com/Josh-Diamond/rancher-terratest/blob/main/tests/aks/aks_test.go) - PASS
2. RKE1
    - Using TF + Terratest, provision a downstream AWS RKE1 Node driver cluster, [k8s `v1.23.6`] 
    - Once provisioned test actual cluster specs against expected cluster specs; 
    - Add 3 node pools, each with 1 "all-roles" node and test actual cluster specs against expected cluster specs; 
    - Delete the 3 node pools added and "restore" cluster back to originally provisioned specs.
    - Verified: [RKE1 Test](https://github.com/Josh-Diamond/rancher-terratest/blob/main/tests/rke1/rke1_test.go) - PASS
3. RKE2
    - Using TF + Terratest, provision a downstream AWS RKE2 Node driver cluster, [k8s `v1.23.6+rke2r1`] 
    - Once provisioned test actual cluster specs against expected cluster specs; 
    - Add 3 node pools, each with 1 etcd node and test actual cluster specs against expected cluster specs; 
    - Delete the 3 node pools added and "restore" cluster back to originally provisioned specs.
    - Verified: [RKE2 Test](https://github.com/Josh-Diamond/rancher-terratest/blob/main/tests/rke2/rke2_test.go) - PASS

Screenshots:

`AKS Results`
<img width="584" alt="aks-pass" src="https://user-images.githubusercontent.com/46494969/170516892-afd847e5-5ae8-4f24-8d47-e0e83e2b9087.png">

`RKE1 Results`
<img width="587" alt="rke1-pass" src="https://user-images.githubusercontent.com/46494969/170516941-6d02df00-da41-401b-afd0-fe0803fa3b08.png">

`RKE2 Results`
<img width="593" alt="Screen Shot 2022-05-26 at 7 52 41 AM" src="https://user-images.githubusercontent.com/46494969/170516982-82d26a74-70e9-466c-8472-79e533069bcc.png">

**Comment by sowmyav27** [comment]
Reopening since review is pending

**Comment by Josh-Diamond** [comment]
https://github.com/rancher/rancher/pull/37931

**Comment by Josh-Diamond** [comment]
Update:
Terratests will be refactored to remove external API call functions and replace them with clients before PR will be merged

**Comment by Josh-Diamond** [comment]
Latest PR:

https://github.com/rancher/rancher/pull/41479

**Comment by Josh-Diamond** [comment]
Moving to `qa-review`.  Awaiting review/approval from devs w.r.t. versioning concerns w/ go.mod and go.sum files

**Comment by Josh-Diamond** [comment]
upon review, by devs, of versioning concerns w.r.t. `go.mod` + `go.sum` files, it was decided to give terratest directory its own go.mod + go.sum files, within the rancher repo.  

Moving ticket to `QA Next Up`, to take up changes and accommodate this request.

**Comment by Josh-Diamond** [comment]
UPDATE - June 28, 2023
---

Latest design meeting discussion concluded that terratest framework is to be separated into its own repo, outside of rancher, and the test files will also be broken out to be stored in the associated terraform providers repo (i.e. `rancher2`, `rke`, etc).

Linked below are (temporary) repositories, to be moved into an official SUSE/Rancher repo:
https://github.com/Josh-Diamond/rancher-terratest-framework
https://github.com/Josh-Diamond/rancher-terratest-tests

Next Steps:
- move framework code into official SUSE/Rancher repository
- move tests to be stored in rancher2 provider repo
- integrate tests w/ Jenkins
- update all existing internal documentation to reflect latest refactors

**Comment by Josh-Diamond** [comment]
to address this ticket, tfp-automation framework portion was created and is now stored in `rancher/tfp-automation` repo, and rancher2 provider tests were created and are now stored in `rancher/terraform-provivder-rancher2/tfp-automation`.

Closing out this issue, as this automation as now been fully integrated into Rancher + our Jenkins env 🚀
