### ISSUE TITLE
RKE2 cluster provisioning with different network providers

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#387]
**clusters with Network provider**

- [x] Canal
- [x] Cilium
- [x] Calico
- [x] multus,Canal
- [x] multus, Cilium
- [x] multus, Calico

**Comment by thaneunsoo** [comment]
[38232](https://github.com/rancher/rancher/pull/38232) has been merged. Closing ticket as completed.

### Issue
[RKE2 cluster provisioning with different network providers](https://github.com/rancher/qa-tasks/issues/387)

### Problem

Manually testing provisioning clusters with all CNI providers takes too much time (3+ hours). Even after provisioning there are additional checks to check that workloads are active/running and network checks. We need a way to bring down time used up to do these checks to focus our efforts on other testing as well.

### Solution
A new provisioning test was added in `tests/v2/validation/provisioning/rke2/provisioning_node_driver_test.go`
- `ProvisioningRKE2CNICluster()` will provision clusters with every CNI provider as both `Admin` and `Standard` user

A new helper function was created in `tests/framework/extensions/workloads/podstatus.go`
- helper function uses the dynamic client to grab all pods in specified cluster (Cluster ID must be passed into the function) and then confirms that pods are running/succeeded and there are no errors.

### Engineering Testing
**Manual Testing**
Manually provisioned RKE2 clusters with all different network providers as admin user and standard user

**Automated Testing**
Ran Jenkins job and passed results to reviewers offline.
