### ISSUE TITLE
Create internal docs for - Deploying Rancher/clusters using Terraform

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#389]
Include this information in the internal confluence page

- [x] Repo where TF is available
- [x] How to download and use the binary for TF?
- [x] Where to find latest available TF version and how to install/download and use it?
- [x] Examples of using TF to deploy
- - Rancher docker install server
- - RKE1 cluster
- - RKE2 cluster
- - AKSv2/GKEv2 or EKSv2 cluster
- [x] How to add tests using Terratest? (update Read me of this repo)

**Comment by Josh-Diamond** [comment]
Internal docs may be viewed in Confluence pages provided below:

- RancherQA Confluence > Knowledge Base > Hostbusters (Team 2) > Terraform
- RancherQA Confluence > Knowledge Base > Hostbusters (Team 2) > Terratest
