### ISSUE TITLE
Test Plan to support k8s 1.24

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#391]
v2.6.6 will have k8s 1.24 support. We should look through the changelog and come up with a test plan for rancher (local) cluster and downstream clusters.

**Comment by Josh-Diamond** [comment]
More info surrounding changes with k8s 1.24 implementation found [here](https://github.com/rancher/rancher/issues/37711#issuecomment-1142713212)

**Comment by sowmyav27** [comment]
Done. Sent for Review to dev
