### ISSUE TITLE
Automate tests for ConfigMaps - create / add / delete

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#395]

**Comment by brandonsuse** [comment]
@MKlimuszka Please move this to the next release. Due to lacking resources and time, we cannot work this ticket for 2.6.7

**Comment by sowmyav27** [comment]
needs to be reworked based on shepherd changes,

**Comment by nickwsuse** [comment]
Closing in favor of https://github.com/rancher/qa-tasks/issues/1344 - https://github.com/rancher/rancher/pull/45780
