### ISSUE TITLE
[RKE2] Snapshot + restore using etcd only option

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#405]
Automated test 

### Snapshot
- Deploy an RKE2 cluster node driver - 3 etcd, 2 cp, 3 worker nodes
- enable local etcd snapshots
- create workload w1/ingress1
- Take a backup b1
- Verify backup is listed in cluster mgmt --> Snapshots page
- Verify backup is available on the etcd nodes

### Restore
- Create a workload w2 after backup b1
- Perform restore from b1
- Validate cluster comes up Active
- Validate w1 and ingress1 are available
- Validate w2 does not exist

**Comment by igomez06** [comment]
This would require us to generate a rancher rke.cattle.io client similar to https://github.com/rancher/rancher/pull/38281 This ticket needs the new client to do these type of actions.
