### ISSUE TITLE
[RKE2] Snapshot + restore using `etcd + k8s version` option

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#406]
Automated test 

### Snapshot
- Deploy an RKE2 cluster node driver - 3 etcd, 2 cp, 3 worker nodes on 1.22 RKE2 k8s version
- enable local etcd snapshots
- create workload w1/ingress1
- Take a backup b1
- Verify backup is listed in cluster mgmt --> Snapshots page
- Verify backup is available on the etcd nodes

### Restore
- Create a workload w2 after backup b1
- upgrade to 1.23 rke2 k8s version
- Perform restore from b1 using `etcd + k8s version`
- Validate cluster comes up Active
- Validate w1 and ingress1 are available
- Validate w2 does not exist
- Validate the cluster's k8s version is 1.22 RKE2 version

**Comment by rishabhmsra** [comment]
Both the PRs for v2.6 and v2.7 are merged, hence closing the issue.
- https://github.com/rancher/rancher/pull/39636
- https://github.com/rancher/rancher/pull/39481
