### ISSUE TITLE
[RKE2] Snapshot + restore using `etcd + k8s + cluster config` option

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#407]
Automated test 

### Snapshot
- Deploy an RKE2 cluster node driver - 3 etcd, 2 cp, 3 worker nodes on 1.22 RKE2 k8s version
- enable local etcd snapshots
- create workload w1/ingress1
- Take a backup b1
- Verify backup is listed in cluster mgmt --> Snapshots page
- Verify backup is available on the etcd nodes

### Restore
- Create a workload w2 after backup b1
- Edit cluster, change the upgrade strategy to Control plane concurrency - 10%, worker nodes concurrency: 20%
- upgrade to 1.23 rke2 k8s version
- Perform restore from b1 using `etcd + k8s version`
- Validate cluster comes up Active
- Validate w1 and ingress1 are available
- Validate w2 does not exist
- Validate the cluster's k8s version is 1.22 RKE2 version
- Validate the Upgrade strategy is set back to the default value.

**Comment by markusewalker** [comment]
@thaneunsoo I assigned this issue to you for 2.7.1, but this may be pushed out further due to it being lower priority. As you are handling similar automation for etcd only / etcd + k8s, I assigned to you as you'll have the most familiarity.

**Comment by rishabhmsra** [comment]
Raised PRs for both v2.7 and v2.6, hence closing the issue:
- https://github.com/rancher/rancher/pull/40791
- https://github.com/rancher/rancher/pull/41032
