### ISSUE TITLE
[RKE2] S3 enabled snapshot + restore

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#408]
Automated test 

### Snapshot
- Deploy an RKE2 cluster node driver - 3 etcd, 2 cp, 3 worker nodes
- enable S3 etcd snapshots
- create workload w1/ingress1
- Take a backup b1
- Verify backup is listed in cluster mgmt --> Snapshots page are in Active state
- Verify backup is available in the S3 bucket

### Restore
- Create a workload w2 after backup b1
- Perform restore from b1
- Validate cluster comes up Active
- Validate w1 and ingress1 are available
- Validate w2 does not exist

### Snapshot
- Deploy an RKE2 cluster node driver - 3 etcd, 2 cp, 3 worker nodes
- enable S3 etcd snapshots with incorrect credentials
- create workload w1/ingress1
- Take a backup b1
- Verify backup is listed in cluster mgmt --> Snapshots page are in Failed state
- Verify backup is NOT available in the S3 bucket

**Comment by markusewalker** [comment]
Closing this as this is already covered in this epic: https://github.com/rancher/qa-tasks/issues/986
