### ISSUE TITLE
Scale and Performance testing for 1.24 k8s clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#413]
- we need to include performance testing involved somewhere regarding large clusters to see how it performs.
- With the reports that the new dockershim replacement, and if it's slower, we need to see the impact.

Specific usecases:

- Local and downstream 1.24 RKE1 and RKE2 clusters - individual cluster performance
- Large number of downstream RKE1/RKE2  Rancher provisioned clusters

**Comment by bmdepesa** [comment]
Can be tested once https://github.com/rancher/rke/issues/2936 is available

**Comment by git-ival** [comment]
@bmdepesa Completed necessary testing with rancher/qa-tasks#446 and rancher/qa-tasks#447.
