### ISSUE TITLE
Validate feature charts on RKE2 Windows cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#414]
Validate feature charts on RKE2 Windows 2022 cluster using latest chart versions on 2.6head latest

- [x] Fleet
- [x] Monitoring v2
- [x] Project monitoring v2
- [x] Alerting
- [x] Logging v2

**Comment by brandonsuse** [comment]
Deferring this ticket to v2.6.7 per conversation with @MKlimuszka and @SheilaghM agreeing with me that this test effort should be pushed to the next release due to current resource constraints & my team taking on other current release priorities.

**Comment by ronhorton** [comment]
~~Logging v2 fail: https://github.com/rancher/rancher/issues/38851~~

issue is fixed

**Comment by ronhorton** [comment]
not able to test due to https://github.com/rancher/rancher/issues/38646 still occurring![2022-09-08_12-12-57.png](https://zube.io/files/rancher/3e020de45ee017dbc97afc663926d279-2022-09-08_12-12-57.png)

**Comment by ronhorton** [comment]
2.7.0-rc9 monitoring/project monitoring still have open defects. 
![2022-11-04_17-53-42.png](https://zube.io/files/rancher/43105672830044b580e4be2449b32f6a-2022-11-04_17-53-42.png)

the issues are included in https://github.com/rancher/rancher/issues/38646 which is scoped for 2023-Q1-v2.7x
