### ISSUE TITLE
Validate RHEL 8.6 - Deploy clusters from Rancher Manager

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#415]
On latest Rancher 2.6head or 2.6.6RC 

Pre Requisite: Deploy Rancher on RKE1 local cluster with RHEL 8.6 AMI
- [x] Deploy RKE1 node driver cluster using public AMI RHEL 8.6 and run Network checks on the cluster
- [x] Deploy RKE1 custom cluster using private RHEL AMI with docker installed and run Network checks on the cluster
- [ ] Deploy RKE2 node driver cluster using public AMI RHEL 8.6 and run Network checks on the cluster
- [x] Deploy RKE2 custom cluster using private RHEL AMI with docker installed and run Network checks on the cluster

---
More info:
- Cluster config - 3 etcd, 2 cp and 3 worker nodes
- Cluster k8s version - latest - 1.23

**Comment by markusewalker** [comment]
Currently blocked from doing RKE2 tests, issue is logged here: https://github.com/rancher/rancher/issues/37997

**Comment by markusewalker** [comment]
Closing issue due to known issue https://github.com/rancher/rancher/issues/38216 with public RHEL 8.6 AMIs.

**Comment by sowmyav27** [comment]
Reopening to test on SELinux enabled AMIs

**Comment by sowmyav27** [comment]
On `v2.6.7-rc5`, using 1.24 downstream clusters

- [x] Deploy RKE1 custom cluster using private SELinux enabled RHEL AMI with docker installed and run Network checks on the cluster
- [x] Deploy RKE2 custom cluster using private SELinux enabled RHEL AMI with docker installed and run Network checks on the cluster

---
To enable SELinux
```
# vi /etc/selinux/config
Configure the SELINUX=enforcing option
Save the change, and restart the system: # reboot

Verification:
$ getenforce
Enforcing

To enable SELinux on Docker Daemon
echo '{"selinux-enabled": true}' > /etc/docker/daemon.json
systemctl restart docker

To check if SELinux is enabled on the host
sestatus
```

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6.7-rc5 with local cluster -> RKE1 v1.24.2-rancher1-1, using RHEL 8.6 AMI

- Created nodes with RHEL 8.6 AMI and SELinux enabled.
- Provisioned k8s v1.24, RKE1 and RKE2 downstream custom clusters.
- Network checks passed successfully.

sestatus on nodes:
```
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
```
OS:
```
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
```
