### ISSUE TITLE
Validate RHEL 8.6 - Validate Feature charts on clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#416]
Validate all feature charts on RKE1/RKE2 downstream cluster (Node driver or custom cluster) deployed from Rancher Manager using RHEL 8.6 instances

- [x] Logging v2
- [x] Monitoring v2
- [x] Project Monitoring v2
- [x] Alerting drivers
- [x] CIS - hardened scan/Permissive scan
- [x] Fleet
- [x] Rancher backup restore
- [x] Istio
- [x] OPA Gatekeeper
- [x] Longhorn
- [x] NeuVector

**Comment by ronhorton** [comment]
working to get an ami that will provision. currently getting 
` encountered RSA key, expected OPENSSH key
 E       encountered RSA key, expected OPENSSH key
 E       encountered RSA key, expected OPENSSH key
 E       encountered RSA key, expected OPENSSH key
 E       encountered RSA key, expected OPENSSH key
 E       encountered RSA key, expected OPENSSH key
 E       encountered RSA key, expected OPENSSH key
 E       encountered RSA key, expected OPENSSH key`

**Comment by ronhorton** [comment]
Need updates on:
1. backup/restore
2. opa gatekeeper
3. nuevector

[edited to remove longhorn]

**Comment by bmdepesa** [comment]
Longhorn - Michael
OPA Gatekeeper - Ron
NeuVector - Anu
