### ISSUE TITLE
RKE2 cert rotation

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#418]
TBD

**Comment by markusewalker** [comment]
@Josh-Diamond I assigned this issue for 2.7.1. That milestone may be pushed back further as this item is lower priority. This issue will require further verification as to all that is needed, so please feel free to reach out!

**Comment by Josh-Diamond** [comment]
Requesting more info surrounding this task
---

From my understanding, we created this ticket to add `RKE2 cert rotation` functionality into our automation tests.

Question: 
- `how is this task different then what has been implemented here:`
https://github.com/rancher/rancher/blob/release/v2.7/tests/v2/validation/provisioning/rke2/cert_rotation_test.go

**Comment by slickwarren** [comment]
this was completed some time ago afaik. closing for now.
