### ISSUE TITLE
Validate RKE2 clusters - all Container Network options on 1.24 RKE2 version

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#422]
Validate deploying RKE2 clusters using different Container Network options and run Network checks on the clusters on 1.24 RKE2 version
- [x] calico
- [x] canal
- [x] cilium
- [x] multus,canal
- [x] multus,cilium
- [x] multus,calico

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6.7-rc3
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: Admin and Standard User RKE2 clusters

----------

### Testing: ###

All checks have passed and this issue https://github.com/rancher/rancher/issues/38379 will be addressed in 2.7.0 release
