### ISSUE TITLE
Run Conformance checks for v1.24/rancher

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#423]
Run Conformance checks for v1.24/rancher

**Comment by vivek-shilimkar** [comment]
**Rancher Server Setup**

- Rancher version:v2.6.7-rc1
- Installation option (Docker install/Helm Chart): Docker
- Proxy/Cert Details:Selfsigned

**Information about the Cluster**

- Kubernetes version:v1.24.2
- Cluster Type (Local/Downstream): 
  - Downstream 1 Node with CP, ETCD and Worker, 2 Worker nodes.

**To Reproduce**
- Create downstream cluster on Rancher v2.6.7-rc1 with NGINX Ingress turned off.
- Once the cluster is up and active, update the kube_api with following extra argument.
 ```
   extra_args:
        service-account-issuer: https://<cp_ip>:6443
```
(`<cp_ip>` is Public/External IP of Control Plane)
- Run conformance test

**Results**
```
Ran 356 of 6971 Specs in 5784.237 seconds
SUCCESS! -- 356 Passed | 0 Failed | 0 Pending | 6615 Skipped
PASS

Ginkgo ran 1 suite in 1h30m14.5888112s
Test Suite Passed
```
