### ISSUE TITLE
Validate Conformance checks for v1.24/rke

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#424]
Validate Conformance chhecks for v1.24/rke

**Comment by rishabhmsra** [comment]
**Rancher Server Setup :**
RKE version : v1.3.13-rc3

**Information about the Cluster:**
Kubernetes version : v1.24.2-rancher1-1
Cluster Type: RKE1 - 1 node with roles - cp, etcd and worker, 2 worker nodes

**To Reproduce :**
- In cluster.yaml set ingress provider as none.
```
ingress:
  provider: none
```
- Add kube-api args:
```
kube-api:
    extra_args:
      service-account-issuer: https:<cp-public-ip>:6443
```
- Run conformance test

**Result:**
```
Ran 356 of 6971 Specs in 5463.390 seconds
SUCCESS! -- 356 Passed | 0 Failed | 0 Pending | 6615 Skipped
PASS

Ginkgo ran 1 suite in 1h31m5.305807985s
Test Suite Passed
```

**Comment by rishabhmsra** [comment]
Conformance test results PR on cncf : https://github.com/cncf/k8s-conformance/pull/2024

**Comment by rishabhmsra** [comment]
Above PR is merged, hence closing the issue.
