### ISSUE TITLE
Hosted cluster Additional Test cases

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#436]
For AKS/GKE cluster
- [ ] Edit and add node pools
- [ ] Edit and upgrade k8s
- [ ] Import clusters + Edit and make changes
- [ ] Deploy Private clusters

**Comment by markusewalker** [comment]
@slickwarren @thaneunsoo I assigned each of us to this with the idea each of us can tackle one hosted cluster? This is lower priority for 2.7.1, and since they're all relatively similar, it makes sense for them to be worked on together.

**Comment by markusewalker** [comment]
Split this ticket into three different tickets as this will be a collective effort with different QAs working on them. I will handle [AKS](https://github.com/rancher/qa-tasks/issues/534), Caleb will do [EKS](https://github.com/rancher/qa-tasks/issues/535) and Tim will do [GKE](https://github.com/rancher/qa-tasks/issues/536).

Closing this issue as a result.
