### ISSUE TITLE
Validate SLES 15 SP4 - Deploy clusters from Rancher Manager

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#437]
On latest Rancher 2.6head or 2.6.7RC 

Pre Requisite: Deploy Rancher on RKE1 local cluster with SLES 15 SP4 AMI
- [x] Deploy RKE1 node driver cluster using public AMI SLES 15 SP4 and run Network checks on the cluster
- [x] Deploy RKE1 custom cluster using private SLES 15 SP4 with docker installed and run Network checks on the cluster
- [x] Deploy RKE2 node driver cluster using public AMI SLES 15 SP4 and run Network checks on the cluster
- [x] Deploy RKE2 custom cluster using private SLES 15 SP4 with docker installed and run Network checks on the cluster

---
More info:
- Cluster config - 3 etcd, 2 cp and 3 worker nodes
- Cluster k8s version - latest - 1.24 for RKE1 and 1.23 for RKE2

**Comment by vivek-shilimkar** [comment]
Following scenarios on SLES 15SP4 passed.

Validation steps:

1. Created rancher server v2.6-head (a678d0e) SLES 15SP4 AMI - ami-0fe63ea712ff88591
2. Created RKE1 node driver cluster and ran network checks. 

Created a new Private SLES 15SP4  AMI. ami-0aab928a1b0873c72
1. On rancher server deployed a RKE1 and RKE2 custom cluster.
2. Ran network checks, network checks passed.

**Comment by vivek-shilimkar** [comment]
Validation steps:

1. Created rancher server v2.6-head (a678d0e) SLES 15SP4 AMI - ami-0fe63ea712ff88591
2. Created a RKE2 node driver cluster and ran network checks.

All checks passed.
