### ISSUE TITLE
Validate OpenSUSE Leap 15.4 - Deploy clusters from Rancher Manager 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#439]
On latest Rancher 2.6head or 2.6.7RC 

Pre Requisite: Deploy Rancher on RKE1 local cluster with OpenSUSE Leap 15.4 AMI
- [x] Deploy RKE1 node driver cluster using public AMI OpenSUSE Leap 15.4 and run Network checks on the cluster
- [x] Deploy RKE1 custom cluster using private OpenSUSE Leap 15.4 with docker installed and run Network checks on the cluster (Note: OpenSUSE Leap 15.4 from AWS comes with docker `20.10.14-ce` installed)
- [x] Deploy RKE2 node driver cluster using public AMI OpenSUSE Leap 15.4 and run Network checks on the cluster
- [x] Deploy RKE2 custom cluster using private OpenSUSE Leap 15.4 with docker installed and run Network checks on the cluster

---
More info:
- Cluster config - 3 etcd, 2 cp and 3 worker nodes
- Cluster k8s version - latest - 1.24 for RKE1 and 1.23 for RKE2

**Comment by vivek-shilimkar** [comment]
Following scenarios on OpenSUSE Leap 15.4 passed.

Validation steps:

1. Created rancher server v2.6-head (a678d0e) OpenSUSE Leap 15.4 AMI - ami-0be91f4be81da8bea
2. Created RKE1 node driver cluster and ran network checks. 

Created a new Private OpenSUSE leap 15.4 AMI. ami-0ef116dcebe529ed5
1. On rancher server deployed a RKE1 and RKE2 custom cluster.
2. Ran network checks, network checks passed.

**Comment by rishabhmsra** [comment]
On rancher v2.6-head(bda0897):
- Deployed RKE2 node driver cluster using OpenSUSE Leap 15.4 AMI (ami-0be91f4be81da8bea). 
- Ran network checks.
- All checks passed successfully.
