### ISSUE TITLE
Support Matrix - New OS - Charts Testing

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#440]
The following charts and OS combination need to be tested. k8s version should be the highest version supported, with 1.24 being the target default. 

| OS                 | Chart                | k8s Version | Assignee | RKE1/RKE2 |
|--------------------|----------------------|-------------|----------|-----------|
| SLES 15 SP4        | Istio                |      1.24       |     Nick     |     Pass/Pass     |
|                    | Monitoring / Alerts  |     1.24        |    Ron      |   Pass/Pass       |
|                    | Logging              |         1.24    |     Ron     |       Pass/Pass   |
|                    | Rancher Backup       |      1.24      |     Nick     |     Pass/Pass    |
|                    | Fleet                |      1.24       |     Drew     | Pass/Pass          |
|                    | CIS                  |    1.24         |     Drew     | Pass/  Pass     |
|                    | Prometheus Federator |      1.24       |     Drew|  Pass/  Pass       |
|                    | ~~Harvester~~            |     1.24        |         |           |
|                    | NeuVector            |      1.24       |     Anupama     |     Pass/Pass      |
|                    | ~~Longhorn~~             |      1.24      |  Michael | Pass/Pass |
| ~~SLE Micro 5.2~~     | Istio                |             |     Nick     |      N/A     |
|                    | Monitoring / Alerts  |             |     Ron     |     N/A      |
|                    | Logging              |             |     Ron     |      N/A     |
|                    | Rancher Backup       |            |    Nick      |    N/A       |
|                    | Fleet           |             |     Drew     |    N/A       |
|                    | CIS                  |             |     Drew     |    N/A       |
|                    | Prometheus Federator |             |     Drew     |    N/A       |
|                    | ~~Harvester~~            |             |          |           |
|                    | NeuVector            |             |     Anupama     |   N/A         |
|                    | ~~Longhorn~~             |             |  |  |
| openSUSE Leap 15.4 | Istio                |     1.24        |     Nick     |     Pass/Pass      |
|                    | Monitoring / Alerts  |      1.24       |     Ron     |     Pass/Pass      |
|                    | Logging              |       1.24      |     Ron     |  Pass/Pass        |
|                    | Rancher Backup       |     1.24        |     Nick     |      Pass    |
|                    | Fleet|        1.24     |     Drew     | Pass/ Pass         |
|                    | CIS                  |        1.24     |     Drew     |   Pass/pass       |
|                    | Prometheus Federator |       1.24      |     Drew | Pass/Pass          |
|                    | ~~Harvester~~            |    1.24         |          |           |
|                    | NeuVector            |     1.24        |    Anupama      |      Pass/Pass     |
|                    | ~~Longhorn~~             |     1.24       | Michael | Pass/Pass |
| RHEL 8.6*           | Istio                |    1.24         |      Nick    |     Pass/Pass     |
|                    | Monitoring / Alerts  |     1.24        |     Ron     |       Pass/Pass   |
|                    | Logging              |    1.24         |    Ron      |     Pass/Pass     |
|                    | Rancher Backup       |    1.24         |    Nick      |     Pass      |
|                    | Fleet|      1.24       |     Drew     |    Pass/Pass      |
|                    | CIS                  |     1.24        |     Drew     |    Pass/Pass      |
|                    | Prometheus Federator |     1.24        |     Drew | bug 1/  Pass       |
|                    | ~~Harvester~~            |     1.24        |         |           |
|                    | NeuVector            |     1.24        |    Anupama      |    Pass/Pass       |
|                    | ~~Longhorn~~             |     1.24       | Michael | Pass/Pass |

*Oracle Linux, Rocky Linux, Amazon Linux should be covered by RHEL certification

Rancher Backup Extra Tests:
- Restore and migrate to new rancher server cluster - Pass
- Restore and rollback in the same rancher setup - Pass
- Restore and rollback in a new rancher - Pass

fleet context
fleet -bug blocking SSH https://github.com/rancher/dashboard/issues/7746
fleet - https://github.com/rancher/fleet/issues/765 - HTTP Auth deprecated

bug 1- https://github.com/rancher/rancher/issues/38425

SLES 15 SP4: ami-0edef877c00b19d23
openSUSE Leap 15.4: ami-04a4591e745abae13
RHEL 8.6: ami-053835e36b16f97d0

**Comment by brandonsuse** [comment]
LOE estimate: 2-2.5 days
With teraform applied, this estimate might be lower

**Comment by bmdepesa** [comment]
Just awaiting NeuVector test results.

**Comment by anupama2501** [comment]
Rancher version v2.6.7-rc5
Verified NeuVector chart version `100.0.1+up2.2.2` on k8s 1.24 for both RKE1 and RKE2 downstream clusters and updated the results in the above table.
