### ISSUE TITLE
Review internal docs for AirGap checks 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#442]
Review internal docs for AirGap checks  --> Deploy airgap using our Jenkins and how to access it.

If any information is missing please add it to internal docs.

**Comment by Josh-Diamond** [comment]
Since we are all assigned to this, as feedback from everyone makes the most sense, we should post a comment here, once we have provided our review, then the last employee to add their feedback closes it out  👍

**Comment by Josh-Diamond** [comment]
LGTM - ✅ 

I have ensured the following topics were sufficiently covered:
- How to deploy Airgap using Jenkins? - ✅ 
- How airgap from Jenkins works ? - ✅

**Comment by timhaneunsoo** [comment]
LGTM

**Comment by markusewalker** [comment]
LGTM. The documentation is concise and to the point. It is a good reference point to use when having to create airgapped clusters.

**Comment by sowmyav27** [comment]
Moving it to done, since there are 3 reviews.
