### ISSUE TITLE
Scale Testing and Recommendations

### ISSUE THREAD

**Issue by samjustus** [rancher/qa-tasks#450]
Explore various resource levels and identify the impact (or lack thereof) on performance

e.g.
- Projects and bindings
  - Does it matter how many clusters the projects are spread across?
  - How many projects or to what level the relation of quantity of bindings, projects, nodes, is affecting performance?
  - Measuring impact of projects (or bindings as a result of the projects?) or clusters, or relationship between the two
    - Will need to explore with different setups 
    - Will it crash? Is it notably slower?
    - QA should already have a baseline to test against

**Comment by git-ival** [comment]
Initial test effort for individual components has been completed and results have been logged internally for the team to review, provide feedback/next steps and action on them.
