### ISSUE TITLE
Automate Project Owner RBAC v1 API Calls

### ISSUE THREAD

**Issue by brudnak** [rancher/qa-tasks#455]
- [ ] Project owner can list the downstream cluster
- [ ] Project owner should be able to list Projects the user owns
- [ ] Project owner should NOT be able to create new Projects in the cluster
- [ ] Project owner should NOT be able to assign members to the cluster
- [ ] Project owner should be able to list namespaces in the project the user owns and is able to create namespaces
- [ ] Project owner should be able to assign users as project members to the project

<hr>

EPIC: https://github.com/rancher/qa-tasks/issues/168

**Comment by anupama2501** [comment]
Closing the issue as the PRs have been merged and validated.
