### ISSUE TITLE
[Automation] Delete/Add nodes in a Custom RKE2/K3S cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#459]
1. Add worker nodes
- Create custom RKE2 cluster - 1etcd, 1 cp and 1 worker nodes
- Add a worker node
- verify the cluster state goes to updating and comes back up Active
- Verify the additional worker node is in Active state
- Verify the node is added successfully, a daemonset scales to this worker node also

2. Add a control plane node
- Create custom RKE2 cluster - 1etcd, 1 cp and 1 worker nodes
- Add one control plane node
- verify the cluster state goes to updating and comes back up Active
- Verify the additional control plane node is in Active state

3. Add two etcd nodes
- Create custom RKE2 cluster - 1etcd, 1 cp and 1 worker nodes
- Add _two_ etcd nodes
- verify the cluster state goes to updating and comes back up Active
- Verify the two additional etcd nodes are in Active state

**Comment by sowmyav27** [comment]
Wait on this to be completed - https://github.com/rancher/qa-tasks/issues/461

**Comment by slickwarren** [comment]
@markusewalker could you check if this is included in your latest scaling PR?

**Comment by markusewalker** [comment]
Deleting nodes is for both custom and node driver. Adding nodes in a custom cluster is currently not in the framework. That is an item that I have in my queue to get done.

**Comment by markusewalker** [comment]
v2.7 PR merged, v2.8 will be merged once it is open to be merged.

**Comment by markusewalker** [comment]
v2.8 PR merged as well.
