### ISSUE TITLE
[RKE2] Add/Delete nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#460]
- [ ] On a custom RKE2 cluster, add a worker node
- [ ] On a node driver RKE2 cluster, scale up an existing worker nodepool 
- [ ] On a node driver RKE2 cluster, Edit cluster, add another worker nodepool
- [ ] On a custom RKE2 cluster, delete a worker node
- [ ] On a node driver RKE2 cluster, scale down an existing worker nodepool by clicking on `Scale Down` option
- [ ] On a node driver RKE2 cluster, Edit cluster, delete a worker nodepool

**Comment by sowmyav27** [comment]
Dup of https://github.com/rancher/qa-tasks/issues/459

**Comment by markusewalker** [comment]
Closing as dup of https://github.com/rancher/qa-tasks/issues/459.
