### ISSUE TITLE
[RKE1] Scale up/down nodes

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#461]
we need the ability to test scaling node pools up and down, and should create a test doing this. 

---
**Custom cluster** --> Already available in python tests [here](https://github.com/rancher/rancher/blob/release/v2.6/tests/validation/tests/v3_api/test_rke_cluster_provisioning.py)
- [x] On a custom RKE1 cluster, add a worker node
- [x] On a custom RKE1 cluster, delete a worker node
---
**Node driver**
- [x] On a node driver RKE1 cluster, scale up an existing worker nodepool --> Already available in python tests [here](https://github.com/rancher/rancher/blob/release/v2.6/tests/validation/tests/v3_api/test_rke_cluster_provisioning.py)
- [x] On a node driver RKE1 cluster, Edit cluster, add another worker nodepool
- [x] On a node driver RKE1 cluster, scale down an existing worker nodepool by clicking on `Scale Down` option
- [x] On a node driver RKE1 cluster, Edit cluster, delete a worker nodepool

**Comment by markusewalker** [comment]
This work is still being undergone. There were initial complications that delayed a solution for this and along with higher priority tickets, this was put on the backburner.

This is still en route to be completed in the assigned milestone in 2.7.0.

**Comment by markusewalker** [comment]
2.6 PR: https://github.com/rancher/rancher/pull/39124
2.7 PR: https://github.com/rancher/rancher/pull/39143

**Comment by markusewalker** [comment]
Installed.
