### ISSUE TITLE
Create `additional tests` package to configure tests run as we scale

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/qa-tasks#464]
Create `additional tests` package to configure tests run as we scale. This will consist of a new configuration being added where users will call the additional tests they want to run. New directory will be created under the parent provisioning directory. All new tests unrelated to the actual provisioning of clusters will be added here, i.e. checking cpu usage or executing additional commands on running cluster. All provisioning tests will be updated to iterate through the tests specified in the config file and only run the tests needed to run.

**Comment by bmdepesa** [comment]
We should not call it `additional tests` as that provides little useful information. Instead, we should be more specific with the naming as it relates to the functions of the tests in that package.

**Comment by igomez06** [comment]
I agree it shouldn't just be additional tests, as from speaking from you it sounds more like system validations of some sort of the clusters. Let's not have anything super generic like this @thaneunsoo

**Comment by thaneunsoo** [comment]
Closing this ticket as we are taking a different approach now
