### ISSUE TITLE
Automate Cluster Member RBAC v1 API calls

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#465]
- [ ] Cluster member owner can list the downstream cluster
- [ ] Cluster member should NOT be able to assign members to the cluster
- [ ] Cluster member should NOT be able to list projects the user does not own
- [ ] Cluster member should NOT be able to list namespaces the user does not own
- [ ] Cluster member should NOT be able to create namespaces in Projects the user does not own
- [ ] Cluster member should be able to create Projects in the cluster

**Comment by anupama2501** [comment]
This has been automated and merged. 
Following are the PRs: 

v2.6 https://github.com/rancher/rancher/pull/39630
v2.7 https://github.com/rancher/rancher/pull/39541
