### ISSUE TITLE
[Legacy Python Maintenance] Fix/Restore HA provisioning of rancher on hosted clusters (EKS, AKS, GKE)

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#466]
Currently, we have the following issues installing rancher on hosted clusters:
- [ ] eks:
  * unable to use kubeconfig locally (not able to diagnose issues further due to this)
    * unclear what variables should be set when using this job. I just search for `eks` on the page, and fill that info in. Is more needed? 
  * seems that there is some issue getting the LB -> hostname from kubectl ingress, and route53 complains that the hostname given is empty
  * Node(s) are being created outside of specified regions (i.e. defaults say us-east-2a,us-east-2b, but I have nodes in 2c)
  * node names are not given, hard to track them down in resources
  * ELB name is also random, does not contain given short name `RANCHER_HOSTNAME_PREFIX` that other resources have when using the job with rke
- [ ] gke:  
  * not currently merged, but somewhat magically no conflicts as of 8/10/22: https://github.com/rancher/rancher/pull/34697
    * probably still needs to be updated, based on feedback in slack for ingress to work. You need the last flag in order for ingress to work properly.
```
helm upgrade --install \
  ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --set controller.service.type=LoadBalancer \
  --version 4.2.0 \
  --create-namespace --set controller.watchIngressWithoutClass=true
```
- [ ] aks:
  * similar issues to eks, in that it is not obvious which parameters should be set to use AKS
  * it seems that there is some issue with ingress-nginx-controller, perhaps the same fix for GKE would work, however I was not able to get rancher working just by fixing ingress . . There is something else going on here, but I could not diagnose it in a timely fashion. 

These all exist in our python framework, however could be rewritten using https://github.com/rancherlabs/corral

**Comment by markusewalker** [comment]
This has been addressed as per issue https://github.com/rancher/qa-tasks/issues/473. When running the HA provisioning tests with hosted clusters AKS, EKS and GKE, all have been validated to be running successfully.

As a result, closing this issue.
