### ISSUE TITLE
Automate additional RBAC cases - Project RBAC

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#467]
Andrew:
- [ ] 1. Project owners in a downstream cluster should not be able to access projects in a different downstream clusters they are not members of 
- [ ] 2. Add a standard user with custom `Manage Project Members` and as this user add another user as a project member

**Comment by anupama2501** [comment]
Made new issue for cluster rbac additional cases https://github.com/rancher/qa-tasks/issues/538

**Comment by dasarinaidu** [comment]
https://github.com/rancher/rancher/pull/41153
