### ISSUE TITLE
Add jenkinsfile/support for TF automation

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#469]
TF work was done as part of this issue, however no jenkins integration has been added. We will likely need a new/update to existing jenkinsfile/dockerfile to:
* install TF and dependency packages
* load tfvars 
* run specified TF tests
all of which should model after our existing config in jenkins

**Comment by Josh-Diamond** [comment]
This has been implemented and is included in the PR to address:
https://github.com/rancher/qa-tasks/issues/386

This change will be included once PR for above issue is merged.
