### ISSUE TITLE
Release Testing checks - Airgap

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#478]
Airgap Testing --> Deploy all k8s versions clusters, RKE1 and RKE2, Deploy all feature charts, look for any image pulls

**Comment by bmdepesa** [comment]
1. Determine if we can run our automation against the airgap server by using the public NLB

(lower priority) Private registry & bastion should be created using Corral packages
Images for Rancher and any required test images should be loaded as part of the registry setup

Deploy clusters and ensure all clusters come up active for RKE1/RKE2
Deploy feature charts

Ensure all workloads are running correctly (no image pull errors) -- requires new code

Upgrade cluster versions

All of this needs to be tied together into a Jenkins job with little manual intervention.

**Comment by bmdepesa** [comment]
Proxy for - git repo, registry, helm repo, logging endpoints

**Comment by igomez06** [comment]
Work needs to be done to deploy feature charts.
Work on cluster deployment is completed: https://github.com/rancher/rancher/pull/41604

**Comment by bmdepesa** [comment]
@igomez06 can you create a followup task for the feature chart deployment?
