### ISSUE TITLE
k3s Provisioning tests

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#495]
Add tests similar to what we have for RKE2 currently

For node driver and custom clusters, include the following tests

- 1 Node all roles Admin User
- 1 Node all roles Standard User
- 3 nodes - 1 role per node Admin User
- 3 nodes - 1 role per node Standard User

Note: These are applicable only from 2.6.9+ and 2.7.0+

**Comment by markusewalker** [comment]
Locally, I have this task done. As described in the issue description, I have validated tests for node driver and custom cluster are successful for K3s. I am awaiting for task https://github.com/rancher/qa-tasks/issues/461 to have its associated PR merged before opening a PR for this issue.

**Comment by markusewalker** [comment]
Installed.
