### ISSUE TITLE
Add support for provisioning k3s hardened Rancher managed Custom clusters

### ISSUE THREAD

**Issue by markusewalker** [rancher/qa-tasks#500]
### Issue Description
When provisioning clusters, we should have automated tests to harden the clusters. For security purposes, this should be seen as the default, so tests should be added to our framework

---

- [x] Deploy a k3s hardened local cluster HA rancher deploy - incorporated existing hardened k3s cluster code in our Jenkins job to enable it.
- [x] Deploy a k3s hardened downstream custom cluster

**Comment by markusewalker** [comment]
Closing in favor of https://github.com/rancher/qa-tasks/issues/417.

**Comment by anupama2501** [comment]
Re-opened as this is to track k3s cluster hardening.

**Comment by markusewalker** [comment]
2.6 PR: https://github.com/rancher/rancher/pull/39620
2.7 PR: https://github.com/rancher/rancher/pull/39614

**Comment by markusewalker** [comment]
Installed.
