### ISSUE TITLE
Upgrade usecase for 2.7.0

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#501]
### Upgrade from 2.7.0 RancherC to RancherP. 
- [ ] Verify the Global setting is set
- [ ] Verify UI branding changes

### Upgrade from 2.7.0 RancherP to RancherC
- [ ] Verify the Global setting is set to blank (unset from prev validation)
- [ ] Verify UI branding changes (back to rancher normal)

**Comment by slickwarren** [comment]
tested on rancher v2.7.0-rc6 on a docker install:
### Upgrade from 2.7.0 RancherC to RancherP. 
- [x] Verify the Global setting is set - global registry
- [x] Verify UI branding changes

### Upgrade from 2.7.0 RancherP to RancherC
- [x] Verify the Global setting is set to blank (unset from prev validation) -- global registry
- [ ] Verify UI branding changes (back to rancher normal) - FAIL
it appears that the environment variable may be saved when upgrading, hence why the P -> C case does not remove the branding/global setting.

**Comment by slickwarren** [comment]
tracking failing use case here: https://github.com/rancher/rancher/issues/39456
