### ISSUE TITLE
Fix ha_deploy

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#504]
Fix ha_deploy - `test_install_rancher_ha` when `RANCHER_HA_HOSTNAME` and `RANCHER_HA_KUBECONFIG` are set, `RANCHER_HA_HARDENED` is set to `True`.

Workaround for now -   `RANCHER_HA_HARDENED` is set to `False`.
```
 print_kubeconfig(kubeconfig_path)
         if RANCHER_HA_HARDENED and RANCHER_LOCAL_CLUSTER_TYPE == "RKE":
 >           prepare_hardened_cluster(profile, kubeconfig_path)
 E           UnboundLocalError: local variable 'profile' referenced before assignment
```

and
```
In test_create_ha.py
Line 82
profile = 'rke-cis-1.5'
Needs to be moved outside of the 2 parent conditionals so it's set by default
```

**Comment by markusewalker** [comment]
2.6 PR: https://github.com/rancher/rancher/pull/39331
2.7 PR: https://github.com/rancher/rancher/pull/39330

**Comment by markusewalker** [comment]
Installed.
