### ISSUE TITLE
Automate Private Registry Validations

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#51]
Create a private registry and automate the setup using a Corral package (this should be done when the airgap task is completely finished) 

We need to support testing all private registry configurations in Rancher: 

* Global private registry defined in Global Settings with no auth -> Not automated
* Cluster level private registry with no auth configured -> Not automated
* Cluster level private registry with auth configured -> Already automated, but update to use valid certificates

We need to start running this automation during every release cycle.

The automated test should take in a private registry address as an input
Check that workloads are using images from private registry (especially for system workloads)
The jenkins job should optionally support running the corral or pointing to an existing setup
Private registry should use valid certs 
Investigate if we have an option for providing a CA for a private registry using self-signed/untrusted certs. If so, we should automate this case as well. 

--- 

We are changing the way private registries work in 2.7 so we may need to add automation specific to those use cases.

**Comment by bmdepesa** [comment]
Private registry should use valid certs
Add cases for node-driver using private registry
Add validation that all system workloads are from the defined registry

**Comment by izaac** [comment]
For RKE1 the CA cert should be added in the Custom Cluster nodes before joining the cluster (using the generated command from Rancher).

For RKE2 there are TLS secret and CA bundle UI input/text fields to configure private registries.

**Comment by bmdepesa** [comment]
Private registry things to check - git repo, registry, helm repo, logging endpoints

**Comment by bmdepesa** [comment]
https://github.com/rancher/rancher/pull/41420
https://github.com/rancher/rancher/pull/41596
https://github.com/rancher/rancher/pull/41671
https://github.com/rancher/rancher/pull/41861
https://github.com/rancher/rancher/pull/41984
