### ISSUE TITLE
Automate Provisioning vSphere Windows Node driver cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#523]
Automate Provisioning vSphere Windows Node driver cluster

**Comment by markusewalker** [comment]
2.7 PR - https://github.com/rancher/rancher/pull/41250
2.6 PR - https://github.com/rancher/rancher/pull/41251

Windows support will come later as that will involve refactoring to the node driver provisioning test that impact the other providers, potentially.

**Comment by markusewalker** [comment]
2.7 PR merged, awaiting to merge 2.6 PR once the latest release is finished.

**Comment by markusewalker** [comment]
Initial PRs merged. Leaving task open as we still need to support Windows.

**Comment by slickwarren** [comment]
done as part ot https://github.com/rancher/shepherd/pull/6
