### ISSUE TITLE
update airgap automation now that rancher-save and rancher-load images.sh scripts have been modified

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#528]
we hard code the removal of the `docker save` step of populating registries using rancher scripts to save time. However, it is based on line number and currently breaks (as of v2.7.0-rc11).  We should make this more dynamic, or at a minimum just update it to remove the new line(s) that docker save.

**Comment by rancher-max** [comment]
This has been done for a while so am just closing
