### ISSUE TITLE
Charts Private Registry and External Images Automation

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#529]
Monitoring and Istio charts require external images to be pulled. This needs:

- Experiments with Private Registry & Airgap difference
- Logic to pull external images both for private registry and airgap
- Logic to add registry prefix

**Comment by bmdepesa** [comment]
rancher/rancher#39151
rancher/rancher#39152

**Comment by bmdepesa** [comment]
@caliskanugur update the status of this.

**Comment by caliskanugur** [comment]
Our tests don’t have support for the above cases, this is a task to create/append image `txt` files and then pull the required images for the tests

**Comment by caliskanugur** [comment]
The linked PRs are the ports for the charts tests, we need those images identified and pulled in the private registry & airgap test cases

**Comment by sowmyav27** [comment]
@bmdepesa @caliskanugur can we close this since charts - Istio and monitoring are not handled by our teams anymore?

**Comment by caliskanugur** [comment]
Moved to: https://github.com/rancher/qa-tasks/issues/1153
