### ISSUE TITLE
[EKS] Additional tests for hosted cluster

### ISSUE THREAD

**Issue by markusewalker** [rancher/qa-tasks#535]
### Issue Description
Currently, in our testing framework, we support hosted cluster provisioning for AKS, EKS and GKE. We should expand upon this and include the following for EKS:

- [ ] Importing clusters + editing and making changes
- [ ] Editing and adding node pools --> In an imported and rancher provisioned cluster
- [ ] Deploying private clusters

**Comment by sowmyav27** [comment]
@markusewalker @Josh-Diamond @slickwarren Let's pause on these since "Hosted clusters" will be moved to another team.

**Comment by markusewalker** [comment]
No longer responsible for hosted cluster provisioning. Closing issue.
