### ISSUE TITLE
[GKE] Additional tests for hosted cluster

### ISSUE THREAD

**Issue by markusewalker** [rancher/qa-tasks#536]
### Issue Description
Currently, in our testing framework, we support hosted cluster provisioning for AKS, EKS and GKE. We should expand upon this and include the following for GKE:

- [ ] Editing and adding node pools
- [ ] Editing and upgrading K8s
- [ ] Deploying private clusters

**Comment by sowmyav27** [comment]
@markusewalker @thaneunsoo Let's pause on these, since "Hosted clusters" will be moved to another team

**Comment by markusewalker** [comment]
No longer responsible for hosted cluster provisioning. Closing issue.
