### ISSUE TITLE
Unmarshaling is psudorandom by design - consider alternatives once we depend on order of variables entered

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#540]
When unmarshaling into a map[string] interface, we run into problems if we expect an order from the user-entered variables. 

I encountered this when writing some code for configuring corral; we are able to run a package just fine, but when trying to run multiple packages that depend on each other, the order of the packages entered by the user was not (always) preserved. 
I found some posts on this, [i.e. stackoverflow](https://stackoverflow.com/questions/70777144/go-unmarshal-yaml-and-preserve-order), but I'm not sure the right move for our framework.

**Comment by sowmyav27** [comment]
@slickwarren Can this issue be closed?

**Comment by slickwarren** [comment]
I can close it as a `wont-fix` as this doesn't seem to affect much at this time.
