### ISSUE TITLE
release checks for non community version of rancher - Rancher Prime

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#544]
* validate images are in registry -- we have scripts for this, need to add them to jenkins if possible
* validate /rancherversion
* validate ui-brand is set

**Comment by markusewalker** [comment]
This is covered as part of https://github.com/rancher/qa-tasks/issues/642.

**Comment by markusewalker** [comment]
https://github.com/rancher/qa-tasks/issues/642 has been merged and as such, this issue is addressed. Closing issue.
