### ISSUE TITLE
Support Matrix checks - OS Certification - Chart validations

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#549]
New OSes for Q1 release

- RHEL 8.7
- Rocky 8.7
- OL 8.7

**Comment by ronhorton** [comment]
Waiting for go-ahead to test charts on OSes
update: we can test with 1.24

**Comment by rishabhmsra** [comment]
Below chart validations were successful on following OSes - RHEL 8.7, Rocky 8.7 and OL 8.7, hence closing the issue:
- Alerting Drivers
- CIS
- Fleet
- Istio
- Logging
- Monitoring
- OPA Gatekeeper
- Prometheus-Federator
- rancher backups
