### ISSUE TITLE
[K3s Clusters] Add/delete worker nodes 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#552]
4.  Add nodes and Scale down nodes - Node Driver clusters 
- Create Node driver k3s cluster - 1 etcd, 2 cp and 3 worker nodes
- Scale up a worker node pool
- verify the cluster state goes to updating and comes back up Active
- Verify the node is added successfully, a daemonset scales to this worker node also
- Delete a worker node from a worker node pool by selecting a node and clicking on `Scale Down`
- Verify the node is removed successfully from cluster
- Verify the node is removed successfully from the backend - Azure/AWS
- Cluster is in Active state
- Verify the daemonset scales down 
_extension of ^_
- Delete a worker node.
- Verify the worker node is deleted form backend.
- Verify a new worker node starts provisioning
- Verify the new worker node is in Active State.
- Verify the cluster is also in Active state

**Comment by bmdepesa** [comment]
@floatingman will start taking up 4. Add nodes and delete nodes - Node Driver clusters

**Comment by bmdepesa** [comment]
Since there is another PR which covers most of this, the remaining work will be adding the validations around daemonsets on the scaled clusters.

**Comment by bmdepesa** [comment]
This is going to be covered in this PR from Markus - https://github.com/rancher/rancher/pull/41846

**Comment by bmdepesa** [comment]
Superceded by https://github.com/rancher/qa-tasks/issues/771
