### ISSUE TITLE
Update Ubuntu 20.04 private AMI used in automation

### ISSUE THREAD

**Issue by markusewalker** [rancher/qa-tasks#564]
### Issue Description
AS part of ongoing efforts to keep private AMIs updated, we should look to update our Ubuntu 20.04 private AMI as it was first created February 2021. Outside of updating the AMI, several Jenkins jobs that reference this AMI need to be updated as well.

**Comment by sowmyav27** [comment]
It will have to be updated in our code too if need be and not just jenkins

**Comment by sowmyav27** [comment]
Also ensure this is covered in the current issue - https://github.com/rancher/qa-tasks/issues/332
