### ISSUE TITLE
Validate arm64 provisioned k3s clusters on Rancher upgrade to version 2.7.3+

### ISSUE THREAD

**Issue by snasovich** [rancher/qa-tasks#565]
As part of https://github.com/rancher/rancher/issues/34658 (https://github.com/rancher/system-agent/pull/103), system-agent's `-suc` image now also includes arm64 version.
So, to validate this we want to ensure system-agent properly upgrades on k3s downstream clusters provisioned on Rancher 2.7.2 after Rancher is upgraded to version 2.7.3+ (provided that target Rancher version has system-agent version higher than 2.7.2) and the cluster's status is (eventually) Active.

**Comment by Josh-Diamond** [comment]
Not quite ready to test, moving to `blocked` until: 
- Rancher `v2.7.2` is released
- the system-agent version in 2.7.3+ is bumped up from system-agent version of 2.7.2

**Comment by Josh-Diamond** [comment]
not quite ready to test due to lack of bump in system-agent versioning from Rancher v2.7.2 to Rancher v2.7.3

Will resume testing, once system-agent has been bumped up from `rancher/system-agent:v0.3.2-suc`

**Comment by Josh-Diamond** [comment]
moving ticket to `Blocked` column.  Will be able to resume validations once `system-agent` version is bumped from `v0.3.2-suc`

**Comment by Josh-Diamond** [comment]
closing issue out as "not needed"
