### ISSUE TITLE
Create plan for when Jenkins is unavailable

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#568]
Create a document as part of onboarding that shows how Jenkins works behind the scenes so that everybody is able to run any automation locally.
1. Run jobs locally
2. Deploy workloads manually
  a. Architecture: arm devices (armv7) + arm64 + windows + amd64 – Multi-arch workloads?
3. Run standalone scripts
  a. Upload any images
4. Workloads that are their own "tests"/"asserts"
5. Record keeping of the data

**Comment by VestigeJ** [comment]
We're opting to close this and focus on the effort for the test automation framework
