### ISSUE TITLE
Automation - Automate v2 logging

### ISSUE THREAD

**Issue by sangeethah** [rancher/qa-tasks#58]
Automate the following:
1. Deployment of v2 logging charts
2. Configure logging providers
3. Deploy worklods.
4. Check that logs relating to the workload (and it logs) are collected by the logging provider.

**Comment by ronhorton** [comment]
after discussion in stand up brandon m advised move automation tickets out of 2.6.7

**Comment by sowmyav27** [comment]
Closing this since logging has been handed off to another internal team
