### ISSUE TITLE
Move windows Terraform from Python framework to Go framework

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#580]
Convert windows terraform installs from the Python framework to the rke2 Go framework.

Add Windows validations.

Part of rancher/qa-tasks#583 epic.

**Comment by rancher-max** [comment]
https://github.com/rancher/distros-test-framework/pull/21

**Comment by mdrahman-suse** [comment]
This task has been completed and merged.

Feature PR: https://github.com/rancher/distros-test-framework/pull/6, https://github.com/rancher/distros-test-framework/pull/17
JJB PR: https://github.com/rancherlabs/jenkins-job-builder/pull/311
