### ISSUE TITLE
Automate service restart scenario in k3s

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#588]
Part of rancher/qa-tasks#583 epic.

**Comment by est-suse** [comment]
Manual steps:

Install RKE2 HA cluster as we usually do.
Deploy a workload -- ensure it is running successfully
Once everything is up and ready, run this:
# Server Nodes:
sudo systemctl restart k3s

# Agent Nodes:
sudo systemctl restart k3s-agent
While they are restarting, the cluster is not accessible for some minutes, then it should come back up and all nodes and pods should be running and working again
Ensure previously deployed workload is running successfully
Also ensure the previously deployed workload does not get restarted after agent restart
Deploy some new workloads (Pods, deployments, ingress, daemonset, replicas, etc) -- ensure they are running successfully

**Comment by rancher-max** [comment]
This is now automated as part of e2e tests per the PR linked above.
