### ISSUE TITLE
Allow the default K8s version to be selected while provisioning if the K8s version is left blank in the configuration file

### ISSUE THREAD

**Issue by markusewalker** [rancher/qa-tasks#608]
### Issue Description
Currently, the Go automation specifically asks for the K8s version to be inputted in the user's config file. Within Rancher, if you do not specify a K8s version while provisioning, the default version is selected. `rke up` works in a similar fashion.

It would be a nice to have enhancement to refactor the provisioning tests for RKE1/RKE2/K3s where the k8s version is optional and if it is not selected, then it will choose the default K8s version.

**Comment by Josh-Diamond** [comment]
Automation Developer Notes:
- Endpoint to grab available k8s versions:
`https://<rancher_server_url>/v3/settings/k8s-versions-current`

Based on `host_url`, we will be able to grab the available versions and `default` to the highest available version.  API call is not ideal in this situation, looking into grabbing these specs via rancher client

**Comment by Josh-Diamond** [comment]
Automation Developer Notes:
- refactor from API call to use rancher's go framework clients (logic):

```go
k8s_versions_data, err := client.Management.Setting.ByID("k8s-versions-current")
require.NoError(t, err)
available_k8s_versions := strings.Split(k8s_versions_data.Value, ",")
default_k8s_version := available_k8s_versions[len(available_k8s_versions)-1]
```

**Comment by Josh-Diamond** [comment]
Automation Developer Notes:
- the above logic, does not explicitly grab k8s default versions, and also only seems to target RKE1 - this not ideal
- the logic below, will be used to grab default versions instead:
```go
	// start - qa-task #608
	
	// RKE1 Logic
	rke1_default_k8s_version_data, err := client.Management.Setting.ByID("k8s-version")
	require.NoError(t, err)
	rke1_default_k8s_version := rke1_default_k8s_version_data.Value
	t.Log("rke1_default_k8s_version: ", rke1_default_k8s_version)

	// RKE2 Logic
	rke2_default_k8s_version_data, err := client.Management.Setting.ByID("rke2-default-version")
	require.NoError(t, err)
	rke2_default_k8s_version := rke2_default_k8s_version_data.Value
	t.Log("rke2_default_k8s_version: ", rke2_default_k8s_version)

	// K3s Logic
	k3s_default_k8s_version_data, err := client.Management.Setting.ByID("k3s-default-version")
	require.NoError(t, err)
	k3s_default_k8s_version := k3s_default_k8s_version_data.Value
	t.Log("k3s_default_k8s_version: ", k3s_default_k8s_version)

	// stop - qa-task #608
```
- Next: create an extension w/ ^^ logic (dynamically)
- Then: modify tests to check if k8s version is. `default` || `''`; if so, use ^^ versions

---

Logs ensure accurate default values are being grabbed (this is for 2.6.11):

<img width="388" alt="Screenshot 2023-03-17 at 3 50 13 PM" src="https://user-images.githubusercontent.com/46494969/226065756-10fcc0ac-de7b-41ae-a5ee-c572825f25d6.png">

**Comment by Josh-Diamond** [comment]
Automation Developer Notes:
- RKE2 + K3s default versions grabbed don't contain leadiing `v`
- revised logic below will be used instead:

```go
// start - qa-task #608

// RKE1 Logic
rke1_default_k8s_version_data, err := client.Management.Setting.ByID("k8s-version")
require.NoError(t, err)
rke1_default_k8s_version := rke1_default_k8s_version_data.Value
t.Log("rke1_default_k8s_version: ", rke1_default_k8s_version)

// RKE2 Logic
rke2_default_k8s_version_data, err := client.Management.Setting.ByID("rke2-default-version")
require.NoError(t, err)
rke2_default_k8s_version := `v` + rke2_default_k8s_version_data.Value
t.Log("rke2_default_k8s_version: ", rke2_default_k8s_version)

// K3s Logic
k3s_default_k8s_version_data, err := client.Management.Setting.ByID("k3s-default-version")
require.NoError(t, err)
k3s_default_k8s_version := `v` + k3s_default_k8s_version_data.Value
t.Log("k3s_default_k8s_version: ", k3s_default_k8s_version)

// stop - qa-task #608
```

**Comment by Josh-Diamond** [comment]
Latest PR:
https://github.com/rancher/rancher/pull/41287

**Comment by Josh-Diamond** [comment]
Backport mentioned above has been merged. Closing out ticket now
