### ISSUE TITLE
Provisioning clusters with PSACT and validating RBAC

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#610]
This task is to automate the cluster provisioning for PSACT that includes validating rbac as mentioned below:

 User permissions | Configure the Admission Controller ( edit cluster) | 
--- | ---
Admin                     | Yes | 
Restricted Admin  | Yes |   
Cluster Owner       | Yes | 
Cluster Member    | No  | 
Project Owner       | No  | 
Project Member    | No  | 
Project Read Only | No | 

To solve this problem, the option that was discussed 

- [ ] Create a pipeline that links the creation of clusters and rbac test suite that includes:
        - RKE1 cluster
        - RKE2 cluster
        - K3s cluster
@markusewalker - 
        - Disable PSACT
        - Edit and re enable PSACT
   
 @anupama2501 rbac implementation as mentioned in the table above.

**Comment by markusewalker** [comment]
Cluster provisioning PR: https://github.com/rancher/rancher/pull/41121

**Comment by markusewalker** [comment]
Cluster provisioning PR merged.

**Comment by anupama2501** [comment]
Re opening as the RBAC part of the issue has not been completed yet.
For the RBAC requirements:

In our automation, we can make use of  create clusters with PSACT enabled. 

- [ ] Create a custom cluster of types:
    - [ ]  PSACT clusters should be created as a standard user and then create additional users for each role as mentioned in the table below.
    - [ ] RKE1 Example: [rke1/custom_cluster.go](https://github.com/rancher/rancher/blob/6d93a4da981acb9cfd94e3d9675c770600980860/tests/v2/validation/provisioning/rke1/custom_cluster.go#L25)
    - [ ] RKE2 [rke2/custom_cluster.go ](https://github.com/rancher/rancher/blob/6d93a4da981acb9cfd94e3d9675c770600980860/tests/v2/validation/provisioning/rke2/custom_cluster.go#LL32C29-L32C29)
    - [ ] K3s [k3s/custom_cluster.go ](https://github.com/rancher/rancher/blob/6d93a4da981acb9cfd94e3d9675c770600980860/tests/v2/validation/provisioning/k3s/custom_cluster.go#L28)

- [ ] Once the cluster type is created, create tests in the rbac suite to validate for each cluster type, we make sure edit cluster works based on the role assigned.

 User permissions | Configure the Admission Controller ( edit cluster) | 
--- | --- 
Admin                     | Yes | 
Restricted Admin  | Yes | 
Cluster Owner       | Yes | 
Cluster Member    | No  |
Project Owner       | No  |
Project Member    | No  |
Project Read Only | No |

- [ ] Once the edit cluster works, make sure to edit the cluster again and disable the PSACT and verify that it succeeds or fails depending on the role assigned to the user:

 User permissions | Configure the Admission Controller ( Disable cluster) | 
--- | --- 
Admin                     | Yes | 
Restricted Admin  | Yes | 
Cluster Owner       | Yes | 
Cluster Member    | No  |
Project Owner       | No  |
Project Member    | No  |
Project Read Only | No |


### Note: 
We have a new change coming in where the cluster creation would be an extension that will be fixed as part of this ticket https://github.com/rancher/qa-tasks/issues/780. Make sure the changes are merged in for #780 prior to working on this issue.

**Comment by Priyashetty17** [comment]
Closing as the PR is merged.
