### ISSUE TITLE
Post KDM OOB release checks

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#612]
Currently this is done manually
- [x] verify the new released versions of RKE1/RKE2/k3s show up in Rancher UI
- [x] Verify a single node cluster - all roles deployed successfully for All new released k8s versions - rke1/rke2/rk3s. Verify the cluster is up and Active and the workloads in System Project page (All namespaces in System Project) are up and Active.

**Comment by rishabhmsra** [comment]
Raised PRs for both v2.7 and v2.6, hence closing the issue
- https://github.com/rancher/rancher/pull/40996
- https://github.com/rancher/rancher/pull/41031
