### ISSUE TITLE
Need to  build a test container that can deploy successfully in PSP enabled setup.

### ISSUE THREAD

**Issue by sangeethah** [rancher/qa-tasks#62]
Currently the test container  used in automation runs for validating clusters is built from "nginx" image.

`nginx` container does not deploy successfully on a cluster with "Pod Security Policy" set to "restricted".
Pod gets deployed and then gets into a crash loop with following error messages in the logs:

```
2020/04/23 20:11:05 [emerg] 1#1: chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)
nginx: [emerg] chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)
```

Need to find an alternate way to build a test container that can be used for automation runs.

**Comment by rancher-max** [comment]
We have `maxross/mytestcontainer:unprivileged` available now for use on PSP enabled setups. The main notable differences between this image and our default (`sangeetha/mytestcontainer`) is that this image does not run as root and uses port 8080.

We still need to move both of these images, and all images from our test quay.io registry to a rancher repo to be consolidated.

**Comment by bmdepesa** [comment]
@rancher-max Can you check in the dockerfile for the hardened image into the rancher/rancher tests repo? 

We have a repo we will be pushing all of our test images into.

**Comment by bmdepesa** [comment]
Closing this as part of #74
