### ISSUE TITLE
Harden 1.25 k8s clusters - RKE1

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#632]
- [x] Harden a ~standalone~ RKE1 cluster
- [x] Harden a standalone RKE2 cluster
- [x] Harden a standalone k3s cluster

**Comment by slickwarren** [comment]
rke2/k3s is done here: https://github.com/rancher/qa-tasks/issues/865

rke1 will be tracked in this ticket. It is more challenging, as the GO framework doesn't currently cover any rke1 hardening.

**Comment by slickwarren** [comment]
this is causing `rancher-v3_ontag_import_certification` to fail due to psact being too strict (From the onTag jobs)

**Comment by markusewalker** [comment]
Merged.
