### ISSUE TITLE
8.7 OS checks 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#636]
**On 2.6-head Rancher**

|  OS | Private AMI  | Public AMI  | User | 
|---|---|---|---|
| Rhel 8.7    | ami-04b3a750f270100c9  | ami-0dc59081aa519f50f  | ec2-user |
|  Oracle Linux 8.7 |  ami-0c72b415e5615f2e3 | ami-054a49e0c0c7fce5c | cloud-user / ec2-user  |
| Rocky Linux 8.7  | ami-09865b872d2572259 | ami-093fce7707cfd5839 | rocky |

```
Note:
- For custom clusters use Private AMIs 
- For Node drivers, use Public AMIs
- Deploy Downstream using latest 1.24 available
- Deploy local clusters using 1.24 k8s version
- To validate:
- - Deploy downstream clusters
- - Run validation checks on the clusters using Jenkins --> -k "test_wl or test_connectivity or test_ingress or test_service_discovery or test_websocket"
```

---

- [X] Downstream cluster checks

| OS and version  | Downstream Cluster Type  | Status  | Assignee  |
|---|---|---|---|
| Rhel 8.7  | RKE1 Custom  | **PASS** | **Vivek** |
| Rhel 8.7  | RKE1 Node Driver  | N/A  |  - |
| Rhel 8.7  | RKE2 Custom  | **PASS** | **Vivek** |
| Rhel 8.7  | RKE2 Node Driver  | N/A  |  - |
| Oracle Linux 8.7  | RKE1 Custom  | **PASS** | **Vivek**|
| Oracle Linux 8.7  | RKE1 Node Driver  | N/A | - |
| Oracle Linux 8.7  | RKE2 Custom  | **PASS** | **Vivek** |
| Rocky Linux 8.7  | RKE1 Custom  | **PASS** | **Vivek** |
| Rocky Linux 8.7  | RKE1 Node Driver  | N/A | - |
| Rocky Linux 8.7  | RKE2 Custom  | **PASS** | **Vivek** |

- [x] Rancher local cluster checks

| OS and version  | Downstream Cluster Type  | Status  | Assignee  |
|---|---|---|---|
| Rhel 8.7  | RKE1 Imported   | **PASS** | **Vivek**|
| Oracle Linux 8.7  | RKE1 imported  | **PASS** | **Vivek**|
| Rocky Linux 8.7  | RKE1 Imported   | **PASS** | **Vivek**|

- [x] Chart validations - https://github.com/rancher/qa-tasks/issues/549

**Comment by vivek-shilimkar** [comment]
Since OS checks and chart validations passed, closing this issue.
