### ISSUE TITLE
Support Matrix checks - OS 8.7 Certification - Chart validations

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#637]
**New OSes for Q1 release**

RHEL 8.7
Rocky 8.7
OL 8.7

**Comment by rishabhmsra** [comment]
Below chart validations were successful on all the mentioned OSes, hence closing the issue:



Chart | Oracle 8.7 | Rhel 8.7 | Rocky 8.7
-- | -- | -- | -- 
Alerting Drivers | PASS | PASS | PASS 
CIS | PASS | PASS | PASS 
Fleet | PASS | PASS | PASS 
Istio | PASS | PASS | PASS 
Logging | PASS | PASS | PASS 
Monitoring | PASS | PASS | PASS 
OPA-Gatekeeper | PASS | PASS | PASS 
Prometheus-Federator | PASS | PASS | PASS 
rancher backups | PASS | PASS | PASS
