### ISSUE TITLE
Automated reporting on open PRs.

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#640]
The automated reporting will highlight PRs open past the agreed-upon timeframe, including notification to the team

**Comment by bmdepesa** [comment]
Potentially look at https://github.com/rancher/qa-tasks/issues/84 as a base for this

Criteria
- Stale PRs
  - PRs that are open for more than 1 week (?? tbd)
- Separate sections for 
  - PRs that haven't been reviewed (review required)
  - PRs that have requested changes but no updates (changes requested)
  - PRs that have reviews but aren't merged (approved review)
- Limit to PRs that have specific labels
  - Anything around automation (probably needs some communication / work with managers around required labels when creating PRs)

Look into a github bot for stale issues, etc..

**Comment by sowmyav27** [comment]
Done. Should send a notification every week in slack channel.
