### ISSUE TITLE
Hosted clusters Support matrix checks

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#641]
**On latest 2.6 RC or 2.6-head**

| Local cluster Type  | Local cluster k8s version  | Downstream Cluster type  | Downstream cluster k8s version  | Rancher version  | Status  | Assignee  |
|---|---|---|---|---|---|---|
| AKS  |  v1.24.9 | AKS  | 1.24.9  | v2.6-head(f3f9e47)  | Pass  | Rishabh  |
| GKE  | v1.24.10-gke.1200(rancher server v2.6-head(2e43de8))  | GKE  | 1.24.10-gke.1200 | v2.6-head(f3f9e47) | Pass | Rishabh |
| EKS  |  1.24  | EKS  | 1.24 | v2.6-head(f3f9e47) | Pass | Rishabh |

**Comment by vivek-shilimkar** [comment]
Downstream AKS hosted cluster creation fails due to [this issue](https://github.com/rancher/rancher/issues/40916).

**Comment by vivek-shilimkar** [comment]
For AKS k8s v1.24.10 is not supported in most of the US regions that I checked. Following are the supported k8s versions.
```
KubernetesVersion    Upgrades
-------------------  -----------------------
| 1.26.0(preview)   |   None available |
1.25.5               1.26.0(preview)
1.25.4               1.25.5, 1.26.0(preview)
1.24.9               1.25.4, 1.25.5
1.24.6               1.24.9, 1.25.4, 1.25.5
1.23.15              1.24.6, 1.24.9
1.23.12              1.23.15, 1.24.6, 1.24.9
```

**Comment by vivek-shilimkar** [comment]
As per discussion on slack, the failures observed in downstream hosted AKS cluster are expected.
Hence, the [issue is logged](https://github.com/rancher/qa-tasks/issues/657) for updating those tests and fix them.

Along with the expected issues with the hosted AKS cluster rest tests passed. Hence closing the issue.
