### ISSUE TITLE
Create test bin or Run dummy validation tests

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#646]
- Building a binary could catch breaking changes faster OR
- Run a dummy gotest  with all tests to catch breaking changes & get an updated test count

**Comment by caliskanugur** [comment]
As a temporary solution for this, as we spoke, we can add a step in the Jenkinsfile. Every PR already needs its Jenkins freeform runs, that way we can eliminate build issues meantime.

**Comment by caliskanugur** [comment]
Recurring runs made this possible out of the box, closing in favor of recurring runs
