### ISSUE TITLE
Monitoring Test Update with 102.0.02+40.1.2

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#647]
Monitoring Automation P0 requires an update specifically for the alert structure serializing part. The current alert structure won't support this.

**Comment by bmdepesa** [comment]
Needs investigation to see what is actually broken

Test will fail if run for the newest versions of monitoring/alerting charts.

**Comment by bmdepesa** [comment]
Start by running the test against the latest (should fail) and `102.0.0+up40.1.2` (should pass) versions of monitoring. 

Try to debug where the test is failing 

Follow up with @caliskanugur on a potential fix.
