### ISSUE TITLE
Validate downstream webhook P0 cases on a windows clusters

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#648]
**Fresh install:**
1. Install rancher 2.7-head
2. As a standard user create a Windows RKE2 cluster (Make Note of -  windows cluster config, and rke2 version and cluster type)
3. Verify on the downstream cluster >> Namespace - cattle-system `rancher-webhook` and version `v0.3.2-rc21` gets installed and is active.
4. Create a project P1  --> and create a namespace ns1.
    - From `Pod Security Admission` tab, enable PSA `Enforce` and set it `restricted`
    - Create a deployment in the namespace ns1, and verify the workload deployment fails.

**Upgrade:**
1. On 2.7.0, As a standard user create a Windows RKE2 cluster (Make Note of -  windows cluster config, and rke2 version and cluster type). 
2. As a standard user create a Windows RKE2 cluster (Make Note of -  windows cluster config, and rke2 version and cluster type)
3. Verify that on downstream cluster --> System project page --> There is no workload/pod related to webhook.
4. Upgrade to rancher 2.7-head
5. Verify on the downstream cluster >> Namespace - cattle-system `rancher-webhook` and version `v0.3.2-rc21` gets installed and is active.
6. Create a project P1  --> and create a namespace ns1.
    - From `Pod Security Admission` tab, enable PSA `Enforce` and set it `restricted`
    - Create a deployment in the namespace ns1, and verify the workload deployment fails.

**Comment by slickwarren** [comment]
**Fresh install (tested on v2.7-head - 2b2ed44) :**


1. Install rancher 2.7-head
2. As a standard user create a Windows RKE2 cluster (rke 1.25.7+rke2r1, 1etcd, 1cp, 2 linux workers, 1 windows worker) -- pass 
3. Verify on the downstream cluster >> Namespace - cattle-system `rancher-webhook` and version `v0.3.2-rc22` gets installed and is active -- pass
4. Create a project P1  --> and create a namespace ns1 -- pass
    - From `Pod Security Admission` tab, enable PSA `Enforce` and set it `restricted`
    - Create a deployment in the namespace ns1, and verify the workload deployment cannot deploy -- pass


**Upgrade:**
1. On 2.7.0, As a standard user create a Windows RKE2 cluster 
2. As a standard user create a Windows RKE2 cluster v1.24.10+rke2r1, 1etcd, 1cp, 2 linux workers, 1 windows worker -- pass
3. Verify that on downstream cluster --> System project page --> There is no workload/pod related to webhook. -- pass
4. Upgrade to rancher 2.7-head
5. Verify on the downstream cluster >> Namespace - cattle-system `rancher-webhook` and version `v0.3.2-rc22` gets installed and is active. -- pass
6. Create a project P1  --> and create a namespace ns1 -- pass
    - From `Pod Security Admission` tab, enable PSA `Enforce` and set it `restricted`
    - Create a deployment in the namespace ns1, and verify the workload deployment cannot deploy -- pass
