### ISSUE TITLE
Validate downstream webhook P0 cases on a hosted rancher 

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#649]
**Fresh install:**
1. Install rancher 2.7-head
2. Create a hosted rancher 
3. Verify on the downstream cluster/tenant/hosted rancher server >> Namespace - cattle-system `rancher-webhook` and version `v0.3.2-rc21` gets installed and is active.
4. Create a project P1  --> and create a namespace ns1 in the downstream cluster.
    - From `Pod Security Admission` tab, enable PSA `Enforce` and set it `restricted`
    - Create a deployment in the namespace ns1, and verify the workload deployment fails.

**Upgrade:**
1. On 2.7.0, Create a hosted rancher server 
2. Verify that on downstream cluster --> System project page --> There is no workload/pod related to webhook.
3. Create a hosted rancher setup.
4. Upgrade to rancher 2.7-head
5. Verify on the downstream cluster >> Namespace - cattle-system `rancher-webhook` and version `v0.3.2-rc21` gets installed and is active.
6. Create a project P1  --> and create a namespace ns1 as a cluster owner
    - From `Pod Security Admission` tab, enable PSA `Enforce` and set it `restricted`
    - Create a deployment in the namespace ns1, and verify the workload deployment fails.

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment



| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-a841a9e101ae601a033fa8b39342ad4800c91d85-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/a841a9e101ae601a033fa8b39342ad4800c91d85 |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.23.6+k3s1                                                                       |
| Cert Details                     | Let's Encrypt / `traefik`                                                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.11.1                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | RKE1 Linode                                                                        |
| Downstream K8s version           | v1.25.6                                                                            |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin, standard user                                                               |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | 110.0.5481.177 (Official Build) (x86_64)                                           |

<details>
    <summary>🚨 Additional Validation Setup Details: Click to Expand</summary>

Host / Tenant setup with this Terraform: https://github.com/brudnak/hosted-tenant-rancher

</details>

## Validation steps

#### Fresh install

1. Create a hosted/tenant setup with https://github.com/brudnak/hosted-tenant-rancher on 2.7-head
2. Verify on the tenant --> Namespace - cattle-system rancher-webhook and version v0.3.2-rc21 gets installed and is active
3. Verify on the host --> Namespace - cattle-system rancher-webhook and version v0.3.2-rc21 gets installed and is active
4. Create a downstream on host, then verify --> Namespace - cattle-system rancher-webhook and version v0.3.2-rc21 gets installed and is active
5. Create a downstream on tenant, then verify --> Namespace - cattle-system rancher-webhook and version v0.3.2-rc21 gets installed and is active
   - Create a project P1 --> and create a namespace ns1 in the cluster
   - From Pod Security Admission tab, enable PSA Enforce and set it restricted
   - Create a deployment in the namespace ns1, and verify the workload deployment fails

#### Upgrade

On 2.7.0, Create a hosted rancher server
Verify that on downstream cluster --> System project page --> There is no workload/pod related to webhook.
Create a hosted rancher setup.
Upgrade to rancher 2.7-head
Verify on the downstream cluster >> Namespace - cattle-system rancher-webhook and version v0.3.2-rc21 gets installed and is active.
Create a project P1 --> and create a namespace ns1 as a cluster owner
From Pod Security Admission tab, enable PSA Enforce and set it restricted
Create a deployment in the namespace ns1, and verify the workload deployment fails.

## Additional Info

## RESULTS

#### ✅ Expected

For fresh install and upgrade checks to be passing

#### ✅ Actual

Fresh install and upgrade checks passed. For upgrade v0.3.2-rc21 gets installed and workload deploys with the specs above fail as expected
