### ISSUE TITLE
Investigate automation solutions for performance / scaling environments

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#655]
Is the rancher2-scaling framework the most appropriate location for our infrastructure/environment automation for general purpose performance testing for Rancher local and downstream clusters? 

How do we want to / should we integrate environment creation and test validations / checks with our existing Go test framework or other tools? 

Should we switch to using Corral for our general purpose environment creation? May be able to use the corral client in Go test framework.

If we use Corral - where are those packages stored?

**Comment by rancher-max** [comment]
Closing as this has effectively been done and we are using rancher/dartboard for this.
