### ISSUE TITLE
[Epic] Create automation to load an environment with a large number of resources to test performance

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#656]
- Configmaps
- Secrets
- Workloads
- ???

This list needs to be expanded upon.

Where should these scripts / automation be stored?

https://github.com/rancher/rancher2-scaling/pull/63

**Comment by bmdepesa** [comment]
#683, #684  is a part of this

**Comment by rancher-max** [comment]
This is possible with dartboard today
