### ISSUE TITLE
Update existing network checks for pre and post upgrade for AKS clusters

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/qa-tasks#657]
Issue: Currently there are expected failures in the network checks for AKS clusters as there are known differences with AKS cluster network configurations. In past releases qa team has been taking a mental note of these failures and ignoring when we hit these failures.

Fix: We should add a condition to parts of the network checks to bypass these checks when AKS clusters are being run against.

**Comment by slickwarren** [comment]
related issues and information: 
* issue is for job rancher-v3_needs_cluster
* the test has some false positives that we need to add some logic not to test for the aforementioned use cases.
* https://github.com/rancher/rancher/issues/39926
```
Downstream EKS -> Ingress checks are failing because there is no ingress-controller present (unlike RKE1 where nginx-ingress-controller is available). Also nodePort checks are failing as it is not able to get the publicEndpoints as per below logs. A similar [issue](https://github.com/rancher/rancher/issues/39926) is logged for it. Here's the jenkins [build](https://jenkins.int.rancher.io/job/rancher_qa/job/rancher-v3_needs_cluster/582/) for the rest of the passed tests.
common.py:809: in get_endpoint_url_for_workload
    url = url + workload.publicEndpoints[0]["addresses"][0] + ":"
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = {'allNodes': True, 'ingressId': None, 'nodeId': None, 'podId': None, 'port': 30457, 'protocol': 'TCP', 'serviceId': 'test-99841:test-node-port-scale-upgrade-98098-nodeport'}
key = 'addresses'

    def __getitem__(self, key):
>       return self.__dict__[key]
E       KeyError: 'addresses'
Downstream AKS -> In this also ingress checks and nodePort checks are failing because of the same reasons as listed above. Here's the jenkins [build](https://jenkins.int.rancher.io/job/rancher_qa/job/rancher-v3_needs_cluster/583/) for network checks. Also Public IP is not getting assigned to worker nodes.
```

**Comment by thaneunsoo** [comment]
I see in our aks test we have ingress checks removed already
https://github.com/rancher/rancher/blob/release/v2.8/tests/validation/tests/v3_api/test_aks_v2_hosted_cluster.py#L122

For the needs_cluster test all we need to do is remove `test_ingress` it seems when testing aks clusters with this job
```
-k "test_bkp or test_wl or test_dns_record or test_rbac or test_connectivity or test_ingress or test_secrets or test_registry or test_service_discovery or test_websocket"
```
