### ISSUE TITLE
Automate manual upgrades in rke2

### ISSUE THREAD

**Issue by rancher-max** [rancher/qa-tasks#658]
Currently we have SUC upgrades automated in rke2 and available in Jenkins. We should do the same for Manual upgrades.

**Comment by bguzman-3pillar** [comment]
This test is completely automated. 
PR -> https://github.com/rancher/rke2/pull/4118

**Comment by rancher-max** [comment]
We just need a jenkins job for k3s and rke2 now and then we can call close this issue
