### ISSUE TITLE
Add provisioning test case to delete an etcd node in a Node Driver cluster and validate cluster comes back up `Active`

### ISSUE THREAD

**Issue by markusewalker** [rancher/qa-tasks#660]
### Issue Description
Currently in the Go framework, we do not have a test that checks to see the behavior of deleting an etcd node in a node driver cluster. Manually doing this, when deleting an etcd node, the node should be removed, a new node replaces it. When the new node finally gets to an `Active` state, the cluster should be `Active` again as well.

We should automate this use-case to ensure that we're regularly covering this test case. This will cover RKE1, RKE2 and K3S.

**Comment by rishabhmsra** [comment]
PR is merged, hence closing the issue.
