### ISSUE TITLE
validate multiple windows nodes in a vsphere node driver. cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#666]
validate multiple windows nodes in a vsphere node driver. cluster - this was not working fro me but i may have been using an out of date template

**Comment by jameson-mcghee** [comment]
I was able to spin up a vSphere Node Driver cluster with multiple windows nodes on `v2.6-head` and `v2.7.2-rc8` without issue. Therefore I am closing this issue.

**Comment by sowmyav27** [comment]
@jameson-mcghee could you please add these info to the ticket before closing? 

- RKE2 version
- Cluster config
- Did you check if all System project page workloads are up and Active? 
- 2.6-head commit id

**Comment by jameson-mcghee** [comment]
- RKE2 versions:
  - v1.25.8+rke2r1
  - v1.24.12+rke2r1
- Cluster config:
  - 3 Linux All Roles and 2 Windows workers
  - 3 Linux etcd, 2 Linux Control Plane, 1 Linux worker, 2 Windows workers
- Confirmed that all System workloads and Pods were up and _Active_
- 2.6-head (Commit ID: 8998506)
