### ISSUE TITLE
[Automation] Delete k3s clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#669]
### Custom Clusters
- [ ] Deleting clusters - Custom
- Create a custom k3s clusters
- Delete cluster
- Verify cluster is removed from Rancher
- Verify nodes are NOT deleted in backend

### Node Driver clusters
- [ ] Delete AWS Node driver clusters
- - Create a Node driver k3s AWS cluster 
- - Delete cluster
- - Verify cluster is removed/deleted from Rancher
- - Verify nodes are also deleted in backend
- [ ] Delete Azure Node driver clusters
- - Create a Node driver k3s Azure cluster 
- - Delete cluster
- - Verify cluster is removed/deleted from Rancher
- - Verify nodes are also deleted in backend

**Comment by markusewalker** [comment]
Discussed offline further with the team regarding implementation of this. I will have something up for RKE1/RKE2/K3S in one PR for this task.

**Comment by markusewalker** [comment]
I have a local fix for this. Awaiting for several other PRs to be merged before opening a PR for this task.

**Comment by markusewalker** [comment]
v2.7 PR: https://github.com/rancher/rancher/pull/41846
v2.8 PR: https://github.com/rancher/rancher/pull/42515

**Comment by markusewalker** [comment]
Merged.
