### ISSUE TITLE
onTag automation job failure due to misconfigured bootstrap password  - [KeyError: 'token']

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/qa-tasks#682]
Our onTag automation job is currently failing with a `404 - unauthorized` error related to the bootstrap password being misconfigured.  This ticket was created to address and track the progress and resolution of this error.

To reproduce, spin off an onTag job (internally) with Rancher `v2.7.2-rc9`.

**Comment by Josh-Diamond** [comment]
Update:

this issue is no longer seen when changing the default branch from `release/v2.6` to `release/v2.7`.

**Comment by Josh-Diamond** [comment]
In addition to the failures related to `release/v2.6` branch (which were resolved by using `release/v2.7` branch,
the following failures were seen with our automation:

- AKS - no ssh key found
- EKS - cluster object is created but no node groups are created or added; test eventually times out and fails waiting for cluster to be in an `active` state after ~20m, while cluster is really `waiting for API to be available` but no nodes or node groups are seen/created

**Comment by markusewalker** [comment]
Closing this issue in favor of https://github.com/rancher/qa-tasks/issues/429.
