### ISSUE TITLE
[scale-testing] Test Rancher performance when there are large #s of shutdown clusters

### ISSUE THREAD

**Issue by git-ival** [rancher/qa-tasks#685]
Goal: Get Rancher to trigger a restart due to resource issues (ex: OOM error) by having increasing #s of shutdown clusters.

General Process:
1. Set up a Local cluster with `rancher-monitoring`
   - Ensure `CATTLE_PROMETHEUS_METRICS` is set to "`true"`
2. Import 26 downstream clusters
   - Ensure Rancher will not auto-provision new nodes if/when the cluster nodes are shutdown
3. Shut down 25 clusters
4. Monitor Rancher's resource utilization for any issues or restarts
5. If no restart was triggered due to resource utilization issues then:
   1. Provision 5 more clusters
   2. Shutdown 5 clusters at a time
   3. Monitor Rancher's resource utilization for any issues or restarts
   4. Repeat until a restart occurs due to resource utilization issues

See https://github.com/rancher/rancher/issues/27676#issuecomment-1503897290 for additional details

**Comment by bmdepesa** [comment]
Waiting on dev?

**Comment by git-ival** [comment]
Waiting on customer env profiles, closing as done. This can be reopened at a later date if needed
