### ISSUE TITLE
Support Matrix checks - OS 9 and SLE 15 SP5 Certification - Chart validations

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#689]
New OSes for Q2 release

- RHEL 9
- Rocky 9
- SLE 15 SP5

**Comment by vivek-shilimkar** [comment]
Below chart validations were successful on RHEL9 as of now.

Chart | Rhel 9 | 
-- | -- | 
Alerting Drivers |  |  
CIS | PASS |  
Fleet |  | 
Istio | PASS |  
Logging |  |  
Monitoring | PASS |  
OPA-Gatekeeper | PASS |  
Prometheus-Federator |  | 
rancher backups |  |

**Comment by rishabhmsra** [comment]
Charts validation on Rocky 9 and RHEL 9 :

Chart | Rocky 9 (RKE1) | RHEL 9 (RKE1) | SLES 15 SP5 (RKE2)
-- | -- | -- | -- |
Alerting Drivers | PASS | PASS | PASS
CIS | PASS | PASS | PASS
Fleet | PASS | PASS | PASS
Istio | PASS | PASS | PASS
Logging | PASS | PASS | PASS
Monitoring | PASS | PASS | PASS
OPA-Gatekeeper | PASS | PASS | PASS
Prometheus-Federator | PASS | PASS | PASS
rancher backups | PASS | PASS | PASS

**Comment by rishabhmsra** [comment]
All chart validations are completed on all OSes, hence closing the issue.
