### ISSUE TITLE
v2.6.12 Performance / Scaling Checks

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#691]
### Rancher Cluster Config:
Rancher version: latest 2.6.12rc
Rancher cluster type: RKE1 HA  (3 all-roles nodes, 1 worker node tainted to run rancher-monitoring)
Cluster Size: Medium
Docker version: 20.10
K8s version: v1.24.10-rancher4-1
Log level: debug
certmanager version: 1.11.0

### Downstream Cluster Config:
Downstream cluster types: RKE1, RKE2, K3s (3 all-roles nodes)
Installed apps: N/A
Deployments: `ranchertest/mytestcontainer`
rke1 version = 1.24.x (use latest supported)
rke2 version = 1.24.x (use latest supported)
k3s version  = 1.24.x (use latest supported)

### Method:
1. Setup HA Local 1.24 cluster with Rancher
	1. Install monitoring
	2. Install other workloads/Apps if desired (SKIPPED)
2. Provision Downstream 1.24 clusters (1 of each RKE1, RKE2, K3s)
3. Load each downstream cluster with a set of "objects"
	1. 100 secrets
	2. 10 projects
	3. 12 namespaces
	4. 300 users (users are created in the Local cluster)
	5. 1 project Role Template
	6. 300 project Role Template bindings
4. Deploy desired pods onto each downstream cluster
	1. Deploy `ranchertest/mytestcontainer` until reaching 330 pod limit
	2. Collect CPU and Memory profile logs as scale-in progresses
	3. Collect rancher pod logs as scale-in progresses
5. Collect rancher-monitoring metrics artifacts

### Rancher Cluster Config:
Rancher version: 
Rancher cluster type: RKE1 HA , 3 all-roles nodes, 1 worker node (tainted to run rancher-monitoring)
Cluster Size: Medium
Docker version: 20.10
K8s version: v1.24.10-rancher4-1
Log level: debug
certmanager version: 1.11.0

### Downstream Cluster Config:
Downstream cluster types: Imported K3s
Installed apps: N/A
Deployments: N/A
k3s version = 1.24.x (use latest supported)

### Method:
1. Setup HA Local 1.24 cluster with Rancher
	1. Install monitoring
	2. Install other workloads/Apps if desired (SKIPPED)
2. Let idle for 30 minutes
3. Provision Downstream 1.24 clusters (Imported K3s)
   - Scale to half the documented cluster limit
4. Collect rancher-monitoring metrics artifacts and review for unexpected behavior
5. Provision Downstream 1.24 clusters (Imported K3s)
   - Scale to the full documented cluster limit
6. Collect rancher-monitoring metrics artifacts and review for unexpected behavior

**Comment by git-ival** [comment]
Added details of the configuration and test method
