### ISSUE TITLE
[LLE] Analysis of long living environments

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#692]
Refer to confluence planning page

- Analysis of current environment
- Document terminology / plans
- Actions needed to bring environment up to date
- Future tasks to utilize this environment
- Determine where supporting TF code should live

**Comment by bmdepesa** [comment]
Break this out into individuals tasks

**Comment by git-ival** [comment]
Code will live in `dartboard` when there is any relevant code to contribute for LLE-specific purposes.

LLE documentation is in Confluence and upgrade scenarios have been passed along to Bullseye QA.

Created some tasks to automate the various LLE upgrade scenarios (bottom-up approach)
