### ISSUE TITLE
[UI] Determine how to get tests added to UI GH actions

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#696]
For tests that don't require real infrastructure and can be run in GH actions with the existing UI automation tests, determine what the process is for merging and enabling those to run.

**Comment by bmdepesa** [comment]
Open questions -- 
* Does this happen automatically?  
* How do we tag tests that shouldn't be run?
* GH actions run tests as an admin user -- can we or should we modify or add to this workflow to use a standard user?

**Comment by yonasberhe23** [comment]
**Yonas will sync up with Richard and Nancy on 5/18 to go through below items**

1. Does this happen automatically? 

- After commit is made full suite of tests are run in GA including the added test in the PR.

2. How do we tag tests that shouldn't be run?

- Add tag to tests that are specific to admin or standard user or both - https://www.browserstack.com/guide/cypress-tag-tests

3. GH actions run tests as an admin user -- can we or should we modify or add to this workflow to use a standard user? 

- Add to this workflow. e.g. before tests run for standard user, create standard user via api, sign in with that user, do the test, and then tear down at the end. We have api hooks that can do this.

**Comment by yonasberhe23** [comment]
**Notes following 5/18 meeting**

1. Does this happen automatically? 

- ./cypress.config.ts file specifies paths to look for spec files (see getSpecPattern ).
- the getSpecPattern method grabs tests under these two paths and executes them in GA. These two paths contain all of the e2e tests thus far. So tests are added to GA automatically in this way however if tests are added to a path outside of this, the path will need to be added to ./cypress.config.ts to ensure they run in GA.
  - cypress/e2e/tests/pages/**/*.spec.ts
  - cypress/e2e/tests/navigation/**/*.spec.ts
  
2. How do we tag tests that shouldn't be run? 

- Richard believes we might be able set up what tests to run in cypress.config.ts file: (see getSpecPattern to check how to run a group of specs). Yonas to look into this. 

3. GH actions run tests as an admin user -- can we or should we modify or add to this workflow to use a standard user? 

- Going to add standard user to workflow.
- Whenever we run e2e tests a standard user will be created. 
- Create a cypress command that makes api requests to create user in commands file and store the users credentials somewhere to access their account later.
- Order of operations: Login as admin user, create standard user, run admin test, logout and login as standard user, run standard user tests, then tear down

**Comment by yonasberhe23** [comment]
pr for adding standard user to workflow https://github.com/rancher/dashboard/pull/9029

**Comment by bmdepesa** [comment]
Let's make sure this process for defining tags and which tags are run in GH actions are documented in Confluence before closing this.

**Comment by yonasberhe23** [comment]
PR merged https://github.com/rancher/dashboard/pull/9029 and documented in Grouping+tests+in+Cypress
