### ISSUE TITLE
[UI] Create Jenkins jobs for running UI tests which require real infrastructure

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#697]
- Jenkins job for running tests against an existing Rancher server
- Jenkins job for deploying Rancher and running tests

Things to keep in mind: 
* Do we run this headless? 
* What browsers will we support for this automation? 
* How do we tag these tests so they do not run in the UI GH actions runner?  
* Do we also want to run the existing tests here for a consolidated report?

**Comment by bmdepesa** [comment]
https://github.com/rancher/dashboard/pull/9432

**Comment by izaac** [comment]
https://github.com/rancherlabs/corral-packages/pull/19
https://github.com/rancher/dashboard/pull/9726
