### ISSUE TITLE
[UI] Define process for PR reviews/merging

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#703]
Who should review and merge UI tests? 
What does this process look like?

**Comment by yonasberhe23** [comment]
1. Who should review and merge UI tests? 

- Nancy and Richard are reviewers of UI automation PRs. Plans is to open it up for more reviewers once people get up to speed.

2. What does this process look like? 

- Create a PR and assign reviewers and add a milestone. 
- Ping the reviewers directly on slack to get the pr on their radar/start discussion. 
- Reviewer gives feedback/change requests.
- Make changes based on those requests (if I have questions about the review/change request I usually set up a meeting)
- Once PR is approved and all checks have passed, merge the PR in

**Comment by bmdepesa** [comment]
To discuss on 5/18

**Comment by yonasberhe23** [comment]
Discussed with Nancy and Richard. Going to keep the same process going as described in my previous comment.
