### ISSUE TITLE
[UI] Create backlog items for UI automation

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#704]
Create backlog items for the rest of the automation items for the "UI P0 Regression Test Cases" from Confluence.

**Comment by bmdepesa** [comment]
Created a column in UI+P0+Regression+Test+Cases doc to list the issues for easier tracking. Once all issues have tasks, we can close this out.

**Comment by yonasberhe23** [comment]
All issues have tasks - see  UI+P0+Regression+Test+Cases doc
