### ISSUE TITLE
`etcd_backup_restore_test.go` does not have error checking for when pods fail or go into a crashloop state

### ISSUE THREAD

**Issue by markusewalker** [rancher/qa-tasks#717]
### Issue Description
Recently, we found an [issue](https://github.com/rancher/rancher/issues/41174) pertaining to etcd snapshot/restore causing pods to be stuck in a status of crashloop. From further testing, it seems that this is specifically occurring on Rancher 2.7.2+ and with RKE2/K3S upgrading from v1.24.x+rke2r1 -> v1.25.x+rke2r1.

Using the `etcd_backup_restore_test.go` file with the above configuration, I reproduced this issue. However, how the pod status check is currently implemented, instead of erroring out when a pod is in any state but `Active`, the test simply hangs. This is not expected behavior, the test should fail then and there and illustrate why.

The test uses function `watchAndWaitForPods`, which lacks error checking. We have a similar function, `StatusPods`, which does include error checking for such scenarios that possibly can be used. The test needs to be updated to have error checking so our automation catches these types of issues.

**Comment by rishabhmsra** [comment]
PR with fix is merged, hence closing this issue.
