### ISSUE TITLE
[Automation] Support Matrix checks - Automate RKE1 checks

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#724]
We do these checks on an RKE1 cluster and update the support matrix with certain image versions for every Rancher release. This is done manually. We must automate this.

Support matrix - https://www.suse.com/suse-rke1/support-matrix/all-supported-versions/rke1-v1-25/

Checks that are currently being done manually include version checks for 

- etcd - `etcdctl version`
- flannel - _when determining the Flannel version, we should look at the image for "flannel", not "canalFlannel"_
- canal
- nginx-ingress-controller

This task is to automate
- [x] deploying RKE1 clusters for all supported k8s versions (for flannel version we might have to deploy a flannel CNI cluster - pls test and confirm)
- [x] Listing the versions for the above mentioned images ^

**Comment by markusewalker** [comment]
PR: https://github.com/rancher/rancher/pull/41644

**Comment by markusewalker** [comment]
Installed.
