### ISSUE TITLE
[Truncate Hostname Feature] - Backup and Restore testing

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/qa-tasks#728]
There is a new feature coming out to truncate rke2 hostnames to 15 characters or less to be in compliance with the NetBIOS policy. Test plan and overview of feature components will be given internally but this ticket is to track backup and restore testing by team 3.

**Comment by nickwsuse** [comment]
Ticket: https://github.com/rancher/rancher/issues/40901
PR: https://github.com/rancher/rancher/pull/41201

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head 95edd02`

Installed rancher-backups
Took backup with encryption
Successfully restored with encryptuion
