### ISSUE TITLE
[UI] Cluster Provisioning: Provision RKE2 custom cluster

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/qa-tasks#749]

**Comment by yonasberhe23** [comment]
I believe there is existing UI automation for this feature: `cypress/e2e/tests/pages/manager/agent-configuration-rke2.spec.ts`. @izaac please confirm

**Comment by izaac** [comment]
Depends on the scope of this issue. The RKE2 cluster created by the framework only creates the Cluster object but doesn't add the nodes to it and/or wait to be active.

Could we confirm if the current test is enough?

**Comment by yonasberhe23** [comment]
You are correct. The extent of the test is hitting create and waiting for a 201 status code so I'll keep this issue open
