### ISSUE TITLE
[Automation] Delete/Add nodes in a Custom k3s cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#770]
1. Add worker nodes
- Create custom k3s cluster - 1etcd, 1 cp and 1 worker nodes
- Add a worker node
- verify the cluster state goes to updating and comes back up Active
- Verify the additional worker node is in Active state
- Verify the node is added successfully, a daemonset scales to this worker node also

2. Add a control plane node
- Create custom k3s cluster - 1etcd, 1 cp and 1 worker nodes
- Add one control plane node
- verify the cluster state goes to updating and comes back up Active
- Verify the additional control plane node is in Active state

3. Add two etcd nodes
- Create custom k3s cluster - 1etcd, 1 cp and 1 worker nodes
- Add _two_ etcd nodes
- verify the cluster state goes to updating and comes back up Active
- Verify the two additional etcd nodes are in Active state

4. Delete a worker node
- Create custom k3s cluster - 1etcd, 1 cp and 2 worker nodes
- Delete a worker node
- verify the cluster state goes to updating and comes back up Active
- Verify the cluster has only 1 worker node now
- Verify an existing daemonset scales down to 1

5. Delete control plane node
- Create custom k3s cluster - 1etcd, 2 cp and 2 worker nodes
- Delete a control plane node
- verify the cluster state goes to updating and comes back up Active
- Verify the cluster has only 1 control plane node

**Comment by markusewalker** [comment]
Closing in favor of https://github.com/rancher/qa-tasks/issues/459.
