### ISSUE TITLE
Remove hardcoded `kwait` parameters -> add good go-to `consts` to use in kwait functions

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#777]
currently, we have ambiguous numbers in all kwait functions. It would be great to have more meaningful values for minutes / how long to wait, so that at a glance someone looking at the code can guess why we are waiting as long for a given kwait function.

**Comment by igomez06** [comment]
This task should also include identifying the same polls used multiple times and abstracted them out as extensions.

**Comment by slickwarren** [comment]
There are now default values in framework/extensions/default  however I don't think existing tests were switched to using this.

**Comment by markusewalker** [comment]
This is being handled as a need to basis. In other words, there won't be one giant PR that addresses, but PRs that touch individual `kwait` will fix this over time. Closing issue.
