### ISSUE TITLE
Validate GRB, PRTB, CRTB on User removal

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/qa-tasks#781]
Implement automation tests on below use cases when user removed from a Downstream Cluster/ Project namespace OR delete from entire users list:

Test Case | Test Steps | Check point
-- | -- | --
Delete rancher user from Cluster | 1. Provision Rancher <br>2. RKE1 cluster<br> 3. Add standard user to the Cluster <br> 4. Delete standard user from the Cluster.   | a. Make sure Cluster Role Bindings deleted `k get clusterroletemplatebindings -A`
Delete rancher user from Users list | 1. Provision Rancher <br>2. RKE1 cluster<br> 3. Add standard user to the cluster <br> 4. Delete standard user from the users list.   | a. Make sure Global role bindings and Cluster Role Bindings deleted <br> `k get globalrolebindings -A` <br> `k get clusterroletemplatebindings -A`
Delete rancher user from  Project /Project Name Space | 1. Provision Rancher<br>2. Add standard user to the Project Name Space <br> 3. Delete Standard User from Project Name Space | a. Make sure Project Role bindings deleted `k get projectroletemplatebindings -A`
Delete rancher user from  Users list. |1. Provision Rancher<br>2. Add standard user to the Project Name Space <br> 3. Delete Standard User from users list | a.  Make sure Global role bindings and Cluster Role Bindings deleted <br> `k get globalrolebindings -A` <br> `k get projectroletemplatebindings -A`

**Comment by Priyashetty17** [comment]
PR has been merged so closing this
