### ISSUE TITLE
[Automation] CIS scans

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#783]
Automated tests for CIS scans
- [ ] Identify Release checks
- [ ] Identify  P0 and P1 checks

**Comment by vivek-shilimkar** [comment]
Run the following checks on following types.

1. On different network providers. 
2. Single node and Multi node clusters.
3. Local hardened clusters

### P0 Checks for CIS Benchmark chart.
- Create a rke1/rke2/k3s non-harden/harden cluster (k8s v1.24-1.26).
- Wait for the cluster to be up and active.
- Install the CIS Benchmark chart from Apps and Marketplace.
- Create a scan depending on the type and version of the cluster.
- Verify all the scans pass.

**Comment by markusewalker** [comment]
This is outdated. Updated epic ticket https://github.com/rancher/qa-tasks/issues/1354 has PRs that will be merged very soon that addresses. As such, closing issue.
