### ISSUE TITLE
Add/Delete/Scale nodes in RKE2 node driver cluster 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#792]
1. Delete a worker node
- Create node driver RKE2 cluster - 1etcd, 1 cp and 2 worker nodes
- Delete a worker node
- Verify the node is deleted from cluster in Rancher and in backend
- Verify another node starts provisioning
- verify the cluster state goes to updating and comes back up Active
- Verify the cluster has 2 worker nodes and the additional worker node is Active.

2. Delete control plane node
- Create node driver RKE2 cluster - 1etcd, 2 cp and 2 worker nodes
- Delete a control plane node
- Verify the node is deleted from cluster in Rancher and in backend
- Verify another node starts provisioning
- verify the cluster state goes to updating and comes back up Active
- Verify the cluster has 2 control plane nodes nodes and the additional control plane node is Active.

3. `Scale down` worker node
- Create node driver RKE2 cluster - 1etcd, 1 cp and 2 worker nodes
- Select a node and`Scale Down` a worker node
- Verify the node is deleted from cluster in Rancher and in backend
- Verify another node does NOT start provisioning
- verify the cluster state goes to updating and comes back up Active
- Verify the cluster has 1 worker node

4. `Scale down` control plane node
- Create node driver RKE2 cluster - 1etcd, 2 cp and 2 worker nodes
- Select a control plane node and `Scale Down` the node
- Verify the node is deleted from cluster in Rancher and in backend
- Verify another node does NOT start provisioning
- verify the cluster state goes to updating and comes back up Active
- Verify the cluster has 1 control plane node

5. `Scale down` etcd nodes
- Create node driver RKE2 cluster - 3 etcd, 2 cp and 2 worker nodes
- Select _TWO etcd nodes_ and `Scale Down` the nodes
- Verify the 2 nodes are deleted from cluster in Rancher and in backend
- Verify no other nodes start provisioning
- verify the cluster state goes to updating and comes back up Active
- Verify the cluster has 1 etcd node

6. Add Worker nodes
7. Add Control plane nodes
8. Scale down a worker node pool
9. Scale down a control plane node pool
10. Scale up a worker node pool
11. Scale up a control plane node pool
12. Scale up an etcd node pool by 2 (to maintain etcd quorum)

**Comment by markusewalker** [comment]
This has been addressed in the Go framework under the `scale_replace_test.go` test. Closing issue.
