### ISSUE TITLE
Automate - usecases around crtb/prtb/rb

### ISSUE THREAD

**Issue by sowmyav27** [rancher/qa-tasks#811]
- Document the differences
- Identify usecases that can be automated (from older issues)
- Prioritize these usecases and scope for Q3 and Q4 releases

**Comment by dasarinaidu** [comment]
**Automate CRTB tests :**
1. Validate CRUD operations with Steve(V1) endpoint related to CRTB  https://github.com/rancher/qa-tasks/issues/922 
2. Validate CRTB related tests by using kubectl https://github.com/rancher/qa-tasks/issues/923

**Automate PRTB tests :**
1. Validate CRUD operations with Steve(V1) endpoint related to PRTB https://github.com/rancher/qa-tasks/issues/925
2. Validate PRTB related tests by using kubectl https://github.com/rancher/qa-tasks/issues/924

**Automate GR and GRB tests :**
1. Validate CRUD operations with Steve(V1) endpoint related to GR and GRB https://github.com/rancher/qa-tasks/issues/926
2. Validate BR and GRB related tests by using kubectl https://github.com/rancher/qa-tasks/issues/927

**Comment by dasarinaidu** [comment]
We created sub cards and closing this one.
