### ISSUE TITLE
Update automation Jenkinsfiles to default branches to release/v2.8 rather than release/v2.6

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#812]

**Comment by bmdepesa** [comment]
How would branching for v2.8 impact the default branches that we want to use? This might need followup design discussion.

**Comment by bmdepesa** [comment]
This will require updating the Jenkinsfiles as well as the jenkins job builder yamls

**Comment by floatingman** [comment]
@bmdepesa @igomez06 Should I update all Jenkinsfiles in the test directory of Rancher.  I noticed that some Jenkinsfiles have release/v2.7 and some have release/v2.6 specified

**Comment by igomez06** [comment]
> @bmdepesa @igomez06 Should I update all Jenkinsfiles in the test directory of Rancher. I noticed that some Jenkinsfiles have release/v2.7 and some have release/v2.6 specified

Yes all Jenkins files please
