### ISSUE TITLE
Upgrade HA Release Test Maintenance

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#832]
- [x] Fix secret type that's used in workload pre/post upgrade tests [#42341](https://github.com/rancher/rancher/pull/42341)
- [x] Update Provisioning Test Configurations After the Provisioning Tests Refactor

A sanity check before the release time frame should be provided.

**Comment by bmdepesa** [comment]
Requires provisioning refactor that is still in review https://github.com/rancher/rancher/pull/41930

**Comment by caliskanugur** [comment]
This ticket will be used for two separate PRs. The first item needs to be addressed before any release testing.
