### ISSUE TITLE
Investigate if provisioning tests can be run in parallel

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#841]
for provisioning tests via the framework, we should add an option in the user config to run them in parallel vs. sequentially.

**Comment by igomez06** [comment]
Due to using testify to run our test suites, there could be an issue with running provisioning in parallel specifically since the actual provisioning is done in a suite.Run(). Needs more investigation.

**Comment by slickwarren** [comment]
we decided not to run in parallel for now, we can look into this later if we decide we need it.
