### ISSUE TITLE
[scale-testing] Investigate k8s upstream soak test for potential usage as healthcheck datapoint

### ISSUE THREAD

**Issue by git-ival** [rancher/qa-tasks#847]
We would like to implement soak testing into our scale/perf testing. We should investigate what upstream has for this and determine if the datapoints generated by their testing would be valuable for healthcheck purposes.

See the soak test here: https://github.com/kubernetes/kubernetes/blob/master/test/soak/serve_hostnames/README.md

**Comment by bmdepesa** [comment]
Host our changes somewhere
Documentation should live in the readme
Eventually document it as part of our perf checks.
