### ISSUE TITLE
Create a script which can output object/CR counts from a cluster

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#853]
Create a script which can output object/CR counts from a cluster. 

One of the issues we have recently seen is that some types of resources have very large counts that are unexplained. We would like to be able to see when resource counts increase beyond expectations. 

Something like this may exist already externally or from Dashboard/UI.

**Comment by moio** [comment]
Suggestion: ask @rbreddy

**Comment by moio** [comment]
In the UI this is visible under 

`Home -> About -> Diagnostics`

Is there anything more/else needed?

**Comment by bmdepesa** [comment]
This has already been completed @moio, but yes we needed a programmatic way to get this so we can run it at scheduled times for our long living and environments under test during release testing.
