### ISSUE TITLE
Fix CheckETCDVersion extension

### ISSUE THREAD

**Issue by igomez06** [rancher/qa-tasks#861]
Currently the extension: https://github.com/rancher/rancher/blob/release/v2.7/tests/framework/extensions/rke1/componentchecks/etcdversion.go is design in such a that when nodeRoles is set with multiple nodes per role, it will panic with an index out of range error. We need to redesign the extension to work in way that we don't rely on an input from the user but from metadata from the actual node.

**Comment by markusewalker** [comment]
Installed.
