### ISSUE TITLE
Automate enabling/disabling openLDAP auth provider in Rancher

### ISSUE THREAD

**Issue by ronhorton** [rancher/qa-tasks#874]
**Description**
Add go-framework automation tests to enable and disable openLDAP authentication provider in Rancher.

**Tests**
`I. Enabling OpenLDAP Authentication`
1. verify that rancher can successfully enable the openLDAP authentication provider.
2. Confirm that Rancher prompts the user for the necessary OpenLDAP credentials/configuration (e.g., LDAP server, Base DN, Bind DN, etc.)
3. Ensure that once enabled, users can successfully authenticate against the openLDAP directory.
4. Validate that user roles and permissions are properly managed based on openLDAP group memberships.

`II. Disabling OpenLDAP Authentication`
1. Verify that rancher can successfully disable the openLDAP authentication provider.
2. Confirm that all users are signed out.
3. Confirm that OpenLDAP users can no longer authenticate.
4. Confirm that OpenLDAP configuration objects are removed from rancher. 

**Steps**
1. Enable an Auth
2. Verify auth is enabled
3. Login using an Auth std user
4. Disable Auth
5. Verify auth is disabled
6. Verify an Auth std user cannot login.

**Comment by ronhorton** [comment]
update: 
created openldap and openldap_test files
currently working on func to marshal json for enable of openldap
disable func works
login func returns 422 - also need to debug that

what remains: 
enable func 
debug login
PR

**Comment by ronhorton** [comment]
update:
all funcs working
refactored
enable func getting a 401 - debugging

**Comment by sowmyav27** [comment]
will be done as part of this issue - https://github.com/rancher/qa-tasks/issues/1283.
Closing this issue.
