### ISSUE TITLE
Create new repo for Bullseye QA

### ISSUE THREAD

**Issue by bmdepesa** [rancher/qa-tasks#881]
Create a new repo for Bullseye QA tools - probably have the new scale/perf testing framework in here as well 

- [x] Add the object count script
- [x] Add the modified soak test script

Refer to https://github.com/rancherlabs/eio/issues/1755 for template

**Comment by git-ival** [comment]
Will temporarily be working in a personal repository until we have something more sizable that would require an org-level repository.
