### ISSUE TITLE
Edit max job history for k3s/RKE2/HA jobs in Jenkins

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/qa-tasks#89]
Having the ability to add description to the job we run would beneficial to track the progress and identify our jobs without having to look at the parameters.

Secondly increase Max # of jobs to keep as jenkins is widely used by all QA's and sometimes we would want to refer to the results of the earlier job.

**Comment by bmdepesa** [comment]
Permissions issue is resolved.

**Comment by rancher-max** [comment]
Max # of jobs to keep issue is also resolved now
