### ISSUE TITLE
Add snapshot retention check to snapshot_backup_restore_test.go

### ISSUE THREAD

**Issue by susesgartner** [rancher/qa-tasks#895]
Currently we don't check that the retention policy is respected i.e make sure that a only the retention amount is stored.
Ticket that brought this to light: https://github.com/rancher/rancher/issues/38711

Update the test snapshot_backup_restore_test.go. 

[Rancher PR](https://github.com/rancher/rancher/pull/44535)
[Shepard PR](https://github.com/rancher/shepherd/pull/75)

**Comment by markusewalker** [comment]
Merged.
