### ISSUE TITLE
add validation for snapshots on s3

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#896]
currently, logic to snapshot to s3 is in / working, but we don't have logic in the test to select the s3 (vs local) snapshot when restoring. We should add this so that s3 etcd restore testing can be completely automated

**Comment by slickwarren** [comment]
note: before the refactor, there was a prefix added to check for s3 https://github.com/rancher/rancher/pull/41764/files

**Comment by markusewalker** [comment]
Closing this as this is going to be addressed in https://github.com/rancher/qa-tasks/issues/986.
