### ISSUE TITLE
add kubeCTL framework extension

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#899]
we have upcoming work that will require the use of kubectl. I see that we have an extensions/kubeapi (which we will also need) but the current requirements are calling for both.

**Comment by sowmyav27** [comment]
@anupama2501 Does your recent PR cover this? (The one that Andrew was waiting for his Public api changes)

**Comment by brudnak** [comment]
https://github.com/rancher/shepherd/pull/17
