### ISSUE TITLE
GB and GRB : Automate k8 operations via kubectl

### ISSUE THREAD

**Issue by dasarinaidu** [rancher/qa-tasks#927]
1. Validate kubectl explain GR and GRBs

2. Validate positive and negative tests while retrieving GR and GRBs by using kubectl

3. Validate positive and negative tests while creating GR and GRBs by using kubectl

4. Validate positive and negative tests while updating GR and GRBs by using kubectl

5. Validate positive and negative tests while deleting GR and GRBs by using kubectl

**Comment by brudnak** [comment]
duplicate
