### ISSUE TITLE
[Spike] Investigate what the business cost might look like for our nighly automation runs

### ISSUE THREAD

**Issue by davidnuzik** [rancher/qa-tasks#93]
Based on our 4/16/21 QA Sync call, we talked about the value of getting a (rough) idea on the potential business cost for running our nightly tests with the full wide breadth of environments (the full OS / Database / etc array Shylaja has established in her project). 

Because we need to have some idea how long the tests might run on each environment we will need to capture this information first, if we don't have it yet. Can Shylaja provide this information?

Using this information, try to estimate what the costs might be to run these tests on the full array of environments each night. Just focus on the 80% of costs, don't get caught in the details such as network in/out costs, etc. Probably the highest costs are RDS, and ec2 nodes.

Dave took down notes from our discussion as a comment at the bottom of the https://confluence.suse.com/display/RKE2/March+2021+Patch+Releases+Post-Mortem confluence page.

**Comment by davidnuzik** [comment]
Follow up in 1-2 weeks. Given releases next week 4/19-4/23 will probably be busy. Just try to work on outside of releases and GitHub issue closure. This information is necessary to drive an initial implementation of a design doc for nightly automation runs.

**Comment by davidnuzik** [comment]
Link to Shylaja's spike: https://github.com/rancher/qa-tasks/issues/94

**Comment by rancher-max** [comment]
This is done and being added to the Nightly Automation Runs design doc.
