### ISSUE TITLE
Global roles v2 automation

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#930]
This serves as an epic to track the automated cases for global roles v2:

@anupama2501 
- [x] Automate P0 check   Fresh install - Create the inherited clusterRoles 
- [x] Automate P0 check Fresh install - Create   the inherited clusterRoles - Restricted admin
- [x] Automate Verify removing the label   authz.management.cattle.io/grb-owner is rejected by webhook
- [x] Automate Verify locked role templates   cannot be used in the global roles inherited cluster roles
- [x] Automate Add the role template in   inheritedClusterRoles and lock the role template
- [x] Automate Verify custom role templates   cannot be deleted when referred in global roles
- [x] Automate Verify adding a project role in   global roles >> inherited cluster roles    is rejected
- [x] Automate Escalation check: Create a   roletemplate with a bad user subject
- [x] Automate Escalation check: Create a   roletemplate with a bad group subject
- [x] Automate Escalation check: Create a CRTB   with the same subject, cluster and same grb owner, verify the CRTB is deleted
- [x] Automate Escalation check: Creating a   CRTB owned by a GRB in local cluster, should be removed as soon as its   created
- [x] Automate Verify global roles are not   accessible by standard user

@Priyashetty17 

- [x] Automate Fresh install - Create custom   roles and inherit the role[nested check]
- [x] Automate Update the existing user and add   the global role
- [x] Automate Create a global role with   multiple inheritedClusterRoles
- [x] Automate Fresh Install Create downstream   clusters after the global role is added to user should list the clusters for   the user
- [x] Automate Delete the inherited cluster   role and verify all users should lose access and CRTBs should be deleted
- [x] Automate Delete a downstream cluster and   verify the bindings are deleted
- [x] Automate Delete user and verify rbs and   grbs are removed
- [x] Automate Delete globalrolebinding and   ensure the CRTBs are deleted for the user

**Comment by Priyashetty17** [comment]
PR for my tests is up for review. 

What's pending: https://github.com/rancher/qa-tasks/issues/1038
- Add Cluster owner/member checks in few tests - This will be done when @anupama2501 's [RBAC Refactor PR](https://github.com/rancher/rancher/pull/43298) is merged

**Comment by Priyashetty17** [comment]
PR cannot be merged to v2.8 now because of the code freeze. Hence moving it to v2.8-Next1

**Comment by sowmyav27** [comment]
@anupama2501 @Priyashetty17 since its not in code freeze anymore, can we work on getting this merged?

**Comment by anupama2501** [comment]
Waiting on https://github.com/rancher/shepherd/pull/16 to be merged.

**Comment by anupama2501** [comment]
Closing this as the PRs for these have been merged.
