### ISSUE TITLE
Automate verification of role bindings and cluster role bindings created for each cluster role/project

### ISSUE THREAD

**Issue by anupama2501** [rancher/qa-tasks#943]
- [ ] ~Validate corresponding RB is created
- [ ] ~validate CRTB is created in the local cluster~
- [ ] ~Validate PRTB is created~
- [ ] ~Validate on deletion these get deleted~

**Comment by joesims22** [comment]
PRs have been merged

- https://github.com/rancher/rancher/pull/47447
- https://github.com/rancher/rancher/pull/47448
- https://github.com/rancher/rancher/pull/47449
- https://github.com/rancher/rancher/pull/47451
