### ISSUE TITLE
RHEL 9.1 OS Validation

### ISSUE THREAD

**Issue by daviswill2** [rancher/qa-tasks#945]
**On 2.8-alpha2 Rancher 1.27 24.0.x**
RHEL 9.1 AMI ID - ami-0014008b9a3c0182c

nm-cloud-setup is disabled in the AMI which is pre-requisite for creating a RKE2 and K3S clusters on RHEL.

- [ ] Downstream cluster checks

| OS and version  | Downstream Cluster Type | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| RHEL | RKE1 Custom  | Vivek :white_check_mark:  |Rishabh ✅ | Vivek ✅|
| RHEL| RKE1 Node Driver  | Vivek :white_check_mark: |Rishabh ✅ | Vivek ✅||
| RHEL  | RKE2 Custom  | Vivek :white_check_mark:  |Rishabh ✅ | Vivek ✅|||
| RHEL | RKE2 Node Driver  | Vivek :white_check_mark:  | Rishabh ✅ | Vivek ✅|||
| RHEL  | k3s Custom  | Vivek :white_check_mark: |Rishabh ✅ | Vivek ✅||
| RHEL  | k3s Node Driver  | Vivek :white_check_mark: |Rishabh ✅| Vivek ✅||

**Although Public AMI should be used for Node Driver cluster, a Public AMI with pre-requisites is not available. Hence a Private AMI was used for Node Driver cluster mentioned above.**

- [ ] Rancher local cluster checks

| OS and version  | Downstream Cluster Type  | G1 | G2 | G3 | G4 | G5 | G6 |
|---|---|---|---|---|---|---|---|
| RHEL| RKE1 Imported   | Vivek :white_check_mark: |Rishabh ✅ | Vivek ✅|
|RHEL| RKE2 Imported   | Vivek :white_check_mark: | Rishabh ✅| Vivek ✅|
| RHEL| K3s Imported   |  Vivek :white_check_mark: |Rishabh ✅ | Vivek ✅|

---

**Comment by mitulshah-suse** [comment]
Closing the issue since there is no further testing planned for this.
