### ISSUE TITLE
[dartboard] Automate LLE K8s upgrade scenario

### ISSUE THREAD

**Issue by git-ival** [rancher/qa-tasks#951]
- [ ] add jenkins-job-builder config yaml for LLE jobs
- [ ] add Jenkinsfile to `dartboard` at `tests/lle/`
- [ ] add Dockerfile to `dartboard` at `tests/lle/`

**Comment by git-ival** [comment]
WIP jenkins-job-builder config yaml has been created
Work on Jenkinsfile was started, but is postponed until [this PR](https://github.com/rancher/rancher/pull/42650) is merged

**Comment by rancher-max** [comment]
We are handling this as part of separate work items, so closing this issue.
