### ISSUE TITLE
[dartboard] Draft design doc

### ISSUE THREAD

**Issue by git-ival** [rancher/qa-tasks#968]
We need to solidify some aspects of what `dartboard` is and what we want to accomplish with it.

Must cover:
- CI tool
- Core codebase/orchestrator
- Test management tool
- IaC tool(s)
- Benchmarking or load tool(s)
- Results/data storage tool(s)
- How these components will integrate at a high-level
  - Bonus for any specific low-level details

**Comment by moio** [comment]
Internal reference: https://confluence.suse.com/display/RANQA/Draft%3A+Design+Doc

**Comment by sowmyav27** [comment]
Draft Design doc is up and is under Review. Closing this and logging a new one to finalize the design.
