### ISSUE TITLE
Investigate fails on ha job with AdminPasssword

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/qa-tasks#97]
HA job is expected to set default password after job is complete, instead the current behavior is it asks for new password while logging into Rancher.

Error in console around array indexing
```
         admin_user = client.list_user(username="admin").data
 >       admin_user[0].setpassword(newPassword=ADMIN_PASSWORD)
 E       IndexError: list index out of range
```

**Comment by rancher-max** [comment]
I noticed this yesterday too, and I believe it is an IOPS issue. I wrote up my findings in [this issue](https://github.com/rancher/rancher/issues/35482#issuecomment-1032015575) that is also related (noticed in the rancher server logs when this console error was happening).

As part of my PR to jenkins-job-builder, I included some additional AMIs to use where we don't see this. @ShylajaDevadiga  Do you think we should try the job out more when using those (or 50GB Volume Size), and if we don't see this issue then close it?

**Comment by rancher-max** [comment]
We've been using this for a while now and it seems to be working, so I'm going to close this out.
