### ISSUE TITLE
Update Ontag Matrix Jenkinsfile Regex to also run on "alpha" tags

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#995]
Update the ontag matrix Jenkinsfile regex (https://github.com/rancher/rancher/blob/release/v2.8/tests/validation/tests/v3_api/scripts/pipeline/Jenkinsfile_ontag_matrix#L35) to run on `-alpha` and `-rc` versions.

**Comment by bmdepesa** [comment]
```def String rancher_version_regex = "^v[\\d]\\.[\\d]\\.[\\d]([\\-rc\\d]|[\\-alpha\\d])+\$"```

Will need to be updated for all ontag Jenkinsfiles

We can test with a dummy Jenkinsfile & Jenkins job using some image other than Rancher and tagging/pushing to dockerhub

**Comment by caliskanugur** [comment]
Closing in favor of https://github.com/rancher/qa-tasks/issues/1213
